org.eclipse.dirigible/org.eclipse.dirigible.parent/runtime/org.eclipse.dirigible.runtime.scheduler/src/org/eclipse/dirigible/runtime/scheduler/SchedulerServlet.java

-shut down the jobsSynchronizerScheduler
-fix the broken synchronization
-change the started status on shutdown

Fix SchedulerServlet shutdown procedure.

---

org.eclipse.dirigible/org.eclipse.dirigible.parent/runtime/org.eclipse.dirigible.runtime.core.test/src/org/eclipse/dirigible/runtime/scripts/XMLUtilsTest.java

Signed-off-by: Aleks Kushev <aleks.kushev@sap.com>

fixing XMLUtilsTest

---

org.eclipse.dirigible/org.eclipse.dirigible.parent/runtime/org.eclipse.dirigible.runtime.flow/src/org/eclipse/dirigible/runtime/flow/FlowsActivator.java
org.eclipse.dirigible/org.eclipse.dirigible.parent/runtime/org.eclipse.dirigible.runtime.flow/src/org/eclipse/dirigible/runtime/job/JobsUpdater.java
org.eclipse.dirigible/org.eclipse.dirigible.parent/runtime/org.eclipse.dirigible.runtime.flow/src/scheduler.properties

Signed-off-by: Svetlin Zarev <svetlin.zarev@sap.com>

Shutdown the quartz scheduler on bundle stop

---

org.eclipse.dirigible/org.eclipse.dirigible.parent/runtime/org.eclipse.dirigible.runtime.init/src/org/eclipse/dirigible/runtime/content/AnonymousUserServlet.java
org.eclipse.dirigible/org.eclipse.dirigible.parent/runtime/org.eclipse.dirigible.runtime.ui/resources/ui/anonymous.html

Fix: https://bugs.eclipse.org/bugs/show_bug.cgi?id=482198

Implement anonymous user name validation

---

modules/database-persistence/pom.xml
modules/database-persistence/src/main/java/org/eclipse/dirigible/database/persistence/PersistenceManager.java
modules/database-persistence/src/main/java/org/eclipse/dirigible/database/persistence/processors/entity/PersistenceInsertProcessor.java
modules/database-persistence/src/main/java/org/eclipse/dirigible/database/persistence/processors/entity/PersistenceUpdateProcessor.java

First part of  #193 - the update and insert statements to accept generic type instead of object.

Improve the usage of generic types in database-persistence module

---

modules/database/database-persistence/src/main/java/org/eclipse/dirigible/database/persistence/model/PersistenceTableColumnModel.java

Added additional constructor to PersistenceTableColumnModel

Constructor

---

modules/database/database-persistence/src/main/java/org/eclipse/dirigible/database/persistence/model/PersistenceTableColumnModel.java

Empty constructor to PersistenceTableColumnModel

Empty constructor

---

modules/repository/repository-api/src/main/java/org/eclipse/dirigible/repository/api/RepositoryPath.java

Signed-off-by: km2k@mail.bg
Fixes the Windows paths in Repository
https://github.com/eclipse/dirigible/issues/505

windows pats fix

---

api/api-facade/api-tests/src/main/resources/core/v3/env/get.js
api/api-facade/api-tests/src/main/resources/core/v4/env/get.js

Fix JS test for environment variables for v3 and v4
https://github.com/eclipse/dirigible/issues/505

Fix in tests for getting environment from JS code

---

ide/services/ide-bpm/pom.xml
modules/bpm/bpm-flowable/pom.xml
modules/core/core-generation-javascript/pom.xml
modules/core/core-messaging/pom.xml
modules/core/core-migrations/pom.xml
modules/engines/engine-job/pom.xml
modules/engines/engine-listener/pom.xml
releng/server-database/pom.xml

Signed-off-by: konstantinmomchev <konstantin.momchev@sap.com>

Rhino to Graalvm dependendy fixes.

---

modules/engines/engine-odata/src/test/resources/META-INF/persistence.xml
releng/server-all/.classpath
releng/server-all/.settings/org.eclipse.core.resources.prefs
releng/server-all/.settings/org.eclipse.wst.common.component

Signed-off-by: Dan Price <g051051+eclipse@gmail.com>
Due to inclusion of private Eclipse workspace files in GitHub, there appears to be a synchronization issue with Maven.  Some Eclipse files had what seem to be old, outdated references.
Also a persistence.xml file had the package name of some test classes wrong, probably missed during a refactoring event.
Removes outdated references, fixes the package names in the persistence.xml file.

Fix various errors and warnings with Eclipse build.

---

pom.xml

Updates ActiveMQ version to get around a problem with using Postgres.
Issue #316

Issue 316 postgre sql   could not create activemq msgs table

---

modules/services/service-core/src/main/java/org/eclipse/dirigible/runtime/core/initializer/DirigibleInitializer.java

Signed-off-by: GrozevJunior <georgi.grozev@sap.com>

Catch Throwable instead of Exception

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/AbstractSqlBuilder.java

Signed-off-by: antoanetamh <antoanetamh@gmail.com>
changing the regex expression to exclude the symbol ::
Fix issue #770

update regexp to handle namespace::objectName

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/AbstractSqlBuilder.java

https://github.com/eclipse/dirigible/issues/774

update regex to handle dash symbol

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/AbstractSqlBuilder.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/test/SelectTest.java

https://github.com/eclipse/dirigible/issues/774

add tests for encapsulatemany

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/AbstractSqlBuilder.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/test/DeleteTest.java

https://github.com/eclipse/dirigible/issues/797

[API] AbstractSqlBulder - content between single quotes

---

ide/ui/ide-workspace/src/main/resources/ide-workspace/workspace.js

https://github.com/eclipse/dirigible/issues/819

add dirigible-editor header on saveFile

---

modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/service/ODataCoreService.java

https://github.com/eclipse/dirigible/issues/821

add SAPData annotation declaration

---

ide/ui/ide-workspace/src/main/resources/ide-workspace/workspace.js

https://github.com/eclipse/dirigible/issues/846
https://github.com/eclipse/dirigible/issues/845

fix issue with create and delete of .xsodata

---

.gitignore
releng/Dockerfile-tomcat
releng/anonymous-all/Dockerfile-base
releng/anonymous-runtime/Dockerfile-base
releng/openshift-all/Dockerfile-base
releng/sap-cf-all/Dockerfile-base
releng/sap-cf-runtime/Dockerfile-base
releng/sap-kyma-all/Dockerfile-base
releng/sap-kyma-runtime/Dockerfile-base
releng/server-all/Dockerfile-base
releng/server-oauth/Dockerfile-base
releng/server-runtime/Dockerfile-base
releng/trial-all/Dockerfile-base

Update hana driver

---

api/api-facade/api-security/src/main/java/org/eclipse/dirigible/api/v3/security/UserFacade.java
api/api-javascript/api-security/src/main/resources/security/v4/user.js

What does this PR do?
Adds UserFacade methods that are necessary for the implementation of the session API in the xsk project.
What issues does this PR fix or reference?
This PR is related to an issue inside the xsk project - https://github.com/SAP/xsk/issues/11
Documentation
Documentation will be provided inside the xsk wiki

Implement methods for session API in xsk

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/table/AbstractTableBuilder.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/test/hana/CreateTableTest.java

https://github.com/eclipse/dirigible/issues/877

add composite primary key supportability

---

CONTRIBUTING.md

Updates the CONTRIBUTING document, fixing typos and adding new information.

Updated contributing document

---

README.md

Fixes the wrong folder name in the build section in the README

Fixed folder name

---

ide/ui/ide-core/src/main/resources/ide-core/ui/ui-core-ng-modules.js
ide/ui/ide-core/src/main/resources/ide-core/ui/ui-layout.js

Disables the 'open in new window' option in the GoldenLayout global configuration.
Fixes issue #879

Updated ide-core, disabled 'open in new window' option

---

README.md
pom.xml

Updates the build instructions to include skipping all tests, javadocs and compiling with threads.

Update build instructions

---

ide/ui/ide-core/src/main/resources/ide-core/ui/ui-core-ng-modules.js
ide/ui/ide-core/src/main/resources/ide-core/ui/ui-layout.js

Adds support for tab and layout settings from GoldenLayout. This enables per view and per layout configuration.

Added view and layout settings

---

ide/ui/ide-core/src/main/resources/ide-core/ui/ui-layout.js

Fixes issue #898 where view groups/layouts should not be closable.

Changed default layout settings. Fixes #898

---

ide/ui/ide-workbench/src/main/resources/ide/index.html

Adds view settings to "Workspace" and "Import" in ide-workbench, making them non closable. Fixes #899

Adding view settings to "Workspace" and "Import". Fixes #899

---

releng/desktop-all/pom.xml

Removed terminal dependency from the `desktop-all` build artifact. Fixes #864

Removed terminal dependency for desktop-all

---

resources/resources-theme-fiori/src/main/resources/theme-fiori/extensions/theme.js
resources/resources-theme-fiori/src/main/resources/theme-fiori/ide.css
resources/resources-theme-fiori/src/main/resources/theme-fiori/monaco.js
resources/resources-theme-fiori/src/main/resources/theme-fiori/project.json

Contains fixes for horizontal scroll, misaligned headers and status bar. Fixes #909

Fiori theme fixes for horizontal scroll, misaligned headers and status bar

---

ide/ui/ide-core/src/main/resources/ide-core/ui/ui-layout.js

Fixes #900
The 'Welcome' tab in the workbench and git perspectives is now unclosable.

Added special treatment for the welcome tab.

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/table/AbstractTableBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/table/CreateTableBuilder.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/test/hana/CreateTableTest.java

fixed https://github.com/eclipse/dirigible/issues/913

fix issue with dublicate primarykey in SQL assemble string

---

ide/ui/ide-core/src/main/resources/ide-core/ui/ui-core-ng-modules.js

Exposes 'set current workspace' functionality and adds new 'open perspective' API calls.
Fixes #920 and #922

Fixes #920 and #922

---

modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/service/ODataCoreService.java
modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/synchronizer/ODataSynchronizer.java

resolve https://github.com/eclipse/dirigible/issues/918

fix issue with missing table DIRIGIBLE_ODATA_HANDLER

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/table/CreateTableBuilder.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/test/hana/CreateTableTest.java

resolve https://github.com/eclipse/dirigible/issues/929

allow creating of table without PK definition

---

modules/odata/odata-core/pom.xml
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/expression/SQLExpressionDelete.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/expression/SQLExpressionInsert.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/expression/SQLExpressionSelect.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/expression/SQLExpressionUpdate.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/expression/SQLExpressionUtils.java
modules/odata/odata-core/src/test/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLQueryTest.java
modules/odata/odata-core/src/test/java/org/eclipse/dirigible/engine/odata2/sql/processor/DefaultSQLProcessorTest.java

Fixed an issue creating wrong sql for post/put/merge of OData2 entities
Added OData2 tests for post/put/merge
Added compatibility for java 1.8 for the OData2 core module
Fixed a bug that prevents post/put/merge of OData2 entities

Fixed a bug with ODATA update/create of entities

---

ide/ui/ide-preview/src/main/resources/ide-preview/preview.js
modules/commons/commons-api/src/main/java/org/eclipse/dirigible/commons/api/helpers/ContentTypeHelper.java

Added CSV content type support in the back-end and updated ide-preview to ignore CSV files. Fixes #940

Added CSV support

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/hana/HanaSqlDialect.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/test/hana/SynonymTest.java

resolve https://github.com/eclipse/dirigible/issues/948

check of synonym existence

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/DatabaseArtifactTypes.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/ISqlDialect.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/ISqlFactory.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/ISqlKeywords.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/SqlFactory.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/CreateBranchingBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/DropBranchingBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/schema/CreateSchemaBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/schema/DropSchemaBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/DefaultSqlDialect.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/hana/HanaSqlDialect.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/test/SchemaTest.java
pom.xml

resolve https://github.com/eclipse/dirigible/issues/951

check of exist schema

---

ide/ui/ide-preview/src/main/resources/ide-preview/preview-view.js
ide/ui/ide-preview/src/main/resources/ide-preview/preview.js

Updates ide-preview, adding exceptions for csvim and hdbti files.

Updated ide-preview

---

modules/database/database-data-models/src/main/java/org/eclipse/dirigible/database/ds/model/transfer/TableMetadataHelper.java
modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/transformers/DBMetadataUtil.java

resolve https://github.com/eclipse/dirigible/issues/958

logic for specific schema

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/table/AbstractTableBuilder.java

Fixes https://github.com/eclipse/dirigible/issues/965

Fixes index referenced columns encapsulation

---

ide/services/ide-core/pom.xml
ide/services/ide-core/src/main/java/org/eclipse/dirigible/runtime/ide/core/synchronizer/IDECoreSynchronizer.java
modules/commons/commons-health/.gitignore
modules/commons/commons-health/pom.xml
modules/commons/commons-health/src/main/java/org/eclipse/dirigible/commons/health/HealthStatus.java
modules/commons/commons-timeout/.gitignore
modules/commons/commons-timeout/pom.xml
modules/commons/commons-timeout/src/main/java/org/eclipse/dirigible/commons/timeout/TimeLimited.java
modules/commons/pom.xml
modules/core/core-scheduler/pom.xml
modules/core/core-scheduler/src/main/java/org/eclipse/dirigible/core/scheduler/api/AbstractSynchronizerJob.java
modules/core/core-scheduler/src/main/java/org/eclipse/dirigible/core/scheduler/manager/SchedulerInitializer.java
modules/services/service-core/pom.xml
modules/services/service-core/src/main/java/org/eclipse/dirigible/runtime/core/filter/HealthCheckFilter.java
modules/services/service-core/src/main/java/org/eclipse/dirigible/runtime/core/services/HealthCheckRestService.java

health and timeout as separate modules

health and timeout as separate modules

---

modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/AbstractSQLProcessor.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/utils/OData2Utils.java

Have more flexibility on customising properties that come from different DBs

Added hooks to customise property values for more flexibility

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/ISqlKeywords.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/CreateBranchingBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/DropBranchingBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/tableType/CreateTableTypeBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/tableType/DropTableTypeBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/hana/HanaCreateBranchingBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/hana/HanaCreateTableTypeBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/hana/HanaDropBranchingBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/hana/HanaDropTableTypeBuilder.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/test/hana/CreateTableTypeTest.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/test/hana/DropTableTypeTest.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/test/mysql/CreateTableTypeTest.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/test/mysql/DropTableTypeTest.java

Implements builders for .hdbstructure artifact

Implementing Drop/Create Builder for TableTypе

---

modules/cms/cms-resources/ide-csv/src/main/resources/ide-csv/js/editor.js

Updates ide-csv and fixes issues #992 and #993 .

Updated ide-csv module

---

ide/ui/ide-core/src/main/resources/ide-core/ui/ui-core-ng-modules.js
ide/ui/ide-core/src/main/resources/ide-core/ui/ui-layout.js
modules/cms/cms-all/pom.xml
modules/cms/cms-resources/ide-csv/src/main/resources/ide-csv/js/editor.js
modules/cms/cms-resources/ide-csvim/.gitignore
modules/cms/cms-resources/ide-csvim/pom.xml
modules/cms/cms-resources/ide-csvim/src/main/resources/ide-csvim/css/dropdown.css
modules/cms/cms-resources/ide-csvim/src/main/resources/ide-csvim/css/editor.css
modules/cms/cms-resources/ide-csvim/src/main/resources/ide-csvim/editor.html
modules/cms/cms-resources/ide-csvim/src/main/resources/ide-csvim/extensions/csvim-editor.extension
modules/cms/cms-resources/ide-csvim/src/main/resources/ide-csvim/js/editor.js
modules/cms/cms-resources/ide-csvim/src/main/resources/ide-csvim/project.json
modules/cms/cms-resources/ide-csvim/src/main/resources/ide-csvim/services/csvim-editor.js
modules/cms/cms-resources/pom.xml

Adds an editor for csvim files, updates ide-core and ide-csv, fixes #947

CSVIM editor

---

modules/cms/cms-resources/ide-csv/src/main/resources/ide-csv/js/editor.js

CSV Editor, fixed #1002 and #1003

---

modules/cms/cms-resources/ide-csv/src/main/resources/ide-csv/css/editor-dark.css
modules/cms/cms-resources/ide-csv/src/main/resources/ide-csv/css/editor-light.css
modules/cms/cms-resources/ide-csv/src/main/resources/ide-csv/editor.html
modules/cms/cms-resources/ide-csv/src/main/resources/ide-csv/js/editor.js
modules/cms/cms-resources/ide-csvim/src/main/resources/ide-csvim/css/dropdown-dark.css
modules/cms/cms-resources/ide-csvim/src/main/resources/ide-csvim/css/dropdown-light.css
modules/cms/cms-resources/ide-csvim/src/main/resources/ide-csvim/css/editor-dark.css
modules/cms/cms-resources/ide-csvim/src/main/resources/ide-csvim/css/editor-light.css
modules/cms/cms-resources/ide-csvim/src/main/resources/ide-csvim/editor.html
modules/cms/cms-resources/ide-csvim/src/main/resources/ide-csvim/js/editor.js

Introduces dark mode support for the csv and csvim editors.
Fixes csvim editor infinite loading on empty files.
Replaces synchronous with asynchronous http calls for improving the user experience.
Fixes issues #1016 #1015 #1014 #1009

Various fixes for csv and csvim editors

---

modules/cms/cms-resources/ide-csv/src/main/resources/ide-csv/editor.html
modules/cms/cms-resources/ide-csvim/src/main/resources/ide-csvim/editor.html

Capitalizes text in menus and buttons. Fixes #1033

Capitalized text in menus and buttons

---

ide/ui/ide-monaco/src/main/resources/ide-monaco/monaco-editor.js
modules/commons/commons-api/src/main/java/org/eclipse/dirigible/commons/api/helpers/ContentTypeHelper.java

Adding HDBTI mime-type support

---

ide/ui/ide-core/src/main/resources/META-INF/dirigible/ide-core/ui/ui-core-ng-modules.js
modules/cms/cms-resources/ide-csv/src/main/resources/META-INF/dirigible/ide-csv/js/editor.js
modules/cms/cms-resources/ide-csvim/src/main/resources/META-INF/dirigible/ide-csvim/editor.html
modules/cms/cms-resources/ide-csvim/src/main/resources/META-INF/dirigible/ide-csvim/js/editor.js
resources/resources-theme-default/src/main/resources/META-INF/dirigible/theme-default/csvim.css
resources/resources-theme-default/src/main/resources/META-INF/dirigible/theme-default/ide.css
resources/resources-theme-fiori/src/main/resources/META-INF/dirigible/theme-fiori/csvim.css
resources/resources-theme-fiori/src/main/resources/META-INF/dirigible/theme-fiori/ide.css

Fixes #1069 #1067 #1066 #1065 issues.

Various editor fixes

---

modules/cms/cms-resources/ide-csvim/src/main/resources/META-INF/dirigible/ide-csvim/js/editor.js

Fix for #1072

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/DatabaseArtifactTypes.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/table/CreateTablePrimaryKeyBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/tableType/CreateTableTypeBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/hana/HanaCreateTableTypeBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/hana/HanaSqlDialect.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/test/hana/CreateTableTypeTest.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/test/mysql/CreateTableTypeTest.java

Extending TableTypeBuilders functionality to support primary keys definition

Adjusting TableTypeBuilders to support primary keys for Type definition

---

modules/cms/cms-resources/ide-csvim/src/main/resources/META-INF/dirigible/ide-csvim/js/editor.js

Fixes for the CSVIM editor

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/AbstractSqlBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/hana/HanaSqlDialect.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/test/CreateTableTest.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/test/mysql/CreateTableTest.java

resolve https://github.com/eclipse/dirigible/issues/1099

add schema to exist on table type

---

ide/services/ide-workspaces/src/main/java/org/eclipse/dirigible/runtime/ide/workspaces/processor/WorkspaceProcessor.java
ide/services/ide-workspaces/src/main/java/org/eclipse/dirigible/runtime/ide/workspaces/processor/WorkspaceSourceTargetPair.java
ide/services/ide-workspaces/src/main/java/org/eclipse/dirigible/runtime/ide/workspaces/service/WorkspaceManagerService.java
ide/ui/ide-git/src/main/resources/META-INF/dirigible/ide-git/git/git.html
ide/ui/ide-workspace/src/main/resources/META-INF/dirigible/ide-workspace/workspace.html
ide/ui/ide-workspace/src/main/resources/META-INF/dirigible/ide-workspace/workspace.js
modules/commons/commons-api/src/main/java/org/eclipse/dirigible/commons/api/helpers/FileSystemUtils.java
resources/resources-theme-default/src/main/resources/META-INF/dirigible/theme-default/ide.css
resources/resources-theme-fiori/src/main/resources/META-INF/dirigible/theme-fiori/ide.css

Fixes #1094 #1093 #1092 #1091 #1090 #1087 #982

Various workspace fixes

---

ide/services/ide-workspaces/src/main/java/org/eclipse/dirigible/runtime/ide/workspaces/processor/WorkspaceProcessor.java
modules/commons/commons-api/src/main/java/org/eclipse/dirigible/commons/api/helpers/FileSystemUtils.java

Fixes the storage memory leak caused by the new copy API functionality.
Fixes #1106 and #1107

Fix storage memory leak

---

modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/synchronizer/ODataSynchronizer.java
modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/transformers/DBMetadataUtil.java
modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/transformers/OData2ODataMTransformer.java
modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/transformers/OData2ODataXTransformer.java
modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/transformers/ODataMetadataUtil.java
modules/engines/engine-odata/src/test/java/org/eclipse/dirigible/engine/odata2/transformers/OData2ODataMTransformerTest.java
modules/engines/engine-odata/src/test/java/org/eclipse/dirigible/engine/odata2/transformers/OData2ODataTransformerTestUtil.java
modules/engines/engine-odata/src/test/java/org/eclipse/dirigible/engine/odata2/transformers/OData2ODataXTransformerTest.java
modules/engines/engine-odata/src/test/resources/entityproperty/Entities.odata
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/expression/SQLExpressionSelect.java
modules/odata/odata-core/src/test/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLQueryComplexTypeTest.java
modules/odata/odata-core/src/test/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLQueryExpandTest.java
modules/odata/odata-core/src/test/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLQueryNavigationPropertiesTest.java
modules/odata/odata-core/src/test/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLQueryTest.java

resolve https://github.com/eclipse/dirigible/issues/1122
resolve https://github.com/eclipse/dirigible/issues/1121

fix odata property validation issues

---

ide/ui/ide-core/src/main/resources/META-INF/dirigible/ide-core/ui/ui-layout.js
ide/ui/ide-git/src/main/resources/META-INF/dirigible/ide-git/git/git.html
ide/ui/ide-git/src/main/resources/META-INF/dirigible/ide-git/git/git.js
ide/ui/ide-git/src/main/resources/META-INF/dirigible/ide-git/index.html
ide/ui/ide-workspace/src/main/resources/META-INF/dirigible/ide-workspace/workspace.html
ide/ui/ide-workspace/src/main/resources/META-INF/dirigible/ide-workspace/workspace.js

Fixes some git and workspace view issues and introduces a new delete dialog.
#1125 #1124 #1105

Git and Workspace fixes

---

ide/services/ide-workspaces/src/main/java/org/eclipse/dirigible/runtime/ide/workspaces/processor/WorkspaceProcessor.java

Fixes project copy for single workspace
Fixes #1127

Workspace project copy fix

---

ide/ui/ide-git/src/main/resources/META-INF/dirigible/ide-git/git/git.html
ide/ui/ide-git/src/main/resources/META-INF/dirigible/ide-git/git/history.html
ide/ui/ide-git/src/main/resources/META-INF/dirigible/ide-git/git/history.js
ide/ui/ide-git/src/main/resources/META-INF/dirigible/ide-git/git/staging.html
ide/ui/ide-git/src/main/resources/META-INF/dirigible/ide-git/git/staging.js
ide/ui/ide-git/src/main/resources/META-INF/dirigible/ide-git/index.html
ide/ui/ide-monaco/src/main/resources/META-INF/dirigible/ide-monaco/diff-view.extension
ide/ui/ide-monaco/src/main/resources/META-INF/dirigible/ide-monaco/diff-view.html
ide/ui/ide-monaco/src/main/resources/META-INF/dirigible/ide-monaco/diff-view.js
ide/ui/ide-monaco/src/main/resources/META-INF/dirigible/ide-monaco/diff.html
ide/ui/ide-monaco/src/main/resources/META-INF/dirigible/ide-monaco/editor.html

Adds a new diff view, fixes some errors.
#1135
#1134

New diff view

---

modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLQuery.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLQueryBuilder.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/expression/SQLExpressionOrderBy.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/expression/SQLExpressionUtils.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/AbstractSQLProcessor.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/utils/OData2Utils.java
modules/odata/odata-core/src/test/java/org/eclipse/dirigible/engine/odata2/sql/ODataSQLProcessorTest.java
modules/odata/odata-core/src/test/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLQueryTest.java
modules/odata/odata-core/src/test/java/org/eclipse/dirigible/engine/odata2/sql/builder/expression/SQLExpressionOrderByTest.java

Fixes #1101
Order by on a member property for OData

Expand on member property for OData Fixed #1101

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/table/CreateTableBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/table/CreateTableForeignKeyBuilder.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/test/CreateTableTest.java

resolve https://github.com/eclipse/dirigible/issues/1151

add shema to foreign keys constraint

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/hana/HanaSqlDialect.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/test/hana/FunctionTest.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/test/hana/ProcedureTest.java

resolve https://github.com/eclipse/dirigible/issues/1181

find procedure nad function by schema

---

releng/Dockerfile-tomcat
releng/server-all/Dockerfile-base
releng/server-minimal/Dockerfile-base
releng/server-oauth/Dockerfile-base
releng/server-runtime/Dockerfile-base

This PR switches off check certificates due to wget/curl issues with https.

switching off check certificates due to wget/curl issues with https

---

ide/ui/ide-problems/src/main/resources/META-INF/dirigible/ide-problems/view/problems.html
ide/ui/ide-problems/src/main/resources/META-INF/dirigible/ide-problems/view/problems.js
modules/core/core-problems/src/main/java/org/eclipse/dirigible/core/problems/model/ProblemsModel.java

Resolves #1089 
Changes:
Inside ProblemsModel:
1. PROBLEM_LOCATION increased to 512
2. PROBLEM_CAUSE increased to 1024
3. PROBLEM_EXPECTED increased to 512
Sync problems.js and problems.html with dirigiblelabs/ide-problems.

Increase Poblems column sizes and sync with dirigiblelabs/ide-problems

---

modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/expression/SQLExpressionUpdate.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/AbstractSQLProcessor.java
modules/odata/odata-core/src/test/java/org/eclipse/dirigible/engine/odata2/sql/ODataSQLProcessorTest.java

Allows patch updates for the OData interface
Fixes #1102

Fix patch on entity that results in NPE: #1102

---

api/api-facade/api-mail/src/main/java/org/eclipse/dirigible/api/v3/mail/MailFacade.java
api/api-javascript/api-mail/src/main/resources/META-INF/dirigible/mail/v4/client.js

Changes:
- mail facade modified to accept parts (different mail body types) now
- js api provides functionality to send multipart email with plain/html text, attachments and inline content
- modified old send method to work the same way for backward compatibility
- catch errors from facade and log
Tested if dirigible mail samples works as expected:
```
var response = require("http/v4/response");
var mail = require("mail/v4/client");
var mailConfig = {
"mail.user": "<your-user>",
"mail.password": "<your-password>",
"mail.transport.protocol": "smtps",
"mail.smtps.host": "smtp.gmail.com",
"mail.smtps.port": "465",
"mail.smtps.auth": "true"
};
var mailClient = mail.getClient(mailConfig);
var from = "test@quanterall.com";
var recipients = {
to: "test@gmail.com",
cc: [],
bcc: []
};
var subject …
```

Mail api sending attachments and inline content

---

api/api-facade/api-tests/src/main/java/org/eclipse/dirigible/api/v3/test/AbstractApiSuiteTest.java
api/api-facade/api-tests/src/main/resources/META-INF/dirigible/utils/v4/qrcode/qrCode.js
api/api-facade/api-utils/pom.xml
api/api-facade/api-utils/src/main/java/org/eclipse/dirigible/api/v3/utils/QRCodeFacade.java
api/api-javascript/api-utils/src/main/resources/META-INF/dirigible/utils/v4/qrcode.js

Added feature for added QR Code generation.
- Added zxing dependency that allows us to generate a qr code based on input text. 
- The generated qr code is than saved in a png format in the specified workspace and project.

Added QR code generation API

---

modules/cms/cms-resources/ide-csvim/src/main/resources/META-INF/dirigible/ide-csvim/editor.html
modules/cms/cms-resources/ide-csvim/src/main/resources/META-INF/dirigible/ide-csvim/js/editor.js
resources/resources-theme-default/src/main/resources/META-INF/dirigible/theme-default/csvim.css
resources/resources-theme-default/src/main/resources/META-INF/dirigible/theme-default/ide.css
resources/resources-theme-fiori/src/main/resources/META-INF/dirigible/theme-fiori/csvim.css
resources/resources-theme-fiori/src/main/resources/META-INF/dirigible/theme-fiori/ide.css

Fixes issues with the CSVIM (and therefore HDBTI) editor, adds new warning label.
#1249

Fixed #1249

---

api/api-facade/api-tests/src/main/resources/META-INF/dirigible/utils/v4/qrcode/qrCode.js
api/api-javascript/api-utils/src/main/resources/META-INF/dirigible/utils/v4/qrcode.js

Changed function name from generateQRCodeByteArray to generateQRCode

Changed function name

---

ide/ui/ide-problems/src/main/resources/META-INF/dirigible/ide-problems/view/problems.html
ide/ui/ide-problems/src/main/resources/META-INF/dirigible/ide-problems/view/problems.js

Resolves #1185 , resolves #1241 , resolves #1242 
Changelog
1. Status values replaced by icons
2. Mark as and delete all buttons replaced by dropdown menu with actions for selected items
3. Double clicking any row will open the corresponding file in the editor
4. Removed unnecessary columns from the initial view
5. Large columns now have fixed length and cut off content that is too long
6. Added "Expand" button to every row for viewing all columns and full column contents inside a modal dialog

Sync ide-problems with dirigiblelabs

---

ide/ui/ide-workbench/src/main/resources/META-INF/dirigible/ide/index.html

Fixes alert dialogs in the workbench perspective.
#1258

Fixed #1258

---

ide/ui/ide-workspace/src/main/resources/META-INF/dirigible/ide-workspace/workspace.js

Opened files in IDE are now closed on project delete

---

ide/ui/ide-git/src/main/resources/META-INF/dirigible/ide-git/git/git.js
modules/commons/commons-api/src/main/java/org/eclipse/dirigible/commons/api/artefacts/IArtefactDefinition.java

Fixes branch listing in the Git perspective
#1284

Git branch fix

---

ide/ui/ide-monaco/src/main/resources/META-INF/dirigible/ide-monaco/js/editor.js
ide/ui/ide-monaco/src/main/resources/META-INF/dirigible/ide-monaco/monaco-editor.js
ide/ui/ide-preview/src/main/resources/META-INF/dirigible/ide-preview/preview.js
ide/ui/ide-workspace/src/main/resources/META-INF/dirigible/ide-workspace/workspace.js
modules/commons/commons-api/src/main/java/org/eclipse/dirigible/commons/api/helpers/ContentTypeHelper.java

This PR prepares dirigible for xsk editors.

preparation for xsk editors

---

ide/ui/ide-preview/src/main/resources/META-INF/dirigible/ide-preview/preview.js

This PR is related to [#668](https://github.com/SAP/xsk/issues/668) tracked in [#1224](https://github.com/eclipse/dirigible/issues/1224).
Now IDE wouldn't download files on save.

Resolve xs artefacts in preview

---

ide/ui/ide-monaco-extensions/src/main/resources/META-INF/dirigible/ide-monaco-extensions/api/utils/suggestionsParser.js
ide/ui/ide-monaco/src/main/resources/META-INF/dirigible/ide-monaco/js/assignmentsParser.js

Fixes ecma version in acorn.js

Set ecma version to 10

---

ide/ui/ide-monaco/src/main/resources/META-INF/dirigible/ide-monaco/editor.html
ide/ui/ide-monaco/src/main/resources/META-INF/dirigible/ide-monaco/js/editor.js
resources/resources-theme-default/src/main/resources/META-INF/dirigible/theme-default/dropdown.css
resources/resources-theme-default/src/main/resources/META-INF/dirigible/theme-default/monaco.css
resources/resources-theme-fiori/src/main/resources/META-INF/dirigible/theme-fiori/dropdown.css
resources/resources-theme-fiori/src/main/resources/META-INF/dirigible/theme-fiori/monaco.css

Adds a loading overview for monaco, sets automatic code formatting on save.
#1306
#1305

Fixed #1306 #1305

---

ide/ui/ide-security/src/main/resources/META-INF/dirigible/ide-security/editors/access/editor.js
ide/ui/ide-security/src/main/resources/META-INF/dirigible/ide-security/editors/roles/editor.js

Remove $$hashkey when saving file.

---

modules/engines/engine-javascript-graalvm/src/main/java/org/eclipse/dirigible/engine/js/graalvm/processor/generation/ExportGenerator.java
modules/engines/engine-javascript-graalvm/src/main/java/org/eclipse/dirigible/engine/js/graalvm/processor/truffle/DirigibleScopePathHandler.java
modules/engines/engine-javascript-graalvm/src/main/java/org/eclipse/dirigible/engine/js/graalvm/processor/truffle/RegistryTruffleFileSystem.java
modules/engines/engine-javascript-graalvm/src/main/java/org/eclipse/dirigible/engine/js/graalvm/processor/truffle/StandardPathHandler.java
modules/engines/engine-javascript-graalvm/src/test/java/org/eclipse/dirigible/engine/js/graalvm/service/ExportGeneratorTest.java

Fixes https://github.com/eclipse/dirigible/issues/1313

fix: Failing es6 paths on windows resolved

---

ide/ui/ide-database/src/main/resources/META-INF/dirigible/ide-database/sql/editor.html

Fixes wrong key code in ide-database
#1308

Fixed #1308

---

ide/ui/ide-monaco/src/main/resources/META-INF/dirigible/ide-monaco/diff-view.html
ide/ui/ide-monaco/src/main/resources/META-INF/dirigible/ide-monaco/editor.html
ide/ui/ide-monaco/src/main/resources/META-INF/dirigible/ide-monaco/js/editor.js
resources/resources-theme-default/src/main/resources/META-INF/dirigible/theme-default/dropdown.css
resources/resources-theme-default/src/main/resources/META-INF/dirigible/theme-default/monaco.css
resources/resources-theme-fiori/src/main/resources/META-INF/dirigible/theme-fiori/dropdown.css
resources/resources-theme-fiori/src/main/resources/META-INF/dirigible/theme-fiori/monaco.css

Fixes XML formatting, introduces stricter HTML formatting options, improves editor loading overview.
#1320

Fixed #1320

---

api/api-facade/api-tests/src/main/resources/META-INF/dirigible/db/v4/sequence/nextval.js
api/api-javascript/api-core/src/main/resources/META-INF/dirigible/core/extensions/modules.json
api/api-javascript/api-core/src/main/resources/META-INF/dirigible/core/v4/threads.js
api/api-javascript/api-database/src/main/resources/META-INF/dirigible/db/dao.js
api/api-javascript/api-database/src/main/resources/META-INF/dirigible/db/database.js
api/api-javascript/api-database/src/main/resources/META-INF/dirigible/db/modules.js
api/api-javascript/api-database/src/main/resources/META-INF/dirigible/db/orm.js
api/api-javascript/api-database/src/main/resources/META-INF/dirigible/db/ormstatements.js
api/api-javascript/api-database/src/main/resources/META-INF/dirigible/db/procedure.js
api/api-javascript/api-database/src/main/resources/META-INF/dirigible/db/query.js
api/api-javascript/api-database/src/main/resources/META-INF/dirigible/db/sequence.js
api/api-javascript/api-database/src/main/resources/META-INF/dirigible/db/sql.js
api/api-javascript/api-database/src/main/resources/META-INF/dirigible/db/update.js
api/api-javascript/api-database/src/main/resources/META-INF/dirigible/db/v4/dao.js
api/api-javascript/api-database/src/main/resources/META-INF/dirigible/db/v4/database.js
api/api-javascript/api-database/src/main/resources/META-INF/dirigible/db/v4/orm.js
api/api-javascript/api-database/src/main/resources/META-INF/dirigible/db/v4/ormstatements.js
api/api-javascript/api-database/src/main/resources/META-INF/dirigible/db/v4/procedure.js
api/api-javascript/api-database/src/main/resources/META-INF/dirigible/db/v4/query.js
api/api-javascript/api-database/src/main/resources/META-INF/dirigible/db/v4/sequence.js
api/api-javascript/api-database/src/main/resources/META-INF/dirigible/db/v4/sql.js
api/api-javascript/api-database/src/main/resources/META-INF/dirigible/db/v4/update.js

This PR:
Replace `var` with `let`/`const` in api-database.
Fix test for nextval.js

refactor: replace var with let/const

---

resources/resources-theme-default/src/main/resources/META-INF/dirigible/theme-default/migration.css
resources/resources-theme-fiori/src/main/resources/META-INF/dirigible/theme-fiori/migration.css

Adds some styles needed by XSK issue https://github.com/SAP/xsk/issues/738

Related to XSK issue 738

---

resources/resources-theme-default/src/main/resources/META-INF/dirigible/theme-default/migration.css
resources/resources-theme-fiori/src/main/resources/META-INF/dirigible/theme-fiori/migration.css

Adds an additional style for the migration view
https://github.com/SAP/xsk/issues/738

Additional style for migration view

---

modules/odata/odata-core-test/src/test/java/org/eclipse/dirigible/engine/odata2/sql/clause/SQLJoinClauseTest.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/clause/SQLJoinClause.java

[OData] Fix double quotes escaping in OData join clause.

---

.github/workflows/release.yml

- Add sign key for helm chart
https://github.com/eclipse/dirigible/issues/1342
`6.1.0`

sign helm chart with key

---

releng/helm-charts/dirigible/Chart.yaml
releng/helm-charts/dirigible/LICENSE
releng/helm-charts/dirigible/templates/NOTES.txt
releng/helm-charts/dirigible/templates/_helpers.tpl
releng/helm-charts/dirigible/templates/dirigible.yaml
releng/helm-charts/dirigible/templates/keycloak.yaml
releng/helm-charts/dirigible/values.yaml

- Add required function in helm chart
- added kubeVersion field
- #1204
6.1.10

Helm chart changes

---

.github/workflows/release.yml

Update release - fix helm gpg

---

ide/ui/ide-git/src/main/resources/META-INF/dirigible/ide-git/git/git.html
ide/ui/ide-git/src/main/resources/META-INF/dirigible/ide-git/git/git.js
ide/ui/ide-git/src/main/resources/META-INF/dirigible/ide-git/git/staging.html
ide/ui/ide-git/src/main/resources/META-INF/dirigible/ide-git/git/staging.js
resources/resources-theme-default/src/main/resources/META-INF/dirigible/theme-default/ide.css
resources/resources-theme-fiori/src/main/resources/META-INF/dirigible/theme-fiori/ide.css

This pr adds loader indicator to git perspective.

Loader indicator

---

ide/ui/ide-git/src/main/resources/META-INF/dirigible/ide-git/git/git.html

Expand loader indicator area on the toolbar.

expand loader indicator area

---

api/api-facade/api-database/pom.xml
api/api-facade/api-database/src/main/java/org/eclipse/dirigible/api/v3/db/DatabaseFacade.java
modules/database/database-api/src/main/java/org/eclipse/dirigible/database/api/wrappers/WrappedDataSource.java

closes #1375 , closes SAP/xsk#898

Set APPLICATIONUSER when getting DB connection

---

releng/server-all/Dockerfile-base

- Update dirigible-base-platform
#892 
Release: [6.1.3](https://github.com/eclipse/dirigible/releases/tag/v6.1.13)

Update tomcat image 

---

api/api-facade/api-database/src/main/java/org/eclipse/dirigible/api/v3/db/DatabaseFacade.java
modules/database/database-api/src/main/java/org/eclipse/dirigible/database/api/wrappers/WrappedDataSource.java

This reverts the changes done in https://github.com/eclipse/dirigible/pull/1376 as and exception is thrown in some cases, it will be fixed in another PR

Revert setClientInfo in WrappedDataSource - to be fixed

---

api/api-facade/api-http/src/main/java/org/eclipse/dirigible/api/v3/http/HttpClientFacade.java

Fix incorrect Content-Encoding header in outbound request

---

api/api-javascript/api-bpm/src/main/resources/META-INF/dirigible/bpm/extensions/bpm.d.ts
api/api-javascript/api-bpm/src/main/resources/META-INF/dirigible/bpm/extensions/modules.js
api/api-javascript/api-git/src/main/resources/META-INF/dirigible/git/extensions/git.d.ts
ide/ui/ide-monaco-extensions/src/main/resources/META-INF/dirigible/ide-monaco-extensions/api/utils/modulesParser.js

d.ts files for api-git and api-bpm added
Resolves #1415 , #1451 , #1452

Documentation

---

modules/database/database-persistence/pom.xml
modules/security/security-oauth/src/main/java/org/eclipse/dirigible/oauth/filters/AbstractOAuthFilter.java
pom.xml

Fix console view issue in Kyma

---

modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/transformers/DBMetadataUtil.java
modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/transformers/OData2ODataMTransformer.java
modules/engines/engine-odata/src/test/java/org/eclipse/dirigible/engine/odata2/transformers/DBMetadataUtilTest.java

Don't return fake PersistenceTableModel for not existing DB artifact.

---

groups/resources-all/pom.xml
ide/ui/ide-csv/src/main/resources/META-INF/dirigible/ide-csv/js/editor.js
ide/ui/ide-csv/src/main/resources/META-INF/dirigible/ide-csv/services/csv-editor.js
ide/ui/ide-csvim/src/main/resources/META-INF/dirigible/ide-csvim/js/editor.js
ide/ui/ide-csvim/src/main/resources/META-INF/dirigible/ide-csvim/services/csvim-editor.js
ide/ui/ide-data-structures/src/main/resources/META-INF/dirigible/ide-data-structures/editors/table/editor.js
ide/ui/ide-data-structures/src/main/resources/META-INF/dirigible/ide-data-structures/editors/view/editor.js
ide/ui/ide-entity/src/main/resources/META-INF/dirigible/ide-entity/js/controller.js
ide/ui/ide-extensions/src/main/resources/META-INF/dirigible/ide-extensions/editors/extension/editor.js
ide/ui/ide-extensions/src/main/resources/META-INF/dirigible/ide-extensions/editors/extensionpoint/editor.js
ide/ui/ide-form-builder/src/main/resources/META-INF/dirigible/ide-form-builder/designer/designer.js
ide/ui/ide-image/src/main/resources/META-INF/dirigible/ide-image/js/editor.js
ide/ui/ide-jobs/src/main/resources/META-INF/dirigible/ide-jobs/editor/editor.js
ide/ui/ide-listeners/src/main/resources/META-INF/dirigible/ide-listeners/editor/editor.js
ide/ui/ide-monaco/src/main/resources/META-INF/dirigible/ide-monaco/js/editor.js
ide/ui/ide-schema/src/main/resources/META-INF/dirigible/ide-schema/js/controller.js
ide/ui/ide-security/src/main/resources/META-INF/dirigible/ide-security/editors/access/editor.js
ide/ui/ide-security/src/main/resources/META-INF/dirigible/ide-security/editors/roles/editor.js
ide/ui/ide-websockets/src/main/resources/META-INF/dirigible/ide-websockets/editor/editor.js

Adds frame parameter functionality to editors. Fixes default csv editor in the CSVIM editor.
#1563 
#1564

Fixed #1563 #1564

---

modules/engines/engine-javascript-graalvm/src/main/java/org/eclipse/dirigible/engine/js/graalvm/processor/GraalVMJavaScriptContextBuilder.java

Fixes: https://github.com/SAP/xsk/issues/1105

fix: disable interpreter mode warning and bump js version

---

api/api-facade/api-security/src/main/java/org/eclipse/dirigible/api/v3/security/UserFacade.java

closes #1576; closes SAP/xsk#783

Set accept-language to * in UserFacade  when not present in request

---

api/api-facade/api-io/src/main/java/org/eclipse/dirigible/api/v3/io/ZipFacade.java
api/api-facade/api-io/src/main/java/org/eclipse/dirigible/api/v3/io/ZipProcessor.java
api/api-javascript/api-io/src/main/resources/META-INF/dirigible/io/extensions/io.d.ts
api/api-javascript/api-io/src/main/resources/META-INF/dirigible/io/v4/zip.js

- Added option to zipping and unzipping folders/files.
- d.ts updated

zip/unzip files/folders

---

modules/cms/cms-internal/src/main/java/org/eclipse/dirigible/cms/internal/Document.java

The Documents api needs it to check for permissions.

Add getPath method to Document class

---

api/api-javascript/api-bpm/src/main/resources/META-INF/dirigible/bpm/extensions/bpm.d.ts
api/api-javascript/api-core/src/main/resources/META-INF/dirigible/core/extensions/core.d.ts
api/api-javascript/api-http/src/main/resources/META-INF/dirigible/http/extensions/http.d.ts

This PR updates d.ts for http, bpm, core API's

D.ts enhancement

---

modules/odata/odata-core-test/src/test/java/org/eclipse/dirigible/engine/odata2/sql/api/SQLStatementParamTest.java
modules/odata/odata-core-test/src/test/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLUtilsTest.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/api/SQLStatementParam.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLSelectBuilder.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLUtils.java

Fix OData filter issue

---

ide/ui/ide-database/src/main/resources/META-INF/dirigible/ide-database/explorer/explorer.js

Fix SQL query construction for show content and drop table/view

fixes in databases explorer

---

ide/ui/ide-workspace/src/main/resources/META-INF/dirigible/ide-workspace/workspace.js

Allows selecting and deleting multiple files and folders in one step
#1223

fixed issue #1223 for multiple files deletion

---

ide/ui/ide-git/src/main/resources/META-INF/dirigible/ide-git/git/git.js
ide/ui/ide-git/src/main/resources/META-INF/dirigible/ide-git/git/staging.html
ide/ui/ide-git/src/main/resources/META-INF/dirigible/ide-git/git/staging.js

Allows edit of remote fetch and push URLs. 
Fixes Pull all functionality.
#1552 
#1630

Git perspective updates

---

modules/odata/odata-core-test/src/test/java/org/eclipse/dirigible/engine/odata2/sql/ODataSQLProcessorTest.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLQueryBuilder.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/AbstractSQLProcessor.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/ExpandCallBack.java

Fix for #1649 #1650
Change log:
1. fix limit and offset issue in expand
2. fix expand with multiplicity 1

[OData] Fix expand issues

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/records/SelectBuilder.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/builders/view/CreateViewTest.java

Related to https://github.com/SAP/xsk/issues/910
Changelog:
- Changed the way in which join clauses with aliases are constructed inside SelectBuilder
- Created a test for the modification to the SelectBuilder

SelectBuilder now handles aliases properly

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/ISqlDialect.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/table/AbstractTableBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/DefaultSqlDialect.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/hana/HanaSqlDialect.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/builders/table/CreateTableTest.java

Added support for the creation of a fuzzy search index data structure which will increase search speed
[HDBDD] SearchIndex are not processed]
- https://github.com/sap/xsk/issues/908

Added support for the creation of Fuzzy Search Index

---

modules/services/service-transport/src/main/java/org/eclipse/dirigible/runtime/transport/processor/TransportProcessor.java
modules/services/service-transport/src/main/java/org/eclipse/dirigible/runtime/transport/service/TransportProjectRestService.java

Fixes https://github.com/SAP/xsk/issues/1449

Use InputStream for project upload

---

api/api-facade/api-cms/src/main/java/org/eclipse/dirigible/api/v3/cms/CmisFacade.java
ide/ui/ide-documents/src/main/resources/META-INF/dirigible/ide-documents/ui/documents/controllers.js

Fixes https://github.com/eclipse/dirigible/issues/1672 .
Fixes https://github.com/eclipse/dirigible/issues/1671 .

Fix readonly folder access

---

ide/ui/ide-workspace/src/main/resources/META-INF/dirigible/ide-workspace/workspace.html
ide/ui/ide-workspace/src/main/resources/META-INF/dirigible/ide-workspace/workspace.js

Adds import / export functionality anywhere within the working tree. 
Fixes: https://github.com/SAP/xsk/issues/672
Works in combination with https://github.com/eclipse/dirigible/pull/1664

Fix #672 from XSK issues

---

modules/commons/commons-api/src/main/java/org/eclipse/dirigible/commons/api/helpers/ContentTypeHelper.java

add support for hdi artifact

---

modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/transformers/OData2ODataMTransformer.java
modules/engines/engine-odata/src/test/java/org/eclipse/dirigible/engine/odata2/transformers/OData2ODataMTransformerTest.java
modules/engines/engine-odata/src/test/resources/users/Users.odata
modules/odata/odata-api/src/main/java/org/eclipse/dirigible/engine/odata2/definition/ODataAssociationEndDefinition.java
modules/odata/odata-api/src/main/java/org/eclipse/dirigible/engine/odata2/definition/ODataManyToManyMappingTableDefinition.java
modules/odata/odata-core-test/src/test/java/org/eclipse/dirigible/engine/odata2/sql/ODataSQLProcessorManyToManyTest.java
modules/odata/odata-core-test/src/test/java/org/eclipse/dirigible/engine/odata2/sql/ODataSQLProcessorTest.java
modules/odata/odata-core-test/src/test/java/org/eclipse/dirigible/engine/odata2/sql/entities/Group.java
modules/odata/odata-core-test/src/test/java/org/eclipse/dirigible/engine/odata2/sql/entities/User.java
modules/odata/odata-core-test/src/test/java/org/eclipse/dirigible/engine/odata2/sql/entities/UsersToGroup.java
modules/odata/odata-core-test/src/test/resources/META-INF/Group.json
modules/odata/odata-core-test/src/test/resources/META-INF/User.json
modules/odata/odata-core-test/src/test/resources/data/Groups.csv
modules/odata/odata-core-test/src/test/resources/data/Users.csv
modules/odata/odata-core-test/src/test/resources/data/UsersToGroup.csv
modules/odata/odata-core-test/src/test/resources/liquibase/changelog.data.xml
modules/odata/odata-core-test/src/test/resources/liquibase/changelog.schema.xml
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/binding/EdmTableBinding.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/AbstractQueryBuilder.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/clause/SQLJoinClause.java

Related to https://github.com/SAP/xsk/issues/1410
Changelog:
1. Added a mapping table to the ODataAssociationEndDefinition.
2. OData2ODataMTransformer will now create a json with a mapping table property.
3. SQLJoinClause will now check for the existence of a mapping table and construct a join statement with it.
4. Added 2 unit tests for the mapping table in the transformer and SQL builder in the SQLJoinClause.

OData join clause mapping table

---

modules/core/core-publisher/src/main/java/org/eclipse/dirigible/core/publisher/api/IPublisherHandler.java
modules/core/core-publisher/src/main/java/org/eclipse/dirigible/core/publisher/api/handlers/ExtensionsPublisherHandler.java
modules/core/core-publisher/src/main/java/org/eclipse/dirigible/core/publisher/api/handlers/MetadataPublisherHandler.java
modules/core/core-publisher/src/main/java/org/eclipse/dirigible/core/publisher/synchronizer/PublisherSynchronizer.java
modules/engines/engine-javascript-graalvm/src/main/java/org/eclipse/dirigible/engine/js/graalvm/processor/truffle/RegistryTruffleFileSystem.java

- fix graalvm path handling for empty paths
- add target registry location to afterPublish hook

fix: fix graalvm paths and add targetLocation to hooks

---

ide/ui/ide-database/src/main/resources/META-INF/dirigible/ide-database/explorer/explorer.js
ide/ui/ide-documents/src/main/resources/META-INF/dirigible/ide-documents/index.html
ide/ui/ide-workspace/src/main/resources/META-INF/dirigible/ide-workspace/workspace.js
pom.xml

Adds support for new options in extension definitions - nameless, one file of a type per folder, static name (create without editing name)
https://github.com/SAP/xsk/issues/765

Specific file types in WS

---

modules/odata/odata-core/pom.xml
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/api/SQLProcessor.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/DefaultSQLProcessor.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/ResultSetReader.java

Handle odata entity when the value are `HanaClob` and `HanaBlob` objects.

Handle odata hana clob and blob value types

---

releng/sap-cf-base/src/main/java/org/eclipse/dirigible/cf/CloudFoundryModule.java
releng/sap-cf-base/src/main/java/org/eclipse/dirigible/cf/utils/CloudFoundryUtils.java
releng/sap-kyma-base/src/main/java/org/eclipse/dirigible/kyma/KymaModule.java

Fixes: https://github.com/SAP/xsk/issues/1533

Introduce connectivity configuration

---

ide/ui/ide-csv/src/main/resources/META-INF/dirigible/ide-csv/editor.html
ide/ui/ide-csv/src/main/resources/META-INF/dirigible/ide-csv/js/editor.js

Adds data rows info in CSV editor and support for "~" delimited CSV files. 
https://github.com/eclipse/dirigible/issues/1488 (duplicated in https://github.com/SAP/xsk/issues/1117)
https://github.com/SAP/xsk/issues/1111

Fix #1488 incl. XSK fix #1111

---

modules/odata/odata-core-test/src/test/java/org/eclipse/dirigible/engine/odata2/sql/ODataSQLProcessorViewTest.java
modules/odata/odata-core-test/src/test/java/org/eclipse/dirigible/engine/odata2/sql/entities/View.java
modules/odata/odata-core-test/src/test/resources/META-INF/View.json
modules/odata/odata-core-test/src/test/resources/data/View.csv
modules/odata/odata-core-test/src/test/resources/liquibase/changelog.data.xml
modules/odata/odata-core-test/src/test/resources/liquibase/changelog.schema.xml
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/clause/SQLSelectClause.java

Changelog:
1. Return the deleted if statement inside SQLSelectClause that adds row_number to the select when using a generated key.
2. Added a test to verify the SQL

Fix the generated key regression

---

modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/AbstractSQLProcessor.java

Resolves https://github.com/SAP/xsk/issues/1679

Added root message cause for odata handler exceptions

---

ide/ui/ide-core/src/main/resources/META-INF/dirigible/ide-core/ui/layout.js
ide/ui/ide-preview/src/main/resources/META-INF/dirigible/ide-preview/js/preview.js
ide/ui/ide-projects/src/main/resources/META-INF/dirigible/ide-projects/js/projects.js
ide/ui/ide-properties/src/main/resources/META-INF/dirigible/ide-properties/properties.html
ide/ui/ide-publisher-service/src/main/resources/META-INF/dirigible/ide-publisher-service/publisher.js
ide/ui/ide-workspace-service/src/main/resources/META-INF/dirigible/ide-workspace-service/workspace.js

Fixes various bugs in the new layout, projects, preview and properties views.
#1841 
#1840 
#1839 
#1838 
#1837 
#1836

Various fixes for new the layout 

---

api/api-facade/api-git/src/main/java/org/eclipse/dirigible/api/v4/git/GitFacade.java
api/api-facade/api-git/src/test/java/org/eclipse/dirigible/api/v4/git/test/GitFacadeTest.java

Currently, when a Git repository init is made, we do not check if the project being initialized has a `project.json` file. If it doesn't have one, it would not be opened properly in the Web IDE. 
This PR ensures we have a `project.json` (and creates it if it doesn't exist) when a call to `GitFacade::initRepository` is made

fix: ensure project.json is generated on git repo init

---

groups/resources-all/pom.xml
ide/ui/ide-core/src/main/resources/META-INF/dirigible/ide-core/core/ide-message-hub.js
ide/ui/ide-core/src/main/resources/META-INF/dirigible/ide-core/services/loader.js
ide/ui/ide-core/src/main/resources/META-INF/dirigible/ide-core/ui/core-modules.js
ide/ui/ide-core/src/main/resources/META-INF/dirigible/ide-core/ui/layout.js
ide/ui/ide-core/src/main/resources/META-INF/dirigible/ide-core/ui/templates/accordionPane.html
ide/ui/ide-core/src/main/resources/META-INF/dirigible/ide-core/ui/templates/ideDialogs.html
ide/ui/ide-core/src/main/resources/META-INF/dirigible/ide-core/ui/widgets.js
ide/ui/ide-image/src/main/resources/META-INF/dirigible/ide-image/editor.html
ide/ui/ide-monaco/src/main/resources/META-INF/dirigible/ide-monaco/editor.html
ide/ui/ide-operations/src/main/resources/META-INF/dirigible/ide-operations/index.html
ide/ui/ide-projects/src/main/resources/META-INF/dirigible/ide-projects/js/projects.js
ide/ui/ide-projects/src/main/resources/META-INF/dirigible/ide-projects/projects.html
ide/ui/ide-search/src/main/resources/META-INF/dirigible/ide-search/js/search.js
ide/ui/ide-search/src/main/resources/META-INF/dirigible/ide-search/services/search-view.js
ide/ui/ide-welcome/src/main/resources/META-INF/dirigible/ide-welcome/js/welcome.js
ide/ui/ide-welcome/src/main/resources/META-INF/dirigible/ide-welcome/services/welcome-view.js
ide/ui/ide-workbench/src/main/resources/META-INF/dirigible/ide/index.html
resources/resources-theme-quartz-dark/src/main/resources/META-INF/dirigible/theme-quartz-dark/extensions/theme.js
resources/resources-theme-quartz-light/src/main/resources/META-INF/dirigible/theme-quartz-light/extensions/theme.js

Fixes some issues with dialog priority and overlay, adds a new dialog, adds new dg css styles and fixes, updates sap-theming and fundamental-styles webjars, adds named scripts in loader.js for perspectives and fixes other small issues.
#1892 
#1867 
#1845

Fixed #1892 #1867 #1845

---

modules/core/core-workspace/src/main/java/org/eclipse/dirigible/core/workspace/json/WorkspaceJsonHelper.java

Fixes: https://github.com/eclipse/dirigible/issues/1916

fix: remove project name when collecting git project statuses

---

releng/helm-charts/dirigible/Chart.yaml

Fix Helm chart incompatible kubernetes version
https://github.com/eclipse/dirigible/issues/1975
Fix: https://github.com/eclipse/dirigible/issues/1975

Fix Helm chart incompatible kubernetes version

---

releng/helm-charts/dirigible/templates/_helpers.tpl
releng/helm-charts/dirigible/templates/dirigible.yaml
releng/helm-charts/dirigible/templates/keycloak.yaml
releng/helm-charts/dirigible/values.yaml

Add properties for GKE deployment.
https://github.com/eclipse/dirigible/issues/1989
[v6.3.15](https://github.com/eclipse/dirigible/releases/tag/v6.3.15)
Fix: #1989

Update helm chart to support GKE

---

releng/Dockerfile-tomcat
releng/anonymous-all/Dockerfile-base
releng/anonymous-runtime/Dockerfile-base
releng/openshift-all/Dockerfile-base
releng/sap-cf-all/Dockerfile-base
releng/sap-cf-runtime/Dockerfile-base
releng/sap-kyma-all/Dockerfile-base
releng/sap-kyma-runtime/Dockerfile-base
releng/server-all/Dockerfile-base
releng/server-minimal/Dockerfile-base
releng/server-oauth/Dockerfile-base
releng/server-runtime-keycloak/Dockerfile-base
releng/server-runtime/Dockerfile-base
releng/trial-all/Dockerfile-base

Update PostgreSQL library in all docker images
https://github.com/eclipse/dirigible/issues/1985

Upgrade PostgreSQL library in all docker images

---

releng/helm-charts/dirigible/templates/dirigible.yaml
releng/helm-charts/dirigible/values.yaml

Set username and password in Helm chart
```
helm install dirigible dirigible/dirigible \
--set dirigible.username=<your-username> \
--set dirigible.password=<your-password>
```
https://github.com/eclipse/dirigible/issues/564
[v6.3.16](https://github.com/eclipse/dirigible/releases/tag/v6.3.16)
Fix: #564

Set username and password in Helm chart

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/ISqlKeywords.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/hana/HanaCreateBranchingBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/hana/HanaCreateTableBuilder.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/dialects/hana/HanaCreateTableBuilderTest.java

Two new supported types are added for the entitys Catalog.tableType - Global Temporary and Global Temporary Column

Added support for Global Temporary and Global Temporary Column tables

---

ext/ext-api/api-cassandra/pom.xml
ext/ext-api/api-elasticsearch/pom.xml
ext/ext-api/api-etcd/pom.xml
ext/ext-api/api-kafka/pom.xml
ext/ext-api/api-mongodb/pom.xml
ext/ext-api/api-qldb/pom.xml
ext/ext-api/api-qldb/src/main/java/org/eclipse/dirigible/api/qldb/QLDBRepository.java
ext/ext-api/api-qldb/src/main/resources/META-INF/dirigible/qldb/QLDBRepository.js
ext/ext-api/api-qldb/src/main/resources/META-INF/dirigible/qldb/QLDBRepository.mjs
ext/ext-api/api-qldb/src/main/resources/META-INF/dirigible/qldb/extensions/modules.js
ext/ext-api/api-qldb/src/main/resources/META-INF/dirigible/qldb/extensions/qldb.d.ts
ext/ext-api/api-rabbitmq/pom.xml
ext/ext-api/api-redis/pom.xml
ext/ext-api/api-spark/pom.xml
pom.xml

resolves comments from the initial PR and removes unused configurations in ext-api modules

chore: QLDBRepository API updates

---

api/api-javascript/api-core/src/main/resources/META-INF/dirigible/core/v4/destinations.js

Adds Find Destination API:
- #2114

#2114 [API] Destinations - Cloud Integration - Adds Find Destination

---

api/api-javascript/api-http/src/main/resources/META-INF/dirigible/http/v4/rs.js

Add support for `rs` paths like:
`/path/{someParam*}` 
to match:
`/path/test1/test2/test3`

feat: request params match many

---

templates/template-application-rest/src/main/resources/META-INF/dirigible/template-application-rest/api/entity.js.template
templates/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/detail/dialog-window/controller.js.template

Fixes #2103 [Templates] DAO Count Details Error on PostgreSQL

---

ext/ext-modules/ext-destinations-proxy/.gitignore
ext/ext-modules/ext-destinations-proxy/pom.xml
ext/ext-modules/ext-destinations-proxy/src/main/resources/META-INF/dirigible/proxy/destinations.js
ext/ext-modules/pom.xml
releng/sap-cf-base/pom.xml
releng/sap-kyma-base/pom.xml

Fixes #2124 SAP BTP - Destination Proxy

---

components/core-extensions/src/main/java/org/eclipse/dirigible/components/extensions/synchronizer/ExtensionPointsSynchronizer.java
components/core-extensions/src/main/java/org/eclipse/dirigible/components/extensions/synchronizer/ExtensionsSynchronizer.java
components/core-initializers/src/main/java/org/eclipse/dirigible/components/initializers/definition/Definition.java

JavaDoc fixes

---

api/api-javascript/api-http/pom.xml
api/api-javascript/api-http/src/main/resources/META-INF/dirigible/http/v4/rs.js
modules/engines/engine-graalium/execution-core/src/main/java/org/eclipse/dirigible/graalium/core/modules/DirigibleSourceProvider.java
modules/engines/engine-graalium/execution-core/src/main/resources/polyfills/require.js
pom.xml

Fixes: 
- https://github.com/eclipse/dirigible/issues/2127
- https://github.com/eclipse/dirigible/issues/2128
- https://github.com/eclipse/dirigible/issues/2129
- https://github.com/eclipse/dirigible/issues/2130
- https://github.com/eclipse/dirigible/issues/2131
- https://github.com/eclipse/dirigible/issues/2132

feat: add path-to-regexp as rs routes matcher

---

ext/ext-modules/ext-destinations-proxy/src/main/resources/META-INF/dirigible/proxy/destinations.js

Adds environment variable to enable proxy.
- #2124

#2124 Adds environment variable to enable proxy

---

components/core-jobs/src/main/java/org/eclipse/dirigible/components/jobs/domain/Job.java
components/core-jobs/src/main/java/org/eclipse/dirigible/components/jobs/endpoint/JobEndpoint.java
components/core-jobs/src/test/java/org/eclipse/dirigible/components/jobs/endpoint/JobEndpointTest.java
components/core-jobs/src/test/java/org/eclipse/dirigible/components/jobs/repository/JobEmailRepositoryTest.java
components/core-jobs/src/test/java/org/eclipse/dirigible/components/jobs/repository/JobLogRepositoryTest.java
components/core-jobs/src/test/java/org/eclipse/dirigible/components/jobs/repository/JobRepositoryTest.java
components/core-jobs/src/test/java/org/eclipse/dirigible/components/jobs/synchronizer/JobSynchronizerTest.java
components/core-jobs/src/test/resources/META-INF/dirigible/test/control.job
components/core-jobs/src/test/resources/META-INF/dirigible/test/handler.js

Spring jobs

---

resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/core-modules.js
resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/templates/ideDialogs.html
resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/widgets.js

Signed-off-by: StanZGenchev <stan.z.genchev@gmail.com>
Adds a few improvements/fixes like automatic input focusing for form dialog inputs, removes unnecessary scroll inside dialogs and adds some clean-up events for the widget library.
#2234

Fixed #2234

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/nightly.yml
.github/workflows/pre-release.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml

Clear Github actions warnings.
https://github.com/eclipse/dirigible/issues/2247
[6.3.28](https://github.com/eclipse/dirigible/releases/tag/v6.3.28)
Fix: https://github.com/eclipse/dirigible/issues/2247

GitHub Action Warnings

---

.github/workflows/build.yml

Fix build workflow warning checkout.

Fix build checkout version

---

ide/ui/ide-databases/src/main/resources/META-INF/dirigible/ide-databases/transfer.html
ide/ui/ide-documents/src/main/resources/META-INF/dirigible/ide-documents/ui/documents/js/controllers.js
resources/resources-resources/src/main/resources/META-INF/dirigible/resources/styles/widgets.css

Signed-off-by: StanZGenchev <stan.z.genchev@gmail.com>
Fixes issues with Safari under macOS.
#2269

Fixed #2269

---

ide/ui/ide-data-structures/src/main/resources/META-INF/dirigible/ide-data-structures/editors/table/editor.html
ide/ui/ide-data-structures/src/main/resources/META-INF/dirigible/ide-data-structures/editors/table/editor.js
ide/ui/ide-data-structures/src/main/resources/META-INF/dirigible/ide-data-structures/editors/view/editor.html
ide/ui/ide-data-structures/src/main/resources/META-INF/dirigible/ide-data-structures/editors/view/editor.js
ide/ui/ide-extensions/src/main/resources/META-INF/dirigible/ide-extensions/editors/extension/editor.html
ide/ui/ide-extensions/src/main/resources/META-INF/dirigible/ide-extensions/editors/extension/editor.js
ide/ui/ide-extensions/src/main/resources/META-INF/dirigible/ide-extensions/editors/extensionpoint/editor.html
ide/ui/ide-extensions/src/main/resources/META-INF/dirigible/ide-extensions/editors/extensionpoint/editor.js
ide/ui/ide-jobs/src/main/resources/META-INF/dirigible/ide-jobs/editor/editor.html
ide/ui/ide-jobs/src/main/resources/META-INF/dirigible/ide-jobs/editor/editor.js
ide/ui/ide-listeners/src/main/resources/META-INF/dirigible/ide-listeners/editor/editor.html
ide/ui/ide-listeners/src/main/resources/META-INF/dirigible/ide-listeners/editor/editor.js
ide/ui/ide-security/src/main/resources/META-INF/dirigible/ide-security/editors/access/editor.html
ide/ui/ide-security/src/main/resources/META-INF/dirigible/ide-security/editors/access/editor.js
ide/ui/ide-security/src/main/resources/META-INF/dirigible/ide-security/editors/roles/editor.html
ide/ui/ide-security/src/main/resources/META-INF/dirigible/ide-security/editors/roles/editor.js
ide/ui/ide-websockets/src/main/resources/META-INF/dirigible/ide-websockets/editor/editor.html
ide/ui/ide-websockets/src/main/resources/META-INF/dirigible/ide-websockets/editor/editor.js
resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/widgets.js

Signed-off-by: StanZGenchev <stan.z.genchev@gmail.com>
Adds a shortcut directive and enables 'Ctrl+S'/'Cmd+S' in all editors.
#2315

Fixed #2315

---

modules/bpm/pom.xml
modules/cms/pom.xml
modules/commons/pom.xml
modules/core/pom.xml
modules/database/pom.xml
modules/engines/pom.xml
modules/git/pom.xml
modules/mail/pom.xml
modules/migrations/pom.xml
modules/odata/pom.xml
modules/repository/pom.xml
modules/security/pom.xml
modules/services/pom.xml
modules/services/service-security/src/main/java/org/eclipse/dirigible/runtime/security/filter/SecurityFilter.java
modules/spring/pom.xml
modules/templating/pom.xml
modules/workspace/pom.xml

Fixes `<relativePath>` for **pom.xml** files of the `modules` group.

[Core] Fix <relativePath> for pom.xml files of the modules group

---

components/ide-ui-monaco/src/main/resources/META-INF/dirigible/ide-monaco/js/editor.js
modules/engines/engine-graalium/execution/src/main/java/org/eclipse/dirigible/graalium/core/graal/GraalJSContextCreator.java
modules/engines/engine-graalium/execution/src/main/java/org/eclipse/dirigible/graalium/core/graal/GraalJSFileSystem.java

Fixes:
- https://github.com/eclipse/dirigible/issues/2421
- https://github.com/eclipse/dirigible/issues/2420

feat: add support for json modules and import assertions

---

modules/engines/engine-graalium/execution/src/main/java/org/eclipse/dirigible/graalium/core/graal/GraalJSContextCreator.java

Fixes: https://github.com/eclipse/dirigible/issues/2423

feat: add support for js operator overloading

---

components/security-keycloak/src/main/java/org/eclipse/dirigible/components/security/keycloak/KeycloakSecurityConfiguration.java

Allow access `favicon.ico`
`favicon.ico` access

Fix favicon access

---

.github/workflows/nightly.yml

Nightly build skip windows

---

build/application/src/main/resources/application.properties
components/ide-terminal/src/main/java/org/eclipse/dirigible/components/terminal/endpoint/TerminalWebsocketConfig.java

Add terminal property - default `false`.
Add option for terminal.

Terminal config

---

components/api-bpm/src/main/resources/META-INF/dirigible/bpm/extensions/bpm.d.ts
components/api-git/src/main/resources/META-INF/dirigible/git/extensions/git.d.ts
components/api-http/src/main/resources/META-INF/dirigible/http/client-async.js
components/api-http/src/main/resources/META-INF/dirigible/http/extensions/http.d.ts
components/api-io/src/main/resources/META-INF/dirigible/io/zip.js
components/api-job/src/main/resources/META-INF/dirigible/job/extensions/job.d.ts
components/api-log/src/main/resources/META-INF/dirigible/log/extensions/log.d.ts
components/api-mail/src/main/resources/META-INF/dirigible/mail/extensions/mail.d.ts
components/api-mongodb/src/main/resources/META-INF/dirigible/mongodb/extensions/mongodb.d.ts
components/api-net/src/main/resources/META-INF/dirigible/net/extensions/net.d.ts
components/api-platform/src/main/resources/META-INF/dirigible/platform/extensions/modules.js
components/api-platform/src/main/resources/META-INF/dirigible/platform/extensions/modules.json
components/api-platform/src/main/resources/META-INF/dirigible/platform/extensions/platform.d.ts
components/api-template/src/main/resources/META-INF/dirigible/template/extensions/modules.js
components/api-template/src/main/resources/META-INF/dirigible/template/extensions/modules.json
components/api-utils/src/main/resources/META-INF/dirigible/utils/base64.js
components/api-utils/src/main/resources/META-INF/dirigible/utils/extensions/utils.d.ts

Fixes to majority of the internal APIs:
- wrong d.ts types
- missing methods
- formatting issues
- typos

Fixes to internal APIs

---

components/api-io/src/main/resources/META-INF/dirigible/io/extensions/io.d.ts

Added documentation for io/image as it was missing

Update api io docs

---

components/api-platform/src/main/resources/META-INF/dirigible/platform/extensions/platform.d.ts
components/api-platform/src/main/resources/META-INF/dirigible/platform/problems.js

- Added missing documentation for problems API
https://www.dirigible.io/api/platform/problems/

Missing problems documentation

---

components/api-rabbitmq/pom.xml
components/api-rabbitmq/src/main/java/org/eclipse/dirigible/components/api/rabbitmq/RabbitMQFacade.java
components/api-rabbitmq/src/main/java/org/eclipse/dirigible/components/api/rabbitmq/RabbitMQReceiverRunner.java
components/api-rabbitmq/src/main/resources/META-INF/dirigible/rabbitmq/consumer.js
components/api-rabbitmq/src/main/resources/META-INF/dirigible/rabbitmq/extensions/modules.js
components/api-rabbitmq/src/main/resources/META-INF/dirigible/rabbitmq/extensions/modules.json
components/api-rabbitmq/src/main/resources/META-INF/dirigible/rabbitmq/extensions/rabbitmq.d.ts
components/api-rabbitmq/src/main/resources/META-INF/dirigible/rabbitmq/extensions/rabbitmq.extension
components/api-rabbitmq/src/main/resources/META-INF/dirigible/rabbitmq/modules.js
components/api-rabbitmq/src/main/resources/META-INF/dirigible/rabbitmq/producer.js
components/api-rabbitmq/src/main/resources/META-INF/dirigible/rabbitmq/project.json
components/api-rabbitmq/src/test/java/org/eclipse/dirigible/components/api/rabbitmq/RabbitMQFacadeTest.java
components/core-initializers/src/main/java/org/eclipse/dirigible/components/initializers/classpath/ClasspathExpander.java
components/engine-web/src/test/java/org/eclipse/dirigible/components/engine/web/synchronizer/ExposesSynchronizerTest.java
components/group-api/pom.xml
components/pom.xml
modules/odata/odata-core/pom.xml

Adds RabbitMQ API as a spring component
https://www.dirigible.io/api/rabbitmq/consumer/
https://www.dirigible.io/api/rabbitmq/producer/

RabbitMQ API component

---

components/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/view.js
components/template-html/src/main/resources/META-INF/dirigible/template-html/index.html.template

Migrates the old "HTML5 (AngularJS)" template to the new view system and fixes an issue with CORS.
Adds a new `$http` boolean config called `disableInterceptors` which disables all built-in interceptors for a specific request.
#2480 
Loading state:
Error state:
Page:

Fixed #2480, new HTML5 (AngularJS) template

---

components/api-etcd/src/test/java/org/eclipse/dirigible/componenets/api/etcd/EtcdFacadeTest.java
components/api-rabbitmq/src/test/java/org/eclipse/dirigible/components/api/rabbitmq/RabbitMQFacadeTest.java
components/api-redis/src/test/java/org/eclipse/dirigible/components/api/redis/RedisFacadeTest.java

Removes old junit4 asserts with junit5 in components

Change old assert with junit5

---

components/api-qldb/pom.xml
components/api-qldb/src/main/java/org/eclipse/dirigible/components/api/qldb/QLDBRepository.java
components/api-qldb/src/main/java/org/eclipse/dirigible/components/api/qldb/QLDBRepositoryException.java
components/api-qldb/src/main/resources/META-INF/dirigible/qldb/QLDBRepository.js
components/api-qldb/src/main/resources/META-INF/dirigible/qldb/QLDBRepository.mjs
components/api-qldb/src/main/resources/META-INF/dirigible/qldb/extensions/modules.js
components/api-qldb/src/main/resources/META-INF/dirigible/qldb/extensions/modules.json
components/api-qldb/src/main/resources/META-INF/dirigible/qldb/extensions/qldb.d.ts
components/api-qldb/src/main/resources/META-INF/dirigible/qldb/extensions/qldb.extension
components/group-api/pom.xml
components/pom.xml

Adds QLDB API Component
https://www.dirigible.io/api/qldb/qldb/

QLDB API Component

---

components/api-utils/src/main/resources/META-INF/dirigible/utils/extensions/utils.d.ts

Add documentation for JSONPath for ECMA6
https://www.dirigible.io/api/utils/jsonpath/

Add documentation for JSONPath in utils.d.ts

---

components/ide-ui-projects/src/main/resources/META-INF/dirigible/ide-projects/js/projects.js

Configures the 'F2/Rename', 'Enter/Double click' and Delete keyboard shortcuts in the Projects view.
Adds new "Ctrl+C" (Copy), "Ctrl+X" (Cut) and "Ctrl+V" (Paste) shortcuts.
Fixes #2151

Fixes keyboard shortcut behaviour in projects view

---

components/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/theming.js
components/resources-resources/src/main/resources/META-INF/dirigible/resources/styles/core.css

Fixes the "white flash" that appears in dark mode.
#2552

Fixed white flashing in views

---

components/ide-ui-preview/src/main/resources/META-INF/dirigible/ide-preview/js/preview.js
components/ide-ui-preview/src/main/resources/META-INF/dirigible/ide-preview/preview.html

Adds the ability to set custom ViewParameters in the preview.
Preview now remembers if the user has locked the automatic load/reload feature.
Adds hints to the icon buttons.
#2557

Custom ViewParameters in preview

---

components/ide-ui-monaco/src/main/resources/META-INF/dirigible/ide-monaco/js/editor.js

Fixes close actions from the main editor
#2559

Fix close actions from the main editor

---

components/ide-ui-monaco/src/main/resources/META-INF/dirigible/ide-monaco/editor.html
components/ide-ui-monaco/src/main/resources/META-INF/dirigible/ide-monaco/js/editor.js
components/ide-ui-monaco/src/main/resources/META-INF/dirigible/ide-monaco/js/workers/computeDiff.js

Fixes a performance issue with main code editor.
#2615

Fixed performance issue with main code editor

---

components/data-export/pom.xml
components/data-export/src/main/java/org/eclipse/dirigible/components/data/export/endpoint/DataExportEndpoint.java
components/data-export/src/main/java/org/eclipse/dirigible/components/data/export/service/DataExportService.java
components/data-management/src/main/java/org/eclipse/dirigible/components/data/management/endpoint/DatabaseExportEndpoint.java
components/data-management/src/main/java/org/eclipse/dirigible/components/data/management/service/DatabaseExportService.java
components/group-database/pom.xml
components/ide-ui-database/src/main/resources/META-INF/dirigible/ide-database/explorer/explorer.js
components/ide-ui-result/src/main/resources/META-INF/dirigible/ide-result/result.js
components/ide-workspace/src/main/java/org/eclipse/dirigible/components/ide/workspace/domain/File.java
components/pom.xml

Adds the functionality in `Database` perspetive to export schema's data in project with its corresponding `csv` files and `csvim`
fixes #2614

[GH-#2614] Export data as project

---

components/data-export/pom.xml
components/data-export/src/main/java/org/eclipse/dirigible/components/data/export/endpoint/DataExportEndpoint.java
components/data-export/src/test/java/org/eclipse/dirigible/components/data/export/endpoint/DataExportEndpointTest.java
components/data-export/src/test/java/org/eclipse/dirigible/components/data/export/service/DataExportServiceTest.java

Adds tests for export project endpoints and service
fixes #2618

[GH-#2618] Add tests for export project endpoints

---

components/data-export/src/main/java/org/eclipse/dirigible/components/data/export/service/DataExportService.java
components/data-management/src/main/java/org/eclipse/dirigible/components/data/management/service/DatabaseExecutionService.java
components/data-management/src/main/java/org/eclipse/dirigible/components/data/management/service/DatabaseExportService.java

Set the limit of records to be export for `Export data in project` to unlimited
Some cleanup of the code because of duplication
fixes #2623

Fixes #2623 Set the limit of export csv

---

components/api-http/src/main/resources/META-INF/dirigible/http/rs/decorators.js
components/core-base/src/main/java/org/eclipse/dirigible/components/base/initializer/Initializer.java
components/data-csvim/src/main/java/org/eclipse/dirigible/components/data/csvim/synchronizer/CsvimProcessor.java
components/engine-typescript/src/main/java/org/eclipse/dirigible/components/engine/typescript/TypeScriptEndpoint.java
components/engine-typescript/src/main/java/org/eclipse/dirigible/components/engine/typescript/TypeScriptException.java
components/engine-typescript/src/main/java/org/eclipse/dirigible/components/engine/typescript/TypeScriptPublisherHandler.java
components/engine-typescript/src/main/java/org/eclipse/dirigible/components/engine/typescript/TypeScriptRegistryInitializer.java
components/engine-typescript/src/main/java/org/eclipse/dirigible/components/engine/typescript/TypeScriptService.java
components/ide-workspace/src/main/java/org/eclipse/dirigible/components/ide/workspace/domain/TypeScriptFile.java

Adds error handling for csvim if no tablematadata or csv parser is present
fixes #2509

Fixes #2509 Csvim error if no tablemetadata or csv parser

---

modules/commons/commons-helpers/src/main/java/org/eclipse/dirigible/commons/api/helpers/ContentTypeHelper.java

add .wasm content-type

---

components/api-database/src/main/java/org/eclipse/dirigible/components/api/db/DataStoreFacade.java
components/api-database/src/main/resources/META-INF/dirigible/db/database.js
components/api-database/src/main/resources/META-INF/dirigible/db/extensions/db.d.ts
components/api-database/src/main/resources/META-INF/dirigible/db/store.js

Adds missing setBinaryStream function in DB API and updated the [documentation](https://www.dirigible.io/api/database/database/#preparedstatement).
fixes #2661

[GH-#2661] Added missing setBinaryStream function

---

components/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/editor.js
components/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/modeler.html
components/ide-ui-generate-service/src/main/resources/META-INF/dirigible/ide-generate-service/generate.mjs
components/ide-ui-projects/src/main/resources/META-INF/dirigible/ide-projects/js/projects.js
components/ide-ui-workspace-service/src/main/resources/META-INF/dirigible/ide-workspace-service/workspace.js
components/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/templates/ideHeader.html

Adds the ability to regenerate a model from the `.gen` file, both from the editor and from the project tree.
#2070

[EDM] Re-generate *.model via *.gen file

---

components/data-csvim/src/main/java/org/eclipse/dirigible/components/data/csvim/synchronizer/CsvProcessor.java
components/data-csvim/src/main/java/org/eclipse/dirigible/components/data/csvim/synchronizer/CsvimProcessor.java
components/data-csvim/src/main/java/org/eclipse/dirigible/components/data/csvim/utils/CsvimUtils.java
components/data-export/src/main/java/org/eclipse/dirigible/components/data/export/endpoint/DataExportEndpoint.java
components/data-import/pom.xml
components/data-import/src/main/java/org/eclipse/dirigible/components/data/export/endpoint/DataImportEndpoint.java
components/data-import/src/main/java/org/eclipse/dirigible/components/data/export/service/DataImportService.java
components/group-database/pom.xml
components/ide-ui-database/src/main/resources/META-INF/dirigible/ide-database/explorer/explorer.js
components/ide-ui-import/src/main/resources/META-INF/dirigible/ide-import/js/import.js
components/ide-ui-result/src/main/resources/META-INF/dirigible/ide-result/result.js
components/pom.xml

Data Import from CSV

---

components/ide-ui-git-service/src/main/resources/META-INF/dirigible/ide-git-service/git.js

Adds an API call for getting the original and modified file contnet in the git service
#2715

Adds an API call for getting the original and modified file contnet in the git service

---

components/engine-camel/src/main/java/org/eclipse/dirigible/components/engine/camel/processor/CamelProcessor.java

When dirigible's camel synchronizer notices changes it triggers a reload of the camel routes from the *.camel yaml files or when it detects a file was deleted it triggers a removal of all routes.
Due to this https://github.com/apache/camel-spring-boot/blob/630b06dde0102ec4b8274258b932a12161088251/components-starter/camel-platform-http-starter/src/main/java/org/apache/camel/component/platform/http/springboot/CamelRequestHandlerMapping.java#L85
being a noop operation, the camel springboot platformHttp component does not remove any registered http mappings.
The current workaround is to remove all registered mappings from the platformHttpEngineRequestMapping.

Fix: camel platformhttp clear all mappings

---

components/ide-ui-projects/src/main/resources/META-INF/dirigible/ide-projects/js/projects.js
components/ide-ui-publisher-service/src/main/resources/META-INF/dirigible/ide-publisher-service/publisher.js

Adds a statusbar indicator that a file/folder or project is being published.
#2828

#2828 - Update Status Bar on Publish Single Project

---

components/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/http/upload.ts

Adopt Spring **StandardMultipartFile** for the `http/upload` API
- https://github.com/spring-projects/spring-framework/blob/4977ef9cea8c34337dd9cc87055d1efd56dea8a3/spring-web/src/main/java/org/springframework/web/multipart/support/StandardMultipartHttpServletRequest.java#L206-L270

[API] Upload is not working

---

components/ide-ui-csv/src/main/resources/META-INF/dirigible/ide-csv/js/editor.js
components/ide-ui-file-manager/src/main/resources/META-INF/dirigible/ide-file-manager/js/file-manager.js
components/ide-ui-git-projects/src/main/resources/META-INF/dirigible/ide-git-projects/js/git-projects.js
components/ide-ui-projects/src/main/resources/META-INF/dirigible/ide-projects/js/projects.js
components/ide-ui-registry/src/main/resources/META-INF/dirigible/ide-registry/js/registry.js
components/ide-ui-repository/src/main/resources/META-INF/dirigible/ide-repository/js/repository.js
components/ide-ui-search/src/main/resources/META-INF/dirigible/ide-search/js/search.js
components/ide-ui-workbench/src/main/resources/META-INF/dirigible/ide/index.html
components/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/core-modules.js
components/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/layout.js
components/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/templates/contextmenu.html
components/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/templates/contextmenuSubmenu.html
components/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/templates/layout.html
components/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/templates/splittedTabs.html
components/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/view.js

Adds a context menu to the Workbench perspective. When you right-click on an editor tab, you will now get the following options:
1. Close
2. Close Others
3. Close All
4. Reveal in Projects View
#2886

[IDE] #2886 - Highlight file in the project tree from the editor tab

---

components/ide-ui-projects/src/main/resources/META-INF/dirigible/ide-projects/js/projects.js

Delete and Unpublish does not work

Fixed: #2875 - Delete and Unpublish does not work

---

components/ide-ui-result/src/main/resources/META-INF/dirigible/ide-result/js/result.js
components/ide-ui-result/src/main/resources/META-INF/dirigible/ide-result/result.html

Adds error handling in the result view.
#2878

[Database] #2878 - Handling of incorrect queries

---

components/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/templates/ideDialogs.html

Fixes the form dialog window.
#2880

[EDM] #2880 - OData checkbox is not visible

---

components/core-initializers/src/main/java/org/eclipse/dirigible/components/initializers/synchronizer/SynchronizationWatcher.java

remove unnecessary watchers + fix win issues on startup

---

components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/manage/dialog-window/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/detail/dialog-window/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/main-details/index.html.template

[Templates] Make 'Calculated' Properties Read-Only in the UI

---

components/data/data-anonymize/src/main/java/org/eclipse/dirigible/components/data/anonymize/service/DataAnonymizeService.java
components/data/data-csvim/src/main/java/org/eclipse/dirigible/components/data/csvim/synchronizer/CsvimProcessor.java
components/data/data-export/src/main/java/org/eclipse/dirigible/components/data/export/service/DatabaseExportService.java
components/data/data-management/src/main/java/org/eclipse/dirigible/components/data/management/format/ResultSetCsvWriter.java
components/data/data-management/src/main/java/org/eclipse/dirigible/components/data/management/service/DatabaseExecutionService.java
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/service/BpmService.java
components/engine/engine-ftp/src/test/java/org/eclipse/dirigible/components/engine/ftp/repository/FtpRepositoryTest.java
components/engine/engine-jobs/src/main/java/org/eclipse/dirigible/components/jobs/service/JobLogService.java
components/engine/engine-jobs/src/main/java/org/eclipse/dirigible/components/jobs/service/JobService.java
components/engine/engine-odata/src/main/java/org/eclipse/dirigible/components/odata/transformers/ODataDatabaseMetadataUtil.java
components/engine/engine-odata/src/test/java/org/eclipse/dirigible/components/odata/transformers/OData2ODataMTransformerTest.java
components/engine/engine-odata/src/test/java/org/eclipse/dirigible/components/odata/transformers/OData2ODataTransformerTestUtil.java
components/engine/engine-odata/src/test/java/org/eclipse/dirigible/components/odata/transformers/OData2ODataXTransformerTest.java
components/ide/ide-template/src/main/java/org/eclipse/dirigible/components/ide/template/endpoint/GenerationEndpoint.java
components/ide/ide-workspace/src/main/java/org/eclipse/dirigible/components/ide/workspace/endpoint/TransportEndpoint.java
components/ide/ide-workspace/src/main/java/org/eclipse/dirigible/components/ide/workspace/endpoint/WorkspaceEndpoint.java
components/ide/ide-workspace/src/main/java/org/eclipse/dirigible/components/ide/workspace/service/TransportService.java
components/ide/ide-workspace/src/test/java/org/eclipse/dirigible/components/ide/workspace/endpoint/WorkspacesEndpointTest.java
components/ide/ide-workspace/src/test/java/org/eclipse/dirigible/components/ide/workspace/service/ProjectTest.java
components/ide/ide-workspace/src/test/java/org/eclipse/dirigible/components/ide/workspace/service/WorkspaceTest.java
modules/database/database-mongodb-jdbc/src/main/java/org/eclipse/dirigible/mongodb/jdbc/MongoDBConnection.java
modules/database/database-sql-hana/src/main/java/org/eclipse/dirigible/database/sql/dialects/hana/HanaDropSequenceBuilder.java
modules/database/database-sql-mysql/src/test/java/org/eclipse/dirigible/database/sql/dialects/mysql/SequenceTest.java
modules/database/database-sql-sybase/src/test/java/org/eclipse/dirigible/database/sql/dialects/sybase/SequenceTest.java
modules/odata/odata-core-test/src/test/java/org/eclipse/dirigible/engine/odata2/sql/ODataSQLBatchTest.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLDeleteBuilder.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/utils/OData2Utils.java
modules/repository/repository-api/src/main/java/org/eclipse/dirigible/repository/api/RepositoryPath.java
modules/repository/repository-master/src/main/java/org/eclipse/dirigible/repository/master/jar/JarRepository.java

fix java code smells reported by Eclipse

---

components/resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/layout.js
components/resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/templates/splittedTabs.html
components/resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/widgets.js
components/resources/resources-resources/src/main/resources/META-INF/dirigible/resources/styles/widgets.css

Adds a hint to the icon tab bar widget.
#3002

[IDE] #3002 - Tab hints

---

components/ide/ide-ui-schema/src/main/resources/META-INF/dirigible/ide-schema/css/styles.css
components/ide/ide-ui-schema/src/main/resources/META-INF/dirigible/ide-schema/modeler.html

Moves all buttons from the bottom toolbar to the top toolbar in the DSM/Schema editor.
#3005

[DSM] #3005 - Move all buttons from the bottom toolbar to the top toolbar

---

.github/workflows/build.yml

fix build.yml

---

.github/workflows/build.yml

remove Setup Docker Buildx from integration tests

---

components/group/group-templates/pom.xml
components/ide/ide-ui-git-projects/src/main/resources/META-INF/dirigible/ide-git-projects/git-projects.html
components/resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/view.js
components/template/template-extension-view/src/main/resources/META-INF/dirigible/template-extension-view/extensions/views/view.extension.template
components/template/template-extension-view/src/main/resources/META-INF/dirigible/template-extension-view/template.js
components/template/template-extension-view/src/main/resources/META-INF/dirigible/template-extension-view/views/view/controller.js.template
components/template/template-extension-view/src/main/resources/META-INF/dirigible/template-extension-view/views/view/index.html.template
components/template/template-extension-view/src/main/resources/META-INF/dirigible/template-extension-view/views/view/view.js.template

Migrates the "Extension (View)" template to the new view system.
#3022

[Templates] #3022 - Migrate "Extension (View)"

---

build/application/pom.xml

fix devtools version

---

build/application/pom.xml
components/api/api-qldb/pom.xml
components/core/core-initializers/pom.xml
components/engine/engine-jobs/pom.xml
components/engine/engine-listeners/pom.xml
components/engine/engine-listeners/src/main/java/org/eclipse/dirigible/components/listeners/config/CloseActiveMQResourcesApplicationListener.java
components/engine/engine-listeners/src/main/java/org/eclipse/dirigible/components/listeners/service/ConnectionArtifacts.java
components/engine/engine-listeners/src/main/java/org/eclipse/dirigible/components/listeners/service/MessageConsumer.java
components/engine/engine-listeners/src/main/java/org/eclipse/dirigible/components/listeners/service/MessageProducer.java
components/engine/engine-listeners/src/test/java/org/eclipse/dirigible/components/listeners/config/CloseActiveMQResourcesApplicationListenerTest.java
components/engine/engine-listeners/src/test/java/org/eclipse/dirigible/components/listeners/service/ConnectionArtifactsTest.java
components/engine/engine-openapi/src/test/java/org/eclipse/dirigible/components/openapi/endpoint/OpenAPIEndpointTest.java
components/pom.xml
modules/database/database-mongodb-jdbc/pom.xml
modules/odata/odata-core/pom.xml
pom.xml
tests/pom.xml
tests/src/test/java/org/eclipse/dirigible/integration/tests/ui/framework/BrowserImpl.java

- use latest Spring Boot 2 - 2.7.18
- use dependencies from the spring-boot-dependencies as recommended

Spring Boot - use latest 2.*

---

components/data/data-sources/src/main/java/org/eclipse/dirigible/components/data/sources/manager/DataSourcesManager.java

Fixes: https://github.com/eclipse/dirigible/issues/3078

fix: do not register systemdb bean a second time

---

components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/cms/cmis.ts

Fixes:
- https://github.com/eclipse/dirigible/issues/3152

[API] CMIS - Adds utility methods to the CMIS Session

---

README.md

Readme for CMS with AWS S3
fixes #3161
Environment variables for setup can be found [here](https://www.dirigible.io/help/setup/setup-environment-variables/#cms)

[#3161] Documentation for CMS with S3

---

components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/db/index.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/db/query.ts

Added types to the typescript api db/query.ts
#3102

[API] TypeScript transformation - db/query.ts

---

components/data/data-csvim/src/main/java/org/eclipse/dirigible/components/data/csvim/synchronizer/CsvimSynchronizer.java
components/data/data-sources/src/main/java/org/eclipse/dirigible/components/data/sources/service/DataSourceLifecycleListener.java
components/data/data-structures/src/main/java/org/eclipse/dirigible/components/data/structures/synchronizer/schema/SchemaCreateProcessor.java
components/data/data-structures/src/main/java/org/eclipse/dirigible/components/data/structures/synchronizer/table/TableAlterProcessor.java
modules/commons/commons-config/src/main/java/org/eclipse/dirigible/commons/config/Configuration.java
modules/commons/commons-config/src/test/java/org/eclipse/dirigible/commons/config/ConfigurationTest.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/DataTypeUtils.java

- Do not fail on missing config for property with multi placeholders
- Add more details on some exceptions

Do not fail on missing config for property with multi placeholders

---

build/application/Dockerfile
build/application/src/main/java/org/eclipse/dirigible/DirigibleApplication.java
build/application/src/main/resources/application.properties
components/core/core-base/src/main/java/org/eclipse/dirigible/components/base/persistence/PersistenceConfig.java
components/core/core-database/src/main/java/org/eclipse/dirigible/components/database/DataSourceSystemConfig.java
components/data/data-source-snowpark/src/main/java/org/eclipse/dirigible/components/data/source/snowpark/DataSourceInitializerContributorSnowpark.java
components/data/data-sources/src/main/java/org/eclipse/dirigible/components/data/sources/manager/DataSourceInitializer.java
components/data/data-sources/src/main/java/org/eclipse/dirigible/components/data/sources/service/CustomDataSourcesService.java
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/config/BpmFlowableConfig.java
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/provider/BpmProviderFlowable.java
pom.xml

[#3253] Fix Snowpark properties and dataSource configurations

---

components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/db/update.ts

Added types for the db/update api

---

components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/core/configurations.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/core/context.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/core/destinations.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/core/env.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/core/globals.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/core/index.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/db/dao.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/db/orm.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/job/scheduler.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/mongodb/dao.ts

[#3101](https://github.com/eclipse/dirigible/pull/3101)

[API] TypeScript transformation - core

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/SqlDialectFactory.java

[#3292] Importing PostgreSQL datasource fix

---

components/template/template-application-dao/src/main/resources/META-INF/dirigible/template-application-dao/dao/entity.js.template

Fix entity template

---

components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/job/scheduler.ts

Aded types to typescript job api

---

components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/messaging/consumer.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/messaging/producer.ts

Added types to the messaging api
Typescript migration

[API] TypeScript transformation - messaging

---

components/core/core-database/src/main/java/org/eclipse/dirigible/components/database/DatabaseParameters.java
components/data/data-management/src/main/java/org/eclipse/dirigible/components/data/management/domain/ForeignKeyMetadata.java
components/data/data-management/src/main/java/org/eclipse/dirigible/components/data/management/domain/TableMetadata.java
components/data/data-management/src/main/java/org/eclipse/dirigible/components/data/management/helpers/DatabaseMetadataHelper.java
components/ide/ide-ui-database/src/main/resources/META-INF/dirigible/ide-database/explorer/explorer.js
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/SqlDialectFactory.java

The `Database` perspective now shows  foreign keys for tables
fixes #3284

[#3284] Database perspective shows foreign keys

---

components/data/data-management/src/main/java/org/eclipse/dirigible/components/data/management/domain/SchemaMetadata.java
components/data/data-management/src/main/java/org/eclipse/dirigible/components/data/management/domain/SequenceMetadata.java
components/data/data-management/src/main/java/org/eclipse/dirigible/components/data/management/helpers/DatabaseMetadataHelper.java
components/ide/ide-ui-database/src/main/resources/META-INF/dirigible/ide-database/explorer/explorer.js
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/SqlDialectFactory.java

The `Database` perspective now displays sequences for the schema you have selected

[#3286] Database perspective shows sequences

---

components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/bpm/deployer.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/bpm/process.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/bpm/tasks.ts

[#3132](https://github.com/eclipse/dirigible/pull/3132)

[API] TypeScript transformation - bpm

---

components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/bpm/deployer.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/bpm/process.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/bpm/tasks.ts

Reverts eclipse/dirigible#3249

Revert "[API] TypeScript transformation - bpm"

---

components/data/data-management/src/main/java/org/eclipse/dirigible/components/data/management/domain/SchemaMetadata.java
components/ide/ide-ui-database/src/main/resources/META-INF/dirigible/ide-database/explorer/explorer.js

[#3326] New database perspective structure

---

components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/log/logging.ts

Added types to typescript log api

---

components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/db/database.ts

Adds types to the db/database typescript api
#3102

Added types to database.ts api in db

---

components/data/data-management/src/main/java/org/eclipse/dirigible/components/data/management/domain/SchemaMetadata.java
components/data/data-management/src/main/java/org/eclipse/dirigible/components/data/management/helpers/DatabaseMetadataHelper.java

Fix MariaDB datasource not displaying Sequences

Fix MariaDB not showing sequences

---

components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/db/dao.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/db/ormstatements.ts

Fixes https://github.com/eclipse/dirigible/issues/3345

[API] DAO - Enhance Filter Functionality

---

components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/editor.js

Updated the Entity editor config, so that when a user is renaming the cell value and hits enter, the value will be applied instead of creating a new line.
#3358

[EDM] #3358 - Cell value is not applied on enter

---

components/api/api-database/src/main/java/org/eclipse/dirigible/components/api/db/DatabaseFacade.java
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/db/dao.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/db/insert.ts

Support inserting entity when DB doesn't support sequences and the id column is AUTO_INCREMENT

Support AUTO_INCREMENT id columns

---

components/api/api-database/src/main/java/org/eclipse/dirigible/components/api/db/DatabaseFacade.java

A fix for https://github.com/eclipse/dirigible/issues/3223

Support timestamps in format yyyy-MM-dd HH:mm:ss.SSS

---

components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/details.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/editor.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/serializer.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/views/details.html
components/ide/ide-ui-generate-service/src/main/resources/META-INF/dirigible/ide-generate-service/generate.mjs
components/ide/ide-ui-generate-service/src/main/resources/META-INF/dirigible/ide-generate-service/template/parameterUtils.js
components/ide/ide-ui-projects/src/main/resources/META-INF/dirigible/ide-projects/js/projects.js
components/template/template-application-dao/src/main/resources/META-INF/dirigible/template-application-dao/dao/entity.js.template
components/template/template-application-dao/src/main/resources/META-INF/dirigible/template-application-dao/template/template.js
components/template/template-application-odata/src/main/resources/META-INF/dirigible/template-application-odata/odata/application.odata.template
components/template/template-application-odata/src/main/resources/META-INF/dirigible/template-application-odata/template/template.js
components/template/template-application-schema/src/main/resources/META-INF/dirigible/template-application-schema/data/application.schema.template
components/template/template-application-schema/src/main/resources/META-INF/dirigible/template-application-schema/template/template.js

Fixes:
- https://github.com/eclipse/dirigible/issues/3369
- https://github.com/eclipse/dirigible/issues/3368
- https://github.com/eclipse/dirigible/issues/3376
Sample EDM, using the `SystemDB` datasource to fetch data from the `DIRIGIBLE_JOBS` table:
https://github.com/eclipse/dirigible/assets/4092083/c14a780c-2b40-4c70-a0fd-388ff000054f

[EDM] Templates Enhancements

---

components/data/data-export/src/main/java/org/eclipse/dirigible/components/data/export/service/DataExportService.java
components/data/data-export/src/test/java/org/eclipse/dirigible/components/data/export/service/DataExportServiceTest.java
components/data/data-management/src/main/java/org/eclipse/dirigible/components/data/management/helpers/DatabaseMetadataHelper.java
components/data/data-management/src/main/java/org/eclipse/dirigible/components/data/management/load/DataSourceMetadataLoader.java
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/js/bpm-process-context.js
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/services/bpm-process-context-view.js
modules/database/database-sql-mariadb/src/main/java/org/eclipse/dirigible/database/sql/dialects/mariadb/MariaDBDeleteBuilder.java
modules/database/database-sql-mariadb/src/main/java/org/eclipse/dirigible/database/sql/dialects/mariadb/MariaDBInsertBuilder.java
modules/database/database-sql-mariadb/src/main/java/org/eclipse/dirigible/database/sql/dialects/mariadb/MariaDBUpdateBuilder.java

- Snowflake sequences fix
- MariaDB export operations fix
- Export operations naming change

Fixes to datasource operations

---

modules/engines/engine-graalium/execution-core/src/main/java/org/eclipse/dirigible/graalium/core/DirigibleJavascriptCodeRunner.java

Tested with Camel and Scheduled jobs.

[Camel] Cannot execute TypeScript files

---

components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/details.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/editor.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/serializer.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/views/details.html

Related to:
- https://github.com/eclipse/dirigible/issues/3378

[EDM] Removes "data source" configuration per entity

---

components/ide/ide-ui-generate-service/src/main/resources/META-INF/dirigible/ide-generate-service/template/parameterUtils.js
components/template/template-application-dao/src/main/resources/META-INF/dirigible/template-application-dao/dao/entity.ts.template
components/template/template-application-dao/src/main/resources/META-INF/dirigible/template-application-dao/dao/reportEntity.ts.template
components/template/template-application-rest/src/main/resources/META-INF/dirigible/template-application-rest/api/entity.ts.template
components/template/template-application-rest/src/main/resources/META-INF/dirigible/template-application-rest/api/reportEntity.ts.template

Related to:
- https://github.com/eclipse/dirigible/issues/3412

[Template] Adds support for more database types instead of unknown

---

components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/details.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/editor.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/serializer.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/views/details.html
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/list/dialog-window/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/manage/dialog-window/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/detail/dialog-window/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/main-details/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/detail/dialog-window/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/main-details/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/report-table/dialog-window/index.html.template

Introduces a new widget property `widgetSize` that controls the width of the widget
#3330

[EDM] Support widgetSize for the grid layout

---

components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/details.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/editor.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/model.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/serializer.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/views/details.html
components/ide/ide-ui-generate-service/src/main/resources/META-INF/dirigible/ide-generate-service/template/generateUtils.js
components/ide/ide-ui-generate-service/src/main/resources/META-INF/dirigible/ide-generate-service/template/parameterUtils.js
components/template/template-application-schema/src/main/resources/META-INF/dirigible/template-application-schema/data/application.schema.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/list/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/manage/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/detail/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/detail/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/report-table/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/report-table/dialog-window-filter/controller.js.template

- Added checkbox `Disable generation` in the EDM for entities to stop generation of files for the selected entitiy
- Changed the templete for `controller.js` to now correctly get the `Service.ts` component for projection entities from their own projects

[EDM] Support for projection entities

---

components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/details.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/editor.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/model.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/serializer.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/views/details.html
components/ide/ide-ui-generate-service/src/main/resources/META-INF/dirigible/ide-generate-service/template/parameterUtils.js
components/template/template-application-dao/src/main/resources/META-INF/dirigible/template-application-dao/dao/entity.ts.template
components/template/template-application-rest/src/main/resources/META-INF/dirigible/template-application-rest/api/entity.ts.template

Introduce Top Level Imports

---

README.md
components/resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/widgets.js

Fixes the validation for both the `fd-combobox-input` (dropdown) widget and the general `dg-input-rules` directive, used by all inputs.
#3355

[Templates] #3355 - Cannot select the first entry in dropdown widget

---

components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/views/details.html

update of details view

---

components/template/template-application-dao/src/main/resources/META-INF/dirigible/template-application-dao/dao/entity.ts.template

Fixes:
- https://github.com/eclipse/dirigible/issues/3224

[EDM] Use topic instead of queue for publishing messages in the DAOs

---

components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/list/dialog-window/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/manage/dialog-window/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/detail/dialog-window/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/main-details/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/detail/dialog-window/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/main-details/index.html.template

[EDM] Display URL, Email and Telephone widgets as links

---

components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/list/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/list/dialog-window/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/manage/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/manage/dialog-window/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/detail/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/detail/dialog-window/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/main-details/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/detail/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/detail/dialog-window/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/main-details/index.html.template

Increase the default widget size of the `DATETIME-LOCAL` widget from `fd-col-md--2` to `fd-col-md--3`
Fixes: #3481

[EDM] Increase DateTime default widget size

---

components/resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/core-modules.js
components/resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/templates/accordionPane.html
components/resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/templates/ideHeader.html
components/resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/templates/ideSidebar.html
components/resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/templates/layout.html
components/resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/widgets.js
components/resources/resources-resources/src/main/resources/META-INF/dirigible/resources/styles/widgets.css

Fixes the dropdown body height, not being properly set for all widgets that have it.
Additionally, it removes some unneeded watchers and adds a clean-up for all custom ones.
#3433

[UI] #3433 - More views dropdown is not properly visualized

---

pom.xml

Reverts eclipse/dirigible#3570

Revert "Bump org.apache.maven.plugins:maven-gpg-plugin from 3.1.0 to 3.2.0"

---

components/api/api-security/src/main/java/org/eclipse/dirigible/components/api/security/UserFacade.java
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/dto/TaskDTO.java
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/endpoint/BpmFlowableEndpoint.java
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/service/task/TaskQueryExecutor.java

This PR is implementation for FR #3604 
The idea is to take the roles or username of the currently logged-in user and based on that to retrieve all the user tasks assigned (or candidate) to him

[BPM][Inbox] Feature#3604: Implement get tasks API using security context

---

components/template/template-application-dao/src/main/resources/META-INF/dirigible/template-application-dao/dao/entity.ts.template

[EDM] Default Values Fix

---

components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/list/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/manage/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/detail/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/detail/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/dialog-filter/index.html.template

[EDM] Filter fields shouldn't be required

---

components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/list/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/manage/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/detail/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/detail/controller.js.template

[EDM] Show Items(0) instead of Items() on missing entities

---

components/ide/ide-ui-form-builder/src/main/resources/META-INF/dirigible/ide-form-builder/css/editor.css
components/resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/core-modules.js
components/resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/templates/ideHeader.html

Adds a confirmation dialog when a user selects the "Reset" option in the "Theme" dropdown.
#3640

[UI] #3640 - Add a warning before resetting all data

---

components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/bpm-tasks.html
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/js/bpm-tasks.js
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/services/bpm-tasks-view.js

[BPM][Inbox] User tasks UI implementation

---

build/application/src/main/resources/quartz.properties
components/core/core-database/src/main/java/org/eclipse/dirigible/components/database/DataSourceSystemConfig.java
components/data/data-sources/src/main/java/org/eclipse/dirigible/components/data/sources/manager/DataSourceInitializer.java
components/data/data-sources/src/main/java/org/eclipse/dirigible/components/data/sources/manager/DataSourcesManager.java
components/data/data-sources/src/main/java/org/eclipse/dirigible/components/data/sources/manager/TenantDataSourceNameManager.java
components/data/data-sources/src/main/java/org/eclipse/dirigible/components/data/sources/provisioning/DefaultDataSourceProvisioning.java
components/data/data-sources/src/main/resources/META-INF/dirigible/datasources/DefaultDB.datasource
components/data/data-sources/src/main/resources/META-INF/dirigible/datasources/SystemDB.datasource
components/engine/engine-jobs/src/main/java/org/eclipse/dirigible/components/jobs/config/QuartzConfig.java
components/ide/ide-ui-generate-service/src/main/resources/META-INF/dirigible/ide-generate-service/template/parameterUtils.js
components/ide/ide-ui-result/src/main/resources/META-INF/dirigible/ide-result/js/result.js
components/template/template-application-schema/src/main/resources/META-INF/dirigible/template-application-schema/data/application.schema.template
components/test-project/src/main/resources/META-INF/dirigible/test-project/schemas/test.schema

Tested with the following env variables:
```
export DIRIGIBLE_DATABASE_DATASOURCE_NAME_SYSTEM="MySystemDB"
export DIRIGIBLE_DATABASE_CUSTOM_DATASOURCES=TEST2
export DIRIGIBLE_DATABASE_DATASOURCE_NAME_DEFAULT=TEST2
export TEST2_DRIVER=org.h2.Driver
export TEST2_URL=jdbc:h2:file:./target/dirigible/h2/Test2DB
export TEST2_USERNAME=sa
export TEST2_PASSWORD=
```
- To regenerated
- clear browser cache
- remove `gen` folder
- delete `*.gen` file
- delete `*.model` file
- regenerate from edm file
- regenerate from model file

configurable Default and System datasource

---

components/ide/ide-ui-bpm/src/main/resources/META-INF/dirigible/ide-bpm/editor-app/configuration/properties-assignment-controller.js
components/ide/ide-ui-bpm/src/main/resources/META-INF/dirigible/ide-bpm/editor-app/configuration/properties/assignment-popup.html

[BPM][Inbox] Restrict assignment UI

---

tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/util/FileUtil.java
tests/tests-integrations/src/test/java/org/eclipse/dirigible/integration/tests/DirigibleCleaner.java

do not delete entire cms folder, only the files

---

components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/endpoint/BpmFlowableEndpoint.java
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/js/bpm-tasks.js

[BPM][Inbox] Claim user task functionality

---

components/ide/ide-ui-form-builder/src/main/resources/META-INF/dirigible/ide-form-builder/editor.html
components/ide/ide-ui-form-builder/src/main/resources/META-INF/dirigible/ide-form-builder/js/editor.js

Fixes the radio widget in the Form Editor
#3762

[Form] #3762 - The Radio Options are not Persisted

---

components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/endpoint/BpmFlowableEndpoint.java
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/service/BpmService.java
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/bpm-historic-process-instances.html
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/extensions/bpm-historic-process-instances-view.extension
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/js/bpm-historic-process-instances.js
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/js/bpm-perspective.js
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/services/bpm-historic-process-instances-view.js

[BPM] List historic process instances

---

components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/http/decorators.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/http/rs/resource-http-controller.ts
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/details.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/editor.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/serializer.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/views/details.html
components/ide/ide-ui-generate-service/src/main/resources/META-INF/dirigible/ide-generate-service/template/generateUtils.js
components/template/template-application-dao/src/main/resources/META-INF/dirigible/template-application-dao/template/template.js
components/template/template-application-rest/src/main/resources/META-INF/dirigible/template-application-rest/api/api.openapi.template
components/template/template-application-rest/src/main/resources/META-INF/dirigible/template-application-rest/template/template.js
components/template/template-application-schema/src/main/resources/META-INF/dirigible/template-application-schema/data/application.schema.template

Fixes: https://github.com/eclipse/dirigible/issues/3791

[EDM] Generate OpenAPI

---

components/resources/resources-inbox/src/main/resources/META-INF/dirigible/inbox/ui/launchpad/Home/controller.js
components/resources/resources-inbox/src/main/resources/META-INF/dirigible/inbox/ui/launchpad/Home/index.html

[BPM][Inbox] Add automatic tasks reloading

---

components/api/api-cache/src/main/java/org/eclipse/dirigible/components/api/cache/CacheFacade.java
components/api/api-cache/src/test/java/org/eclipse/dirigible/components/api/cache/CacheFacadeTest.java
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/cache/cache.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/cache/index.ts
modules/engines/engine-graalium/execution-core/src/main/java/org/eclipse/dirigible/graalium/core/modules/DirigibleModulesMetadata.java
tests/tests-integrations/src/test/resources/META-INF/dirigible/modules-tests/src/cache/cache-test.ts

- Fix cache API, so that it works properly
- Configure cache
- entries will expire after 15 minutes after the write operation
- cache max size will be 1000

fix cache API

---

components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/dialogs.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/editor.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/widgets.js
components/ide/ide-ui-projects/src/main/resources/META-INF/dirigible/ide-projects/js/projects.js

While it does not add arrows for moving properties up and down, it does enable Drag & Drop reordering.
The current limitation is that you cannot move multiple properties at once, you will have to move them one by one.
Demo:
https://github.com/eclipse/dirigible/assets/82379274/a0e70b0f-446e-4538-9168-90e0b8e634ff
#3764

[EDM] #3764 - Move up/down arrow for entity's properties

---

components/ide/ide-ui-registry/src/main/resources/META-INF/dirigible/ide-registry/extensions/workspace-after-unpublish.extension
components/ide/ide-ui-registry/src/main/resources/META-INF/dirigible/ide-registry/services/unpublish-typescript.js

Fixes: https://github.com/eclipse/dirigible/issues/3836

[IDE] Add support for unpublish of a single Typescript file

---

components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/list/dialog-filter/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/list/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/manage/dialog-filter/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/manage/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/detail/dialog-filter/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/detail/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/dialog-filter/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/detail/dialog-filter/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/detail/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/dialog-filter/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/dialog-filter/index.html.template

Fixes: https://github.com/eclipse/dirigible/issues/3725

[EDM] Enable filtering by boolean field with value false

---

components/ide/ide-ui-form-builder/src/main/resources/META-INF/dirigible/ide-form-builder/js/editor.js
components/ide/ide-ui-jobs/src/main/resources/META-INF/dirigible/ide-jobs/view/job-trigger.html
components/resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/widgets.js
components/template/template-form-builder-angularjs/src/main/resources/META-INF/dirigible/template-form-builder-angularjs/ui/index.html.template
components/template/template-html-widgets/src/main/resources/META-INF/dirigible/template-html-widgets/controller.js
components/template/template-html-widgets/src/main/resources/META-INF/dirigible/template-html-widgets/index.html.template
components/template/template-html/src/main/resources/META-INF/dirigible/template-html/index.html.template

Adds support for compact mode in the Form Editor and the template used for form generation.
Fixes paragraph getting deleted when a user presses the delete button while editing its text in the Form Editor.
#3782 
#3761

[Templates] #3782 - Support of Widget Size in the Form Designer

---

components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/bpm-image-viewer.html
components/ide/ide-ui-form-builder/src/main/resources/META-INF/dirigible/ide-form-builder/editor.html
components/ide/ide-ui-form-builder/src/main/resources/META-INF/dirigible/ide-form-builder/js/editor.js
components/ide/ide-ui-image/src/main/resources/META-INF/dirigible/ide-image/editor.html
components/ide/ide-ui-monaco/src/main/resources/META-INF/dirigible/ide-monaco/api/extensions/core.js
components/ide/ide-ui-monaco/src/main/resources/META-INF/dirigible/ide-monaco/js/editor.js
components/resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/widgets.js
components/resources/resources-resources/src/main/resources/META-INF/dirigible/resources/styles/widgets.css
components/template/template-form-builder-angularjs/src/main/resources/META-INF/dirigible/template-form-builder-angularjs/ui/controller.js.template
components/template/template-form-builder-angularjs/src/main/resources/META-INF/dirigible/template-form-builder-angularjs/ui/index.html.template
components/template/template-form/src/main/resources/META-INF/dirigible/template-form/form/order.form.template

Adds primitive support for Velocity template file highlighting in the main editor.
Adds a new category in the Form editor called "Display". It will contain controls which are not form inputs but could be included in the form to display information.
Adds an image control to the Form editor.
Adds support for static data in the select control in the Form editor.
Adds support for dynamic data in the radio control in the Form editor.
Adds a regenerate button in the Form editor.
#3777 
#3846 
#3888 
#3889

[IDE] Various fixes and improvements for the Form and Code editors

---

components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/bpm-process-jobs.html
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/js/bpm-process-jobs.js

[BPM] Use a separate dialog for the dead-letter job's stacktrace

---

components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/db/ormstatements.ts

[API] Fix limit and offset to work independently

---

components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/bpm-historic-process-instances.html

[BPM] Unify the dates across all views in the BPM perspective

---

components/api/api-database/src/main/java/org/eclipse/dirigible/components/api/db/ParametersSetter.java

A fix for https://github.com/eclipse/dirigible/issues/3928

Fix update API - allow using  floating-point types

---

components/data/data-structures/src/main/java/org/eclipse/dirigible/components/data/structures/domain/TableConstraints.java
components/engine/engine-odata/src/main/java/org/eclipse/dirigible/components/odata/transformers/OData2ODataMTransformer.java

Fix NPE in toString

---

components/engine/engine-camel/pom.xml

Adds missing dependency for camel-stream.
https://github.com/eclipse/dirigible/issues/3955

Add camel-stream dependency

---

components/engine/engine-odata/src/main/java/org/eclipse/dirigible/components/odata/api/ODataEntity.java
components/engine/engine-odata/src/main/java/org/eclipse/dirigible/components/odata/transformers/DefaultTableMetadataProvider.java
components/engine/engine-odata/src/main/java/org/eclipse/dirigible/components/odata/transformers/OData2ODataMTransformer.java
components/engine/engine-odata/src/test/java/org/eclipse/dirigible/components/odata/transformers/OData2ODataMTransformerTest.java
modules/commons/commons-config/src/main/java/org/eclipse/dirigible/commons/config/DirigibleConfig.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/binding/EdmTableBinding.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/AbstractQueryBuilder.java

Support exposing OData entities from tables which are located in different schemas than the default one, but the DB user has access to these schemas.

Support exposing OData entities from another schema

---

components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/bpm-historic-process-instances.html

FR#3844: Add proper columns to historic instances

---

modules/database/database-sql-hana/src/main/java/org/eclipse/dirigible/database/sql/dialects/hana/HanaSqlDialect.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/ISqlDialect.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/DropBranchingBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/view/DropViewBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/DefaultSqlDialect.java

Currently:
-  the existence check, doesn't include the artefact schema
- drop view doesn't support specifying the schema

fix tables and views check for existence

---

modules/database/database-sql-hana/src/main/java/org/eclipse/dirigible/database/sql/dialects/hana/HanaDropSequenceBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/ISqlKeywords.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/sequence/DropSequenceBuilder.java

A fix for https://github.com/eclipse/dirigible/issues/4006

Support sequence drop option

---

components/core/core-base/src/main/java/org/eclipse/dirigible/components/base/synchronizer/SynchronizerCallback.java
components/core/core-extensions/src/main/java/org/eclipse/dirigible/components/extensions/synchronizer/ExtensionPointsSynchronizer.java
components/core/core-extensions/src/main/java/org/eclipse/dirigible/components/extensions/synchronizer/ExtensionsSynchronizer.java
components/core/core-initializers/src/main/java/org/eclipse/dirigible/components/initializers/synchronizer/SynchronizationProcessor.java
components/data/data-csvim/src/main/java/org/eclipse/dirigible/components/data/csvim/synchronizer/CsvimSynchronizer.java
components/data/data-sources/src/main/java/org/eclipse/dirigible/components/data/sources/synchronizer/DataSourcesSynchronizer.java
components/data/data-store/src/main/java/org/eclipse/dirigible/components/data/store/synchronizer/EntitySynchronizer.java
components/data/data-structures/src/main/java/org/eclipse/dirigible/components/data/structures/synchronizer/SchemasSynchronizer.java
components/data/data-structures/src/main/java/org/eclipse/dirigible/components/data/structures/synchronizer/TablesSynchronizer.java
components/data/data-structures/src/main/java/org/eclipse/dirigible/components/data/structures/synchronizer/ViewsSynchronizer.java
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/synchronizer/BpmnSynchronizer.java
components/engine/engine-camel/src/main/java/org/eclipse/dirigible/components/engine/camel/synchronizer/CamelSynchronizer.java
components/engine/engine-jobs/src/main/java/org/eclipse/dirigible/components/jobs/synchronizer/JobSynchronizer.java
components/engine/engine-listeners/src/main/java/org/eclipse/dirigible/components/listeners/synchronizer/ListenerSynchronizer.java
components/engine/engine-odata/src/main/java/org/eclipse/dirigible/components/odata/synchronizer/ODataSynchronizer.java
components/engine/engine-openapi/src/main/java/org/eclipse/dirigible/components/openapi/synchronizer/OpenAPISynchronizer.java
components/engine/engine-security/src/main/java/org/eclipse/dirigible/components/security/synchronizer/AccessSynchronizer.java
components/engine/engine-security/src/main/java/org/eclipse/dirigible/components/security/synchronizer/RoleSynchronizer.java
components/engine/engine-web/src/main/java/org/eclipse/dirigible/components/engine/web/synchronizer/ExposesSynchronizer.java
components/engine/engine-websockets/src/main/java/org/eclipse/dirigible/components/websockets/synchronizer/WebsocketsSynchronizer.java
components/engine/engine-wiki/src/main/java/org/eclipse/dirigible/components/engine/wiki/synchronizer/ConfluenceSynchronizer.java
components/engine/engine-wiki/src/main/java/org/eclipse/dirigible/components/engine/wiki/synchronizer/MarkdownSynchronizer.java

a fix for https://github.com/eclipse/dirigible/issues/4021

Reduce duplicated logging and improve SynchronizerCallback API

---

.github/workflows/release.yml

Change zip command to package executable into release file.
Fixes: https://github.com/eclipse/dirigible/issues/3978

Change zip command to package executable into release file.

---

components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/db/database.ts

A fix for: https://github.com/codbex/codbex-kronos/issues/588

fix errors when reading clob, nclob and blob

---

components/api/api-database/src/main/java/org/eclipse/dirigible/components/api/db/DatabaseFacade.java
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/db/database.ts
components/data/data-sources/src/main/java/com/zaxxer/hikari/pool/LeakedConnectionsDoctor.java
components/data/data-sources/src/main/java/org/eclipse/dirigible/components/data/sources/manager/DataSourceInitializer.java
components/data/data-sources/src/main/java/org/eclipse/dirigible/components/data/sources/manager/ManagedDataSource.java

A fix for https://github.com/eclipse/dirigible/issues/4029
Includes
- fine tune Hikari connection pool
- automatically detect and fix leaked connections so that the app can be used

Fine tune Hikari connection pool and add leaked connections detection and remediation logic

---

components/data/data-management/src/main/java/org/eclipse/dirigible/components/data/management/helpers/DatabaseResultSetHelper.java
components/engine/engine-javascript/src/main/java/org/eclipse/dirigible/components/engine/javascript/service/JavascriptHandler.java

related to: https://github.com/codbex/codbex-kronos/issues/598

ABAP - support inline statements

---

components/core/core-base/src/main/java/org/eclipse/dirigible/components/base/spring/BeanProvider.java
components/data/data-management/src/main/java/org/eclipse/dirigible/components/data/management/helpers/DatabaseResultSetHelper.java
modules/engines/engine-graalium/execution-core/pom.xml
modules/engines/engine-graalium/execution-core/src/main/java/org/eclipse/dirigible/graalium/core/DirigibleJavascriptCodeRunner.java
modules/engines/engine-graalium/execution-core/src/main/java/org/eclipse/dirigible/graalium/core/modules/DirigibleSourceProvider.java
modules/engines/engine-graalium/execution-core/src/main/java/org/eclipse/dirigible/graalium/core/modules/ExternalModuleResolver.java

- use case - add Kronos libraries as part of sdk apis (sdk/abap)

Support resolving external libraries

---

components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/bpm-tasks.html
components/resources/resources-inbox/src/main/resources/META-INF/dirigible/inbox/ui/launchpad/Home/controller.js
components/resources/resources-inbox/src/main/resources/META-INF/dirigible/inbox/ui/launchpad/Home/index.html

FR#4014: Implement generic forms functionality in the standalone app

---

components/data/data-management/src/main/java/org/eclipse/dirigible/components/data/management/helpers/DatabaseResultSetHelper.java
components/ide/ide-ui-welcome/src/main/resources/META-INF/dirigible/ide-welcome/welcome.html
tests/tests-framework/pom.xml
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/EdmView.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/IDE.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/WelcomeView.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/Workbench.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/framework/Browser.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/framework/HtmlAttribute.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/framework/HtmlElementType.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/framework/impl/BrowserImpl.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/restassured/RestAssuredExecutor.java
tests/tests-integrations/src/test/java/org/eclipse/dirigible/integration/tests/ui/TestProject.java
tests/tests-integrations/src/test/java/org/eclipse/dirigible/integration/tests/ui/tests/DirigibleHomepageIT.java
tests/tests-integrations/src/test/java/org/eclipse/dirigible/integration/tests/ui/tests/HomepageRedirectIT.java

- need for Kronos ABAP Starter template tests
- fix template typo as well

Enhance UI testing module

---

components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/delegate/DirigibleCallDelegate.java
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/endpoint/BpmFlowableEndpoint.java
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/endpoint/TaskVariablesDTO.java

Example:
`http://localhost:8080/services/bpm/bpm-processes/tasks/445/variables`

add REST api for tasks variables + allow TS tasks

---

components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/config/BpmFlowableConfig.java
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/provider/BpmProviderFlowable.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/FormView.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/IDE.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/WelcomeView.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/Workbench.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/framework/Browser.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/framework/impl/BrowserImpl.java
tests/tests-integrations/pom.xml
tests/tests-integrations/src/test/java/org/eclipse/dirigible/integration/tests/DirigibleCleaner.java
tests/tests-integrations/src/test/java/org/eclipse/dirigible/integration/tests/ui/tests/BPMStarterTemplateIT.java
tests/tests-integrations/src/test/java/org/eclipse/dirigible/integration/tests/ui/tests/OrderedTestSuite.java

Test steps:
- generates new project using `BPM Project Starter` template
- generates trigger process form
- triggers a new process instance using the generated form
- verifies that the process tasks logs an expected message
This test verifies that
- `BPM Project Starter` template works
- BPM engine is configured and works 
- Forms works
- BPM JavaScript API
- TS REST API

BPM Starter project integration test

---

components/core/core-base/src/main/java/org/eclipse/dirigible/components/base/http/access/UserRequestVerifier.java
components/core/core-tenants/src/main/java/org/eclipse/dirigible/components/tenants/security/CustomUserDetailsService.java
components/engine/engine-security/src/main/java/org/eclipse/dirigible/components/security/filter/SecurityFilter.java
components/engine/engine-security/src/main/java/org/eclipse/dirigible/components/security/synchronizer/AccessSynchronizer.java
components/ide/ide-ui-security-menu/src/main/resources/META-INF/dirigible/ide-security-menu/services/workspace-menu-new-template-roles.js
components/security/security-keycloak/src/main/java/org/eclipse/dirigible/components/security/keycloak/CustomOidcUserService.java
tests/tests-framework/pom.xml
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/IDE.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/IDEFactory.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/framework/Browser.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/framework/BrowserFactory.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/framework/HtmlElementType.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/framework/impl/BrowserFactoryImpl.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/framework/impl/BrowserImpl.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/util/SecurityUtil.java
tests/tests-integrations/src/test/java/org/eclipse/dirigible/integration/tests/ui/TestProject.java
tests/tests-integrations/src/test/java/org/eclipse/dirigible/integration/tests/ui/tests/CustomSecurityIT.java
tests/tests-integrations/src/test/resources/dirigible-test-project/security/access.access
tests/tests-integrations/src/test/resources/dirigible-test-project/security/protected_page.html
tests/tests-integrations/src/test/resources/dirigible-test-project/security/roles.roles

- fix access constraints bug - fix parsing of multiple constrains
- fix security filter - get request path from the right method
- fix user roles assignment in the spring context - add `ROLE_` prefix when needed
- add UI integration test for the custom security with `.roles` and `.access`

Fix access functionality

---

components/api/api-git/src/main/java/org/eclipse/dirigible/components/api/git/GitFacade.java
components/core/core-initializers/src/main/java/org/eclipse/dirigible/components/initializers/classpath/ClasspathExpander.java
components/data/data-management/src/main/java/org/eclipse/dirigible/components/data/management/endpoint/DatabaseExecutionEndpoint.java
components/engine/engine-command/src/main/java/org/eclipse/dirigible/components/engine/command/service/CommandService.java
components/ide/ide-git/src/main/java/org/eclipse/dirigible/components/ide/git/domain/GitConnectorFactory.java
components/ide/ide-workspace/src/main/java/org/eclipse/dirigible/components/ide/workspace/endpoint/TransportEndpoint.java

needed to investigate snowflake issues

Add exception causes to help in issues resolution

---

components/data/data-source-snowpark/src/main/java/org/eclipse/dirigible/components/data/source/snowpark/DataSourceInitializerContributorSnowpark.java
pom.xml

Example env variables to create SNOWFLAKE datasource:
```
export DIRIGIBLE_DATABASE_CUSTOM_DATASOURCES='SNOWFLAKE'
export DIRIGIBLE_DATABASE_DATASOURCE_NAME_DEFAULT='SNOWFLAKE'
export SNOWFLAKE_DRIVER='net.snowflake.client.jdbc.SnowflakeDriver'
export SNOWFLAKE_URL='jdbc:snowflake://jiixfdf-qd67203.snowflakecomputing.com'
export SNOWFLAKE_USERNAME='<my-user>'
export SNOWFLAKE_PASSWORD='<my-password>'
export SNOWFLAKE_WAREHOUSE='CONTAINER_HOL_WH_ILIYAN_NEW'
export SNOWFLAKE_DATABASE='CONTAINER_HOL_DB_ILIYAN_NEW'
export SNOWFLAKE_ROLE='CONTAINER_USER_ROLE_ILIYAN_NEW'
export SNOWFLAKE_SCHEMA='PUBLIC'
```

Fix snowflake communication

---

components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/details.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/editor.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/model.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/serializer.js
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/views/details.html
components/resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/entityApi.js
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/manage/dialog-window/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/detail/dialog-window/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/main-details/controller.js.template

**Demo:**
https://github.com/user-attachments/assets/26a8dc89-2fab-4828-836d-7d9ad98f6a4f
Fixes: https://github.com/eclipse/dirigible/issues/4178

[EDM] Dependent property feature

---

README.md

motivated by 
- https://github.com/eclipse/dirigible/issues/3878#issuecomment-2293275645
- additional info - https://github.com/eclipse/dirigible/issues/3878#issuecomment-2293413069

update docker run readme - hints for volumes mounting

---

components/data/data-source-snowpark/src/main/java/org/eclipse/dirigible/components/data/source/snowpark/SnowflakeDatabaseConfigurator.java
components/ide/ide-ui-databases/src/main/resources/META-INF/dirigible/ide-databases/dialogs/database-dialog.js

Register MariaDB in the UI

---

build/application/pom.xml
pom.xml

fix vulnerabilities in commons-collections

fix critical vulnerabilities in commons-collections

---

README.md

Fix badges in  README.md

---

pom.xml
tests/tests-integrations/src/test/java/org/eclipse/dirigible/integration/tests/services/integrations/CamelPlatformHttpIT.java

Downgrade camel version to fix Camel issue https://github.com/eclipse/dirigible/issues/4392

Downgrade camel version

---

components/engine/engine-camel/src/main/java/org/eclipse/dirigible/components/engine/camel/invoke/DirigibleJavaScriptInvokerImpl.java
pom.xml

The code from https://github.com/eclipse/dirigible/pull/4470 + bump camel to 4.8.0.
Details in: https://github.com/eclipse/dirigible/pull/4470
Workaround for https://github.com/eclipse/dirigible/issues/4392

Fix camel async issue in 4.8.0

---

components/resources/resources-portal/src/main/resources/META-INF/dirigible/portal/js/dashboard-controller.js

Change maximum size of widgets containers for small and large widgets
codbex/codbex-olympus#235

fix(codbex/codbex-olympus#235): change size of widgets containers

---

components/resources/resources-portal/src/main/resources/META-INF/dirigible/portal/js/dashboard-controller.js
components/resources/resources-portal/src/main/resources/META-INF/dirigible/portal/subviews/dashboard.html

fixes codbex/codbex-olympus#247

[Dashboard] Hides unused widget controllers 

---

components/api/api-http/src/main/java/org/eclipse/dirigible/components/api/http/HttpClientFacade.java

[API] HTTP Client - Handling of custom response content types and data serialization

---

.github/workflows/pull-request.yml

enable pull-request.yml for all branches

---

components/core/core-base/src/main/java/org/eclipse/dirigible/components/base/http/access/CustomSecurityConfigurator.java
components/core/core-base/src/main/java/org/eclipse/dirigible/components/base/http/access/HttpSecurityURIConfigurator.java
components/core/core-tenants/src/main/java/org/eclipse/dirigible/components/tenants/security/BasicSecurityConfig.java
components/security/security-keycloak/src/main/java/org/eclipse/dirigible/components/security/keycloak/KeycloakSecurityConfiguration.java
components/security/security-oauth2/src/main/java/org/eclipse/dirigible/components/security/oauth2/OAuth2SecurityConfiguration.java
components/security/security-snowflake/src/main/java/org/eclipse/dirigible/components/security/snowflake/SnowflakeSecurityConfig.java

Add interface (CustomSecurityConfigurator) for custom security configurations.

Add java interface for custom security configurations

---

tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/framework/HtmlElementType.java

add more elements in HtmlElementType

---

components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/main-details/controller.js.template

Adds missing bracket in main-details controller template
Fixes: #4622 - Depends on feature not working properly

add missing bracket in template

---

components/resources/resources-portal/src/main/resources/META-INF/dirigible/portal/js/dashboard-controller.js

fixes codbex/codbex-olympus#334

fix: redirect view on clicked widgets in dashboard-controller.js

---

components/resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/templates/ideSidebar.html
components/ui/platform-core/src/main/resources/META-INF/dirigible/platform-core/ui/platform/shell.js
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/IDE.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/Workbench.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/framework/Browser.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/framework/impl/BrowserImpl.java
tests/tests-integrations/src/test/resources/logback-test.xml

- Add ids to perspectives
- Improve UI testing framework
- Check for elements in all iframes using recursion
- Fail if found more than one elements with match the conditions and selector
- code refactoring

Perspective IDs and UI test framework Improvements

---

.github/workflows/build.yml
.github/workflows/pull-request.yml

Generate random name for Selenide files zip to prevent issues like the following:

Generate random name for Selenide files zip

---

build/application/src/main/java/org/eclipse/dirigible/AppLifecycleLoggingListener.java
build/application/src/main/java/org/eclipse/dirigible/DirigibleApplication.java
build/application/src/main/resources/logback.xml
components/core/core-base/src/main/java/org/eclipse/dirigible/components/base/artefact/ArtefactRepository.java
components/core/core-base/src/main/java/org/eclipse/dirigible/components/base/artefact/ArtefactService.java
components/core/core-base/src/main/java/org/eclipse/dirigible/components/base/artefact/BaseArtefactService.java
components/core/core-base/src/main/java/org/eclipse/dirigible/components/base/synchronizer/BaseSynchronizer.java
components/core/core-initializers/src/main/java/org/eclipse/dirigible/components/initializers/synchronizer/SynchronizationProcessor.java
components/core/core-tenants/src/main/java/org/eclipse/dirigible/components/tenants/provisioning/TenantProvisioningJob.java
components/data/data-sources/src/main/java/org/eclipse/dirigible/components/data/sources/config/TransactionsConfig.java
components/data/data-sources/src/main/java/org/eclipse/dirigible/components/data/sources/manager/DataSourceInitializer.java
components/engine/engine-bpm-flowable/pom.xml
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/config/BpmFlowableConfig.java
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/config/BpmProviderFlowableFactoryBean.java
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/delegate/DirigibleCallDelegate.java
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/provider/BpmProviderFlowable.java
components/engine/engine-jobs/src/main/java/org/eclipse/dirigible/components/jobs/SystemJob.java
components/engine/engine-jobs/src/main/java/org/eclipse/dirigible/components/jobs/config/QuartzConfig.java
components/engine/engine-jobs/src/main/java/org/eclipse/dirigible/components/jobs/handler/JobHandler.java
modules/commons/commons-config/src/main/java/org/eclipse/dirigible/commons/config/DirigibleConfig.java
pom.xml

The PR configures the transaction management in the application.
- db transactions in flowable and quartz were broken 
Flowable version is updated to latest as well. Spring boot dependencies are used instead of direct flowable dependencies.
The PR fixes issue: https://github.com/eclipse-dirigible/dirigible/issues/4755

Fix transaction management issues in the Dirigible

---

components/core/core-base/src/main/java/org/eclipse/dirigible/components/base/artefact/BaseArtefactService.java
components/core/core-base/src/main/java/org/eclipse/dirigible/components/base/synchronizer/BaseSynchronizer.java
components/core/core-base/src/main/java/org/eclipse/dirigible/components/base/synchronizer/MultitenantBaseSynchronizer.java

Fix proxy warnings like. This prevents transactions to be executed properly.

fix spring proxy warnings

---

.github/workflows/build.yml
.github/workflows/pull-request.yml
README.md
components/ide/ide-terminal/src/main/java/org/eclipse/dirigible/components/terminal/endpoint/ProcessRunnable.java
components/ide/ide-terminal/src/main/java/org/eclipse/dirigible/components/terminal/endpoint/TerminalWebsocketConfig.java
components/ide/ide-terminal/src/main/java/org/eclipse/dirigible/components/terminal/endpoint/TerminalWebsocketHandler.java

When starting Dirigible with java jar it starts ttyd in read only mode.
This PR starts it in writable mode and fixes the issue which prevents the user to type input in the terminal view.

fix terminal in mac

---

tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/framework/impl/BrowserImpl.java

Execution reduced from `32min` to `27m`

Speed up tests

---

components/data/data-import/src/main/java/org/eclipse/dirigible/components/data/export/endpoint/DataSQLEndpoint.java
components/data/data-import/src/main/java/org/eclipse/dirigible/components/data/export/service/DataImportService.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/ISqlDialect.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/DefaultSqlDialect.java

[IDE] Database - Import of Large SQL Dump Files

---

components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/dialog-window/view.extension.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/dialog-window/view.extension.template

Fixes missing dialog window in generated UI from entities with layout type Manage Master Entities and Manage Master Details. Extension files are made to use the velocity syntax.

Fix: Missing dialog window

---

components/ui/editor-monaco/src/main/resources/META-INF/dirigible/editor-monaco/js/editor.js

[IDE] #4916 Clicking 'save' does not close the file

---

components/engine/engine-camel/src/main/java/org/eclipse/dirigible/components/engine/camel/invoke/DirigibleJavaScriptInvokerImpl.java

An implementation for issue https://github.com/eclipse-dirigible/dirigible/issues/4928

Add support for async camel steps

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/records/InsertBuilder.java

Columns which have `/` are wrongly escaped which lead to invalid insert sql statements
Example: column `/BAC/ABC` becomes becomes `/"BAC"/"ABC"`

fix insert sql statements

---

components/data/data-csvim/src/main/java/org/eclipse/dirigible/components/data/csvim/processor/CsvProcessor.java
components/data/data-csvim/src/main/java/org/eclipse/dirigible/components/data/csvim/processor/CsvimProcessor.java

[CSVIM] Misleading Info Message

---

components/template/template-application-schema/src/main/resources/META-INF/dirigible/template-application-schema/data/application.schema.template

[EDM] Unique Constraint Not Set in Generated .schema File

---

components/template/template-application-schema/src/main/resources/META-INF/dirigible/template-application-schema/data/application.schema.template
components/ui/editor-entity/src/main/resources/META-INF/dirigible/editor-entity/dialogs/details.html
components/ui/editor-entity/src/main/resources/META-INF/dirigible/editor-entity/dialogs/js/details.js

[EDM] Use ComboBox Input for the Order By Property

---

tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/framework/browser/HtmlElementType.java

Add li and ul htmltypes needed for athena testing

Add li and ul needed for athena testing

---

tests/tests-integrations/src/main/java/org/eclipse/dirigible/integration/tests/ui/tests/camel/CamelAsyncStepIT.java
tests/tests-integrations/src/main/java/org/eclipse/dirigible/integration/tests/ui/tests/camel/CamelAsyncStepTestProject.java
tests/tests-integrations/src/main/resources/CamelAsyncStepIT/CamelAsyncStepIT.camel
tests/tests-integrations/src/main/resources/CamelAsyncStepIT/async-functions.ts
tests/tests-integrations/src/main/resources/CamelAsyncStepIT/async-step.ts
tests/tests-integrations/src/main/resources/CamelAsyncStepIT/project.json
tests/tests-integrations/src/main/resources/CamelAsyncStepIT/tsconfig.json

A test for https://github.com/eclipse-dirigible/dirigible/issues/4932

Add integration test for camel async step

---

components/template/template-form-builder-angularjs/src/main/resources/META-INF/dirigible/template-form-builder-angularjs/ui/index.html.template
components/ui/editor-form-builder/src/main/resources/META-INF/dirigible/editor-form-builder/js/editor.js
components/ui/platform-core/src/main/resources/META-INF/dirigible/platform-core/ui/blimpkit/blimpkit.js
components/ui/platform-core/src/main/resources/META-INF/dirigible/platform-core/ui/blimpkit/combobox.js
components/ui/platform-core/src/main/resources/META-INF/dirigible/platform-core/ui/styles/blimpkit.css

Updates the BlimpKit component library to 1.5.2.
Combobox now has a `filter` option - "StartsWith" and "Contains". See documentation for more info - https://dirigiblelabs.github.io/BlimpKit/
Also, it fixes a bug where the whole page shifts a few pixels when the combobox dropdown is shown.
#5016

[UI] Combobox input should have filter options

---

components/ui/editor-form-builder/src/main/resources/META-INF/dirigible/editor-form-builder/js/editor.js
components/ui/platform-core/src/main/resources/META-INF/dirigible/platform-core/ui/blimpkit/blimpkit.js
components/ui/platform-core/src/main/resources/META-INF/dirigible/platform-core/ui/blimpkit/combobox.js

Adds a "ContainsEach" filter option to the combobox.
#5025

[UI] Comboboxfilter type - Contains each

---

components/ui/view-databases/src/main/resources/META-INF/dirigible/view-databases/js/explorer.js

Adds the decimal scale value in the database explorer.
#4920

#4920 - Decimal scale not shown in DB perspective

---

components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/manage/dialog-window/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/detail/dialog-window/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/dialog-window/controller.js.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/main-details/controller.js.template
components/ui/perspective-processes/src/main/resources/META-INF/dirigible/perspective-processes/views/js/bpm-process-definitions.js
components/ui/perspective-processes/src/main/resources/META-INF/dirigible/perspective-processes/views/js/bpm-process-instances.js
components/ui/perspective-processes/src/main/resources/META-INF/dirigible/perspective-processes/views/js/bpm-process-jobs.js
components/ui/perspective-processes/src/main/resources/META-INF/dirigible/perspective-processes/views/js/bpm-tasks.js
tests/tests-integrations/src/main/resources/DependsOnScenariosTestProject/gen/sales-order/ui/Country/Country/City/dialog-window/controller.js
tests/tests-integrations/src/main/resources/DependsOnScenariosTestProject/gen/sales-order/ui/Country/Country/dialog-window/controller.js
tests/tests-integrations/src/main/resources/DependsOnScenariosTestProject/gen/sales-order/ui/Country/Country/main-details/controller.js
tests/tests-integrations/src/main/resources/DependsOnScenariosTestProject/gen/sales-order/ui/Customer/Customer/CustomerPayment/dialog-window/controller.js
tests/tests-integrations/src/main/resources/DependsOnScenariosTestProject/gen/sales-order/ui/Customer/Customer/dialog-window/controller.js
tests/tests-integrations/src/main/resources/DependsOnScenariosTestProject/gen/sales-order/ui/Customer/Customer/main-details/controller.js
tests/tests-integrations/src/main/resources/DependsOnScenariosTestProject/gen/sales-order/ui/Product/Product/dialog-window/controller.js
tests/tests-integrations/src/main/resources/DependsOnScenariosTestProject/gen/sales-order/ui/Product/Product/main-details/controller.js
tests/tests-integrations/src/main/resources/DependsOnScenariosTestProject/gen/sales-order/ui/SalesOrder/SalesOrder/SalesOrderItem/dialog-window/controller.js
tests/tests-integrations/src/main/resources/DependsOnScenariosTestProject/gen/sales-order/ui/SalesOrder/SalesOrder/SalesOrderPayment/dialog-window/controller.js
tests/tests-integrations/src/main/resources/DependsOnScenariosTestProject/gen/sales-order/ui/SalesOrder/SalesOrder/dialog-window/controller.js
tests/tests-integrations/src/main/resources/DependsOnScenariosTestProject/gen/sales-order/ui/SalesOrder/SalesOrder/main-details/controller.js
tests/tests-integrations/src/main/resources/DependsOnScenariosTestProject/gen/sales-order/ui/UoM/UoM/dialog-window/controller.js
tests/tests-integrations/src/main/resources/DependsOnScenariosTestProject/gen/sales-order/ui/UoM/UoM/main-details/controller.js

Fixes: #5034 
Fixes: #4792
Fixes: #4656

[EDM] Templates - Replace Alert with Notification for Entity Create/Update Events

---

components/ui/platform-core/src/main/resources/META-INF/dirigible/platform-core/ui/blimpkit/blimpkit.js
components/ui/platform-core/src/main/resources/META-INF/dirigible/platform-core/ui/blimpkit/icon-tab-bar.js
components/ui/platform-core/src/main/resources/META-INF/dirigible/platform-core/ui/styles/blimpkit.css
components/ui/platform-core/src/main/resources/META-INF/dirigible/platform-core/ui/templates/layout.html
components/ui/platform-core/src/main/resources/META-INF/dirigible/platform-core/ui/templates/splitted-tabs.html

Updated BlimpKit to the latest version and makes the tab list in the center pane scrollable.
#5038

[IDE] Make tabs scrollable

---

pom.xml

Reverts eclipse-dirigible/dirigible#5089

Revert "Bump org.webjars:bootstrap from 5.3.5 to 5.3.6"

---

components/ui/shell-ide/src/main/resources/META-INF/dirigible/shell-ide/settings/js/general.js

Automatically reloads the app after the user has reset all settings.
#5125

#5125 - Refresh app after resetting all settings

---

components/api/api-bpm/src/main/java/org/eclipse/dirigible/components/api/bpm/BpmFacade.java
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/bpm/process.ts
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/config/BpmProviderFlowable.java

[SDK] BPM - Add Support for Business Key and Business Status

---

components/api/api-log/src/main/java/org/eclipse/dirigible/components/api/log/LogFacade.java

LogFacade refactoring
- check whether log level is enabled
- parse args only when needed
- add error details on error

LogFacade refactoring

---

components/api/api-http/src/main/java/org/eclipse/dirigible/components/api/http/HttpClientFacade.java
components/resources/resources-dashboard/src/main/resources/META-INF/dirigible/dashboard/configs/bg-BG.js

[SDK] HTTP Client - Issue with large payloads

---

components/api/api-bpm/src/main/java/org/eclipse/dirigible/components/api/bpm/BpmFacade.java
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/bpm/index.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/bpm/process.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/bpm/tasks.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/bpm/values.ts
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/config/BpmProviderFlowable.java

Add functionality for correlateMessageEvent to BPMFacade

Add correlateMessageEvent to BPMFacade

---

components/ui/perspective-processes/src/main/resources/META-INF/dirigible/perspective-processes/views/js/bpm-process-instances.js

Fixes wrong error message in the skip response
#5132

#5132 - Skip doesn't work for user tasks

---

components/api/api-bpm/src/main/java/org/eclipse/dirigible/components/api/bpm/BpmFacade.java
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/config/BpmProviderFlowable.java

Allow correlateMessageEvent with processInstanceId

Allow correlateMessageEvent with processInstanceId
