eclipse-dirigible/dirigible

org.eclipse.dirigible/org.eclipse.dirigible.parent/runtime/org.eclipse.dirigible.runtime.core.test/src/org/eclipse/dirigible/runtime/scripts/XMLUtilsTest.java

The XMLUtilsTest must not depend on specific ordering of the elements.
Signed-off-by: Svetlin Zarev <svetlin.zarev@sap.com>

Fix the build for java 8

---

api/api-facades/api-core/src/main/java/org/eclipse/dirigible/api/v3/core/JavaFacade.java
modules/commons-api/src/main/java/org/eclipse/dirigible/commons/api/context/ThreadContextFacade.java

The long type provides wide enough namespace for unique IDs
and the AtomicLong type provides faster way to generate unique
object IDs than the UUID class.

Use AtomicLong for object ID generation.

---

modules/database/database-persistence/src/main/java/org/eclipse/dirigible/database/persistence/model/PersistenceTableModel.java
modules/database/database-persistence/src/main/java/org/eclipse/dirigible/database/persistence/model/PersistenceTableRelationModel.java

Added additional logic in the PersistenceModels in order to use them for the oData mappings:
-PersistenceTableRelationModel in order to store the relations between tables later used in the creation of odataM and odataX files.

Enhanced persistence models 

---

modules/repository/repository-zip/src/main/java/org/eclipse/dirigible/repository/zip/RepositoryZipImporter.java

Signed-off-by: km2k <k.momchev@abv.bg>
Fix for Windows-style paths in Zip import functionality
https://github.com/eclipse/dirigible/issues/505

Fix in paths for Windows for Zip importer

---

pom.xml

Signed-off-by: borisnen <26414287+BorisNen@users.noreply.github.com>
Downgrades jackson-databind's version from 2.11.1 to 2.10.5.1. This is an inner dependency of "cxf-rt-rs-service-description-swagger". Downgrade is necessary for future Apache Spark integration since the official Spark release works only with jackson-databind < 2.11.1.
None

Downgraded jackson-databind to 2.10.5.1 for Apache Spark integration

---

releng/desktop-all/pom.xml

Signed-off-by: Nenchovski <26414287+BorisNen@users.noreply.github.com>
Removes an unnecessary slash for accessing the target directory and copying ROOT.war from desktop-all to CATALINA_HOME. The slash prevented the war copying on MacOS.
None

Removed redundant slash that was preventing the copying of the war

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/mysql/MySQLCreateBranchingBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/mysql/MySQLCreateViewBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/postgres/PostgresCreateViewBuilder.java

Introduces implementation logic for these [integration tests](https://github.com/SAP/xsk/issues/168).
It appears that for postgresql, only table/view names should be escaped solely. Other properties should not be escaped.
The following sql is a good working example:
```sql
CREATE VIEW "hdbview-itest::SamplePostgreXSClassicViewppp" AS SELECT T1.Column2 FROM "public"."acme.com.test.tables::MY_TABLE1" AS T1 LEFT JOIN "public"."acme.com.test.views::MY_VIEW1" AS T2 ON T1.Column1 = T2.Column1;
```
For MySQL, the proper [escaping symbol](https://github.com/eclipse/dirigible/issues/850) is considered.

PostgreCreateViewBuilder & MySQLCreateViewBuilder adapted for xsk hdbview

---

api/api-facade/api-http/src/main/java/org/eclipse/dirigible/api/v3/http/HttpSessionFacade.java
api/api-facade/api-security/src/main/java/org/eclipse/dirigible/api/v3/security/UserFacade.java
api/api-javascript/api-security/src/main/resources/security/v4/user.js

Adds UserFacade methods that are necessary for the implementation of the language member and the getInvocationCount method in session API in the xsk project. Improves previous Session API methods. Adds a counter to the getSession method inside HttpSessionFacade.
This PR is related to two different issues inside the xsk project - https://github.com/SAP/xsk/issues/218 and https://github.com/SAP/xsk/issues/219
Documentation will be provided inside the xsk wiki.

Session API - added language and invocation count methods. Improved previous methods.

---

modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/transformers/DBMetadataUtil.java
modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/transformers/OData2ODataMTransformer.java
modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/transformers/OData2ODataXTransformer.java
modules/engines/engine-odata/src/test/java/org/eclipse/dirigible/engine/odata2/transformers/OData2ODataMTransformerTest.java
modules/engines/engine-odata/src/test/java/org/eclipse/dirigible/engine/odata2/transformers/OData2ODataXTransformerTest.java

Continue on issue: https://github.com/eclipse/dirigible/issues/958
When there is a synonyms with the same names as the entities, they need to be search from the DB by the scheme.

odata load artifacts for a specific schema

---

api/api-facade/api-http/src/main/java/org/eclipse/dirigible/api/v3/http/HttpUploadFacade.java
api/api-javascript/api-http/src/main/resources/http/v4/upload.js

Adds a method to the `HttpUploadFacade` that transforms header names iterator into header names list. Also adds methods to the `upload` js api to get the multipart child requests headers.
This PR is related to an issue from the XSK project SAP/xsk#22
https://www.dirigible.io/api/http/upload/

Upload API - getting multipart request headers.

---

ide/ui/ide-database/src/main/resources/ide-database/explorer/explorer.html
ide/ui/ide-debugger/src/main/resources/ide-debugger/views/debugger/index.html
ide/ui/ide-git/src/main/resources/ide-git/git/git.html
ide/ui/ide-git/src/main/resources/ide-git/git/history.html
ide/ui/ide-git/src/main/resources/ide-git/git/staging.html
ide/ui/ide-registry/src/main/resources/ide-registry/registry.html
ide/ui/ide-repository/src/main/resources/ide-repository/repository.html
ide/ui/ide-workspace/src/main/resources/ide-workspace/search.html
ide/ui/ide-workspace/src/main/resources/ide-workspace/workspace.html
resources/resources-all/pom.xml

Currently, with jstree 3.3.4 the build fails on windows with the following error:
```
[ERROR] Failed to execute goal on project dirigible-resources: Could not resolve dependencies for project org.eclipse.dirigible:dirigible-resources:jar:5.12.9: Failed to collect dependencies at org.webjars.npm:jstree:jar:3.3.4 -> org.webjars.npm:jquery:jar:3.3.0 -> org.webjars.npm:npm:jar:4.4.1 -> org.webjars.npm:npm-registry-client:jar:7.4.6 -> org.webjars.npm:semver:jar:2- >=2.2.1,[3,4),[4,5),[5,6): Failed to read artifact descriptor for org.webjars.npm:semver:jar:2- >=2.2.1,[3,4),[4,5),[5,6): Could not transfer artifact org.webjars.npm:semver:pom:2- >=2.2.1,[3,4),[4,5),[5,6) from/to mvnrepository (https://repo1.maven.org/maven2): C:\Users\IVO\.m2\repository\org\webjars\npm\semver\2- …
```

fix: updates jstree due to windows build errors

---

modules/repository/repository-local/src/main/java/org/eclipse/dirigible/repository/local/LocalRepositoryDao.java

The way that the cache currently works - it sometimes uses Dirigible workspace paths, other times it uses local file system paths.
This PR unifies the behavior to always use the workspace path.
Related to: https://github.com/eclipse/dirigible/issues/812

fix: use workspace path for caching.

---

resources/resources-theme-default/src/main/resources/META-INF/dirigible/theme-default/dropdown.css
resources/resources-theme-fiori/src/main/resources/META-INF/dirigible/theme-fiori/dropdown.css

This PR adds CSS styles for dropdown_btn used in xsk-ide-migration.
It's part of the solution for [https://github.com/SAP/xsk/issues/472](https://github.com/SAP/xsk/issues/472) issue.

css styles

---

modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/EdmUtils.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLQuery.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/expression/SQLExpressionDelete.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/expression/SQLExpressionUpdate.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/expression/SQLExpressionUtils.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/AbstractSQLProcessor.java
modules/odata/odata-core/src/test/java/org/eclipse/dirigible/engine/odata2/sql/ODataSQLProcessorTest.java
modules/odata/odata-core/src/test/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLQueryTest.java

Fixes an issue with delete entity where the genereated SQL contains the Entity property names instead of the table column names

Fix Delete Entities

---

modules/engines/engine-javascript-graalvm/src/main/java/org/eclipse/dirigible/engine/js/graalvm/processor/GraalVMJavascriptEngineExecutor.java

beforeEval should be called between require/module initialisation and module loading / script evaluation

Move beforeEval after require initialisation

---

modules/database/database-data-models/src/main/java/org/eclipse/dirigible/database/ds/model/DataStructureTableIndexModel.java
modules/database/database-data-models/src/main/java/org/eclipse/dirigible/database/ds/model/DataStructureTableModel.java
modules/database/database-data-models/src/main/java/org/eclipse/dirigible/database/ds/model/processors/TableCreateProcessor.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/ISqlKeywords.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/CreateBranchingBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/table/AbstractTableBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/table/CreateTableBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/table/CreateTableIndexBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/table/CreateTableUniqueIndexBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/hana/HanaCreateBranchingBuilder.java
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/hana/HanaCreateTableBuilder.java
modules/database/database-sql/src/test/java/org/eclipse/dirigible/database/sql/test/hana/CreateTableTest.java

- Creation of ROW table type is now possible for Hana DB
- Creation of unique and non-unique indexes is now possible. Index properties are now taken into account as well
.hdbtable indeces type in not taken into account #1270
.hdbtable tableType is not taken into account #1271

adding support for Hana Row table and indexes creation

---

ide/ui/ide-workspace/src/main/resources/META-INF/dirigible/ide-workspace/workspace.js

Added `Dirigible-Editor: Workspace` header to the file upload of the ide workspace as `.xsodata` artifact couldn't be uploaded.

Added dirigible editor header for workspace file upload

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/builders/table/AlterTableBuilder.java

Adding overloaded unique() method in AlterTableBuilder

overloading unique() methodin AlterTableBuilder

---

modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/dialects/h2/H2NextValueSequenceBuilder.java

This PR fixes NextValueSequenceBuilder for the H2 database by removing encapsulate on generated sequence id name.
Resolves #1312

Remove encapsulate generated sequence name

---

modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/transformers/DBMetadataUtil.java
modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/transformers/OData2ODataXTransformer.java
modules/engines/engine-odata/src/test/java/org/eclipse/dirigible/engine/odata2/transformers/OData2ODataXTransformerTest.java
modules/engines/engine-odata/src/test/resources/transformers/EmployeeSynonym.odata

Resolves #1295 
`OData2ODataXTransformer` check if the defined entity is synonym and in case it is uses the target object of the synonym for further processing.

Allow xsodata entity definition use synonym

---

modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/transformers/DBMetadataUtil.java
modules/engines/engine-odata/src/test/java/org/eclipse/dirigible/engine/odata2/transformers/DBMetadataUtilTest.java

Resolves #1329
Changes:
1. Add support for NCLOB, CLOB, TEXT, BINTEXT, ALPHANUM data types in the OData Framework
2. Improve error handling in case of unknown data type

Add missing HANA Cloud data types to the OData framework.

---

modules/core/core-scheduler/src/main/java/org/eclipse/dirigible/core/scheduler/api/AbstractSynchronizer.java
modules/database/database-data-structures/src/main/java/org/eclipse/dirigible/database/ds/artefacts/SchemaSynchronizationArtefactType.java

Method "applyArtefactState" overloading in AbstractSynchronizer class

overloading applyArtefactState required by XSK

---

releng/anonymous-all/src/main/resources/logback.xml
releng/anonymous-runtime/src/main/resources/logback.xml
releng/desktop-all/src/main/resources/logback.xml
releng/openshift-all/src/main/resources/logback.xml
releng/sap-all-ephemeral/src/main/resources/logback.xml
releng/sap-all/src/main/resources/logback.xml
releng/sap-cf-base/src/main/resources/logback.xml
releng/sap-cms/src/main/resources/logback.xml
releng/sap-kyma-base/src/main/resources/logback.xml
releng/sap-runtime-ephemeral/src/main/resources/logback.xml
releng/server-all/src/main/resources/logback.xml
releng/server-keycloak-all/src/main/resources/logback.xml
releng/server-minimal/src/main/resources/logback.xml
releng/server-oauth/src/main/resources/logback.xml
releng/server-runtime-keycloak/src/main/resources/logback.xml
releng/server-runtime/src/main/resources/logback.xml
releng/trial-all/src/main/resources/logback.xml

Fixes: https://github.com/eclipse/dirigible/issues/651
This PR configures the logback.xml files to use the following environment variables for logs output:
1. DIRIGIBLE_LOGS_DIR
2. CATALINA_BASE
3. CATALINA_HOME
The variable to be used, if several of those exist, would be the first one found in the same order as in the list above.
If none of those variables exist, logs would be output the same way as before this PR - relative to the folder where the tomcat was started.

fix: reconfigure logback.xml file appenders path

---

modules/commons/commons-api/src/main/java/org/eclipse/dirigible/commons/api/context/ThreadContextFacade.java

Fixes: https://github.com/eclipse/dirigible/issues/1439
This PR sets newly created stacks to have their parent's stack as their own one in order for the `get` methods to have access to their parent's objects. 
Although this could be implemented by modifying the `get` method to lookup into parent stacks and use a bit less memory, it would be computationally heavier as the `get` methods are called often.

feat: keep parent stack objects in new stacks

---

modules/odata/odata-core-test/src/main/java/org/eclipse/dirigible/engine/odata2/sql/AbstractSQLProcessorTest.java
modules/odata/odata-core-test/src/main/java/org/eclipse/dirigible/engine/odata2/sql/OData2RequestBuilder.java
modules/odata/odata-core-test/src/test/java/org/eclipse/dirigible/engine/odata2/sql/ODataSQLProcessorTest.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/AbstractSQLProcessor.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/DefaultSQLProcessor.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/utils/SingleConnectionDataSource.java

Provides support for transactions and batching #1282 #843 
Closes #1282 
Closes #843
Note: If you want to use transactions for customer operations, you can use a custom data source that uses only one connection, set auto-commit false on the connection perform the requests and then commit the transaction. The class org.eclipse.dirigible.engine.odata2.sql.utils.SingleConnectionDataSource  can be used for that purpose in custom code.
This approach is very similar to how the changesets in the batch support are implemented. 
Support for batching and transactions. Added unit tests.

Initial support for OData batching

---

api/api-javascript/api-bpm/src/main/resources/META-INF/dirigible/bpm/extensions/bpm.d.ts
api/api-javascript/api-bpm/src/main/resources/META-INF/dirigible/bpm/extensions/modules.json
api/api-javascript/api-core/src/main/resources/META-INF/dirigible/core/extensions/core.d.ts
api/api-javascript/api-core/src/main/resources/META-INF/dirigible/core/extensions/modules.json
modules/engines/engine-javascript-graalvm/src/test/resources/META-INF/dirigible/graalvm/ecmascript/relativeImports/l11/l11_with_dirigible_import.mjs
modules/engines/engine-javascript-graalvm/src/test/resources/META-INF/dirigible/graalvm/ecmascript/relativeImports/l12/l12.mjs

Fixes: https://github.com/eclipse/dirigible/issues/1447
This PR adds:
- Test for the case of import of a file from a sibling folder that has a `@dirigible` import inside of it
- Add `modules.json` for the `api-bpm` module
- Add empty `bpm.d.ts` file for the `api-bpm` module (this and other `d.ts` files would be updated at a later point)

fix: add modules.json and add test for sibling imports with dirigible imports

---

api/api-facade/api-git/src/main/java/org/eclipse/dirigible/api/v4/git/GitFacade.java

GitFacade.getGitRepositories should return only projects with initialized repositories.

Fix getGitRepositories returning projects without git repos

---

modules/repository/repository-zip/src/main/java/org/eclipse/dirigible/repository/zip/RepositoryZipImporter.java
modules/services/service-transport/src/main/java/org/eclipse/dirigible/runtime/transport/processor/TransportProcessor.java
modules/services/service-transport/src/main/java/org/eclipse/dirigible/runtime/transport/service/TransportProjectRestService.java

Fixes: https://github.com/eclipse/dirigible/issues/1483
This PR adds support for importing zips into a given path which would be treated as relative to the Repository root path.
The new endpoint is a POST to `/project?path=/some/path/relative/to/the/repository/root`

feat: support importing zips into a given path

---

modules/core/core-git/src/main/java/org/eclipse/dirigible/core/git/GitConnectorFactory.java
modules/core/core-git/src/main/java/org/eclipse/dirigible/core/git/command/CloneCommand.java
modules/core/core-git/src/main/java/org/eclipse/dirigible/core/git/command/ShareCommand.java

Fixes: https://github.com/eclipse/dirigible/issues/1457
Currently, we get the default repository branch by checking the HEAD. This is not necessary as stated in the JGit docs: https://archive.eclipse.org/jgit/site/4.5.0.201609210915-r/apidocs/org/eclipse/jgit/api/CloneCommand.html#setBranch-java.lang.String-

fix: change how we clone projects without a specified branch

---

api/api-facade/api-core/src/main/java/org/eclipse/dirigible/api/v3/core/ExecFacade.java
api/api-facade/api-core/src/test/java/org/eclipse/dirigible/api/v3/core/test/ExecFacadeTest.java
modules/commons/commons-process/pom.xml
modules/commons/commons-process/src/main/java/org/eclipse/dirigible/commons/process/execution/DefaultProcessExecutor.java
modules/commons/commons-process/src/main/java/org/eclipse/dirigible/commons/process/execution/ErrorsRedirectProcessExecutor.java
modules/commons/commons-process/src/main/java/org/eclipse/dirigible/commons/process/execution/ProcessExecutionException.java
modules/commons/commons-process/src/main/java/org/eclipse/dirigible/commons/process/execution/ProcessExecutionFuture.java
modules/commons/commons-process/src/main/java/org/eclipse/dirigible/commons/process/execution/ProcessExecutor.java
modules/commons/commons-process/src/main/java/org/eclipse/dirigible/commons/process/execution/output/OutputsPair.java
modules/commons/commons-process/src/main/java/org/eclipse/dirigible/commons/process/execution/output/ProcessResult.java
modules/engines/engine-command/src/main/java/org/eclipse/dirigible/engine/command/processor/CommandEngineExecutor.java
pom.xml

Related to: https://github.com/eclipse/dirigible/issues/1491 and https://github.com/SAP/xsk/issues/1120
Currently, the ExecFacade uses a process executor that combines the error and out streams. This is not desired in some cases. The current process executor API is not easily extendable and would need some refactoring to support this. 
This PR proposes a new API for executing command-line programs with the idea of extending it over time for our needs. An advantage of this API is that it returns a Future. This would allow us at a later point to support the `async/await` style in JS if we want to. 
One current disadvantage of it is that it doesn't support timeouts. This could easily be supported as the Apache Exec has the notion of watchdogs that could do the work.

feat: add new process executor and change ExecFacade implementation

---

modules/bpm/bpm-flowable/src/main/java/org/eclipse/dirigible/bpm/flowable/DirigibleCallDelegate.java
modules/engines/engine-api/src/main/java/org/eclipse/dirigible/engine/api/script/IScriptEngineExecutor.java
modules/engines/engine-api/src/main/java/org/eclipse/dirigible/engine/api/script/ScriptEngineExecutorsManager.java
modules/engines/engine-command/src/main/java/org/eclipse/dirigible/engine/command/processor/CommandEngineExecutor.java
modules/engines/engine-javascript-graalvm/src/main/java/org/eclipse/dirigible/engine/js/graalvm/processor/GraalVMJavaScriptContextBuilder.java
modules/engines/engine-javascript-graalvm/src/main/java/org/eclipse/dirigible/engine/js/graalvm/processor/GraalVMJavascriptEngineExecutor.java
modules/engines/engine-javascript/src/main/java/org/eclipse/dirigible/engine/js/processor/DefaultJavascriptEngineExecutor.java

Currently, the BPMN engine in Dirigible supports only executing scripts. This PR enables execution of ES6 modules with a provided `className/methodName` pair or a `methodName`.

feat: support bpmn mjs class and method execution

---

modules/odata/odata-core-test/src/test/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLSelectBuilderComplexTypeTest.java
modules/odata/odata-core-test/src/test/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLSelectBuilderExpandTest.java
modules/odata/odata-core-test/src/test/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLSelectBuilderNavigationPropertiesTest.java
modules/odata/odata-core-test/src/test/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLSelectBuilderTest.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLQueryBuilder.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLSelectBuilder.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/clause/SQLOrderByClause.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/clause/SQLSelectClause.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/AbstractSQLProcessor.java

Fix for #1555 
Change log:
1. **$skip** is now implemented with OFFSET for all DBs
2. **$top** is now implemented with LIMIT for all DBs
3. remove requirement for support of ResultSet **TYPE_SCROLL_INSENSITIVE** by the DB drivers

[OData] Improve skip/offset logic

---

modules/odata/odata-core-test/src/test/java/org/eclipse/dirigible/engine/odata2/sql/clause/SQLOrderByClauseTest.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/clause/SQLOrderByClause.java

Handle OData default order by when there is no primary keys

---

api/api-facade/api-platform/src/main/java/org/eclipse/dirigible/api/v3/platform/RepositoryFacade.java
groups/ide-services-all/pom.xml
ide/services/ide-editor/pom.xml
ide/services/ide-editor/src/main/java/org/eclipse/dirigible/runtime/ide/editor/services/EditorRestService.java
ide/services/ide-editor/src/main/resources/META-INF/services/org.eclipse.dirigible.commons.api.service.IRestService
ide/services/pom.xml
ide/ui/ide-monaco/src/main/resources/META-INF/dirigible/ide-monaco/editor.html
ide/ui/ide-monaco/src/main/resources/META-INF/dirigible/ide-monaco/js/editor.js
modules/services/service-repository/pom.xml
modules/services/service-repository/src/main/java/org/eclipse/dirigible/runtime/repository/processor/RepositoryProcessor.java

* Prettier standalone is now registered as a custom formatter in monaco editor (in the browser) to format `.js` files.
* Added a new rest service for ide releated features.
* `.prettierrc.json` files are supported as configuration files.
* When you save a javascript file formatting occurs, the closest .prettierrc.json file in a bottom-up 
traversal of the folder structure is used as a formatting configuration.

feat: add prettier formatting support

---

modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/transformers/DefaultPropertyNameEscaper.java
modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/transformers/OData2ODataMTransformer.java
modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/transformers/OData2ODataXTransformer.java
modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/transformers/ODataMetadataUtil.java
modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/transformers/ODataPropertyNameEscaper.java
modules/engines/engine-odata/src/test/java/org/eclipse/dirigible/engine/odata2/transformers/DefaultPropertyNameEscaperTest.java
modules/engines/engine-odata/src/test/java/org/eclipse/dirigible/engine/odata2/transformers/OData2ODataMTransformerTest.java

Introduce OData property name escaper, so that different implementation can be supplied for different requirements.

Introduce OData property name escaper

---

modules/engines/engine-javascript-graalvm/src/main/java/org/eclipse/dirigible/engine/js/graalvm/callbacks/Require.java
modules/engines/engine-javascript-graalvm/src/main/java/org/eclipse/dirigible/engine/js/graalvm/processor/GraalVMJavascriptEngineExecutor.java
modules/engines/engine-javascript-graalvm/src/main/resources/Module.js
modules/engines/engine-javascript/src/main/java/org/eclipse/dirigible/engine/js/service/ScriptingDependencyExceptionHandler.java

This PR changes several things:
- Throw a `ScriptingException` if there is an exception while evaluating JS code
- Return 500 from the REST service if there is a `ScriptingException`
- Do not `eval` source code as string
- Use GraalVM's `load` instead of `eval` in order to provide a file name of the code being loaded
Fixes: https://github.com/SAP/xsk/issues/1461
Fixes: https://github.com/SAP/xsk/issues/646

fix: return 500 for js errors and fix eval file names

---

ext/ext-api/api-spark/pom.xml
pom.xml

Set Jackson Databind version to 2.13.2.2 to fix security vulnerability

Jackson Databind version 2.13.2.2

---

pom.xml

Jetty 11 uses the Servlet 5.0 API and it doesn't work on Tomcat 8.

revert: use jetty 9 for servlet 4.0 spec

---

modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/transformers/OData2ODataMTransformer.java
modules/engines/engine-odata/src/test/java/org/eclipse/dirigible/engine/odata2/transformers/OData2ODataMTransformerTest.java
modules/engines/engine-odata/src/test/resources/view/View.odata
modules/odata/odata-api/src/main/java/org/eclipse/dirigible/engine/odata2/definition/ODataEntityDefinition.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/AbstractQueryBuilder.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/clause/SQLSelectClause.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/AbstractSQLProcessor.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/ResultSetReader.java

Related to https://github.com/SAP/xsk/issues/1444
Changelog:
1. ODataEntityDefinition now has a separate field for generated keys.
2. OData2ODataMTransformer now checks the keyGenerated field and adds it to the json.
3. SQLSelectClause will add HANA's row_num value to the select clause when we have keyGenerated in the table binding.
4. AbstractSQLProcessor now builds two different ResultSetEntities - one that uses the table keys for entities and one that uses the row_num values as key when we have a HANA view.

OData now uses row_num value as ID for HANA views

---

api/api-facade/api-mail/src/main/java/org/eclipse/dirigible/api/v3/mail/ConnectivitySocks5ProxySocket.java
api/api-facade/api-mail/src/main/java/org/eclipse/dirigible/api/v3/mail/MailClient.java

The ConnectivitySocks5ProxySocket class is a modified version of the one taken from [here](https://help.sap.com/docs/CP_CONNECTIVITY/cca91383641e40ffbe03bdc78f00f681/cd1583775afa43f0bb9ec69d9dbcc880.html). The changes allow for username/password authentication to the proxy server instead of JWT and are required since authentication on Kyma is done so.
closes #1718

Enable connection to on-premise mail server via SOCKS5 proxy

---

modules/repository/repository-zip/src/main/java/org/eclipse/dirigible/repository/zip/RepositoryZipImporter.java

When importing zip, created in mac os, there are some files added by os. This pr excludes these unused files to be imported.

remove internal macos folders and files when importing project from zip

---

modules/core/core-scheduler/src/main/java/org/eclipse/dirigible/core/scheduler/service/definition/SynchronizerStateArtefactDefinition.java

Truncate SYNCHRONIZER_ARTEFACT_MESSAGE
Messages stored by the artefact synchroniser could be too long. Thats why we store only the first 512 characters. 
Fixes: https://github.com/sap/xsk/issues/1326

Truncating synchroniser artefact message because it could be too long

---

modules/odata/odata-core-test/src/test/java/org/eclipse/dirigible/engine/odata2/sql/clause/SQLWhereClauseTest.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/builder/SQLUtils.java
modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/clause/SQLWhereClauseVisitor.java

Fixes #1781 
Current behaviour is that $filter=LastName eq null is transformed to WHERE LastName = null SQL which is incorrect SQL for working with NULL predicate.
With this PR **IS NULL/IS NOT NULL** will be used in the SQL when you have OData filter with right side of type Edm.Null

Fix odata filter with null predicate

---

api/api-facade/api-http/src/main/java/org/eclipse/dirigible/api/v3/http/HttpClientFacade.java

It was detected CSV was recognised as text while processing client responses in HTTP client facade. 
This PR adds CSV content types.
Detected while working on fix https://github.com/SAP/xsk/issues/1585

Treat CSV as text in client facade

---

ide/ui/ide-monaco/src/main/resources/META-INF/dirigible/ide-monaco/js/editor.js

Monaco context menu has a new action that is initially labeled 'Disable Auto-Formatting'.
When you click it the current file is added to a list of files with disabled auto formatting in the localStorage.
Upon the next context menu open for the same file the action is labeled 'Enable Auto-Formatting'.
On save if the file is in the localStorage's list of files with disabled auto formatting => no auto formatting is done to the content before save.
The action is bound to `Cmd/Ctrl + Shift + D` in the editor and you can cleanup any configurations for files with disabled auto formatting by using the 'Reset Theme' button.

feat: add disable auto-formatting toggle in monaco context menu

---

ext/ext-api/api-redis/pom.xml

This PR excludes the `org.json:json` library from the build. This library is distributed under the JSON license which includes field of use restrictions that are not compatible with the project license.
The tests all pass with this exclusion, but I am not familiar enough with the project to understand if removing this library will result in any runtime failures.

Exclude org.json:json

---

modules/engines/engine-graalium/execution/src/main/java/org/eclipse/dirigible/graalium/core/graal/GraalJSFileSystem.java

Adds support for importing ESM modules from other projects:
```JS
import { someExportedMember } from "/project-name/module-name.mjs"
```
Is it according to the specification?
> The module specifier provides a string that the JavaScript environment can resolve to a path to the module file. In a browser, this could be a path relative to the site root, which for our basic-modules example would be /js-examples/module-examples/basic-modules. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules
In our case, the root is the public registry directory.

feat: support absolute path imports from projects root

---

components/ide-ui-generate-service/src/main/resources/META-INF/dirigible/ide-generate-service/template/generateUtils.js
components/ide-ui-generate-service/src/main/resources/META-INF/dirigible/ide-generate-service/template/parameterUtils.js
components/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/template/ui/masterDetailsList.js
components/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/template/ui/masterDetailsManage.js
components/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/launchpad/Home/view.extension
components/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/launchpad/Home/view.js
components/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/index.html
components/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/detail/controller.js.template
components/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/detail/dialog-window/view.extension
components/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/detail/view.extension
components/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/detail/controller.js.template
components/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/detail/dialog-window/view.extension
components/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/detail/view.extension

Fixes:
- #2816
New fields to be added in the `*.model` file per entity:
- `referencedProjectionProjectName` - the project name of the referenced entity
- `referencedProjectionPerspectiveName` - the name of the perspective, which contains the referenced entity
```json
{
"model": {
"entities": [
{
"properties": [
...
],
"layoutType": "MANAGE_DETAILS",
"type": "DEPENDENT",
"referencedProjectionProjectName": "main",
"referencedProjectionPerspectiveName": "entities"
}
]
}
}
```
**Note:** In the sample the project that's being extended is `main` and the perspective, which contains the entity that's being extended is `entities`.

[Templates] Add Support for Contributing Details Entity

---

components/ide-ui-documents/src/main/resources/META-INF/dirigible/ide-documents/ui/documents/index.html
components/ide-ui-documents/src/main/resources/META-INF/dirigible/ide-documents/ui/documents/js/controllers.js

Introduces a function in the document perspective preview, that checks if the selected file type can be previewed and warns the user.
#2820

#2820 - Selecting a CSV file start "download" instead of "preview"

---

components/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/css/styles.css
components/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/modeler.html

Moves the resizing buttons in  the top toolbar.
Wide screen:
Narrow screen:
#2876

[IDE] #2876 - Move resizing buttons in the top toolbar

---

components/ide-ui-monaco/src/main/resources/META-INF/dirigible/ide-monaco/api/extensions/core.js
components/ide-ui-monaco/src/main/resources/META-INF/dirigible/ide-monaco/js/editor.js

Example Dirigible project setup:
1. Create some project
2. Add `index.tsx`:
``` TypeScript
import React from "https://esm.sh/react@18.2.0";
import ReactDOM from "https://esm.sh/react-dom@18.2.0";
function App() {
return (
<div>Hello, React!!! </div>
);
}
ReactDOM.render(<App />, document.getElementById("root"));
```
3. Add `project.json`:
``` JSON
{
"guid": "some_project_id",
"actions": [
{
"name": "Build",
"command": "esbuild index.tsx --bundle --outfile=public/index.js --loader:.js=jsx --format=esm",
"publish": "true"
}
]
}
```
4. Add folder `public`
5. Add file `public/index.html`:
``` HTML
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Hello, React!</title>
</head>
<body>
<div …
```

feat: initial react support

---

components/api/api-modules-javascript/pom.xml
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/build-source.sh
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/http/decorators.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/http/index.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/http/rs/resource-http-controller.ts

The following should work in both ESM and TS files:
``` TypeScript
import { Controller, Get, Post } from "@dirigible/http"
// or if you use the CJS modules support
// const { Controller, Get, Post } = require("http/v4/rs/decorators");
@Controller
class MyApi {
@Get("/")
onGet() {
return "Hello there!";
}
@Post("/")
onPost(body) {
return {
some: "data"
}
}
}
```

fix: decorators module rename and default exports, fix rs arrow function args

---

components/engine/engine-jobs/src/main/java/org/eclipse/dirigible/components/jobs/handler/JobHandler.java

```
2023-12-05 14:30:00.145 [ERROR] [schedulerFactoryBean_Worker-2] o.e.d.c.jobs.handler.JobHandler - Failed to execute JS. Job name [synchronize], handler[ide-documents/security/synchronize.js]
org.graalvm.polyglot.PolyglotException: TypeError: cmis.getSession is not a function
at <js>.:anonymous(ide-documents/utils/cmis/object:13) ~[na:na]
at <js>.:anonymous(ide-documents/utils/cmis/document:14) ~[na:na]
at <js>.:anonymous(ide-documents/api/processors/constraintsProcessor:13) ~[na:na]
at <js>.:module:eval(synchronize.js:12) ~[na:na]
at org.graalvm.polyglot.Context.eval(Context.java:402) ~[polyglot-23.1.1.jar:na]
at org.eclipse.dirigible.graalium.core.javascript.GraalJSCodeRunner.run(GraalJSCodeRunner.java:149) ~[classes/:na]
at …
```

improve jobhandler error logging

---

README.md
modules/commons/commons-config/src/main/java/org/eclipse/dirigible/commons/config/Configuration.java
modules/commons/commons-config/src/test/java/org/eclipse/dirigible/commons/config/ConfigurationTest.java

example config property: `jdbc:mariadb://${PORTUNUS_OPENCART_DB_HOST}:${PORTUNUS_OPENCART_DB_PORT}/${PORTUNUS_OPENCART_DB_NAME}`

Support more complex placeholders in config files

---

components/engine/engine-listeners/src/main/java/org/eclipse/dirigible/components/listeners/service/ListenerManager.java

Configure default redelivery policy for all listeners.
An example execution of the handlers with this configuration:
```
2024-01-11 13:29:35.496 [INFO ] [ActiveMQ Session Task-1] app.out - ### Handler Execution
2024-01-11 13:29:36.634 [INFO ] [ActiveMQ Session Task-1] app.out - ### Handler Execution
2024-01-11 13:29:41.741 [INFO ] [ActiveMQ Session Task-1] app.out - ### Handler Execution
2024-01-11 13:30:06.824 [INFO ] [ActiveMQ Session Task-1] app.out - ### Handler Execution
```
@delchev consider to extend the `.listener` spec with configurations for redelivery

Configure ActiveMQ redelivery policy

---

components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/integrations/index.ts
components/data/data-sources/src/main/java/org/eclipse/dirigible/components/data/sources/service/DataSourceLifecycleListener.java
components/engine/engine-camel/src/main/java/org/eclipse/dirigible/components/engine/camel/invoke/IntegrationMessage.java
components/engine/engine-camel/src/main/java/org/eclipse/dirigible/components/engine/camel/invoke/Invoker.java
components/engine/engine-camel/src/main/java/org/eclipse/dirigible/components/engine/camel/processor/CamelProcessor.java
tests/src/test/java/org/eclipse/dirigible/integration/tests/services/integrations/CamelPlatformHttpTest.java
tests/src/test/resources/META-INF/dirigible/camel_test/calledFromCamel.js
tests/src/test/resources/META-INF/dirigible/camel_test/calledFromCamel.mjs
tests/src/test/resources/META-INF/dirigible/camel_test/test-routes.camel
tests/src/test/resources/META-INF/dirigible/modules-tests/src/services/integrations/dirigible-js-to-camel-route-test.js

- Modified JS invoker to return response to any invoking camel routes.
- Adds an integration test which calls a PlatformHttp route, which in turn provides the payload to a dirigible js script that forms a response.
- Adds an integration test which from a dirigible js script calls a camel direct route via the js api that forms a response.
- Dirigible code runner closes context after route completes when camel invokes dirigible js/mjs/ts files

feat: Add integration tests for Camel PlatformHTTP and @dirigible/integrations API

---

components/data/data-sources/src/main/resources/META-INF/dirigible/datasources/SystemDB.datasource

When you are using env variables like the following:
```
export DIRIGIBLE_DATABASE_SYSTEM_URL='jdbc:h2:file:/Users/iliyan/work/dirigible-work-dir/h2/SystemDB'
export DIRIGIBLE_DATABASE_SYSTEM_USERNAME='admin'
export DIRIGIBLE_DATABASE_SYSTEM_PASSWORD='admin'
```
Tables are not shown in the UI

fix SystemDB visualization when using env variable

---

components/api/api-database/src/main/java/org/eclipse/dirigible/components/api/db/DatabaseFacade.java
components/data/data-export/src/main/java/org/eclipse/dirigible/components/data/export/endpoint/DataExportEndpoint.java
components/data/data-export/src/main/java/org/eclipse/dirigible/components/data/export/service/DataExportService.java
components/data/data-export/src/test/java/org/eclipse/dirigible/components/data/export/endpoint/DataExportEndpointTest.java
components/data/data-export/src/test/java/org/eclipse/dirigible/components/data/export/service/DataExportServiceTest.java
components/ide/ide-ui-database/src/main/resources/META-INF/dirigible/ide-database/explorer/explorer.js
components/ide/ide-ui-result/src/main/resources/META-INF/dirigible/ide-result/js/result.js
modules/database/database-sql/src/main/java/org/eclipse/dirigible/database/sql/DataTypeUtils.java

Right now the generate project needs to be edited a little because of the mandatory table prefix when generating an application. This will be fix with #3369 
Quick fix:
- in gen/dao/your_tables.js remove the prefix in the table string to be the same as the table in the datasource
fixes #3353, #3370

[#3353] Generate model from schema

---

components/data/data-structures/src/main/java/org/eclipse/dirigible/components/data/structures/domain/Schema.java
components/data/data-structures/src/main/java/org/eclipse/dirigible/components/data/structures/synchronizer/SchemasSynchronizer.java
components/template/template-application-schema/src/main/resources/META-INF/dirigible/template-application-schema/data/application.schema.template
components/test-project/src/main/resources/META-INF/dirigible/test-project/schemas/test.schema

Part of:
- #3378 
The `.schema` file when generating application from `.model` now has `dataSource` _(`DefaultDB` is still default if no datasource is given as an input)_ and is taken in mind when doing CRUD operations from the EDM, eg - new entity will be created in the chosen dataSource instead of `DefaultDB`.
Next part will be to implement support for each entity to be able to have different datasource.

[Schema] Support for different datasource for whole model

---

components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/dto/ActionData.java
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/endpoint/BpmFlowableEndpoint.java
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/provider/BpmProviderFlowable.java
components/engine/engine-bpm-flowable/src/main/resources/stencilset_bpmn.json
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/bpm-process-instances.html
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/bpm-process-jobs.html
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/extensions/bpm-process-jobs-view.extension
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/js/bpm-perspective.js
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/js/bpm-process-instances.js
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/js/bpm-process-jobs.js
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/services/bpm-process-jobs-view.js

Feature#3335: Retry failed process step impl

---

components/template/template-application-dao/src/main/resources/META-INF/dirigible/template-application-dao/dao/entity.extensionpoint.template
components/template/template-application-dao/src/main/resources/META-INF/dirigible/template-application-dao/dao/entity.ts.template
components/template/template-application-rest/src/main/resources/META-INF/dirigible/template-application-rest/api/entity.ts.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/list/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/manage/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/manage/dialog-window/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/detail/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-list/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/detail/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/detail/dialog-window/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/dialog-filter/index.html.template
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/master-manage/main-details/index.html.template

- Add server side validation via extension point (in the REST API).
- One common extension point for both `trigger` (DAO) and `validate` (REST API) events.
- The extension point was renamed from `${projectName}/${perspectiveName}/${name}` to `${projectName}-${perspectiveName}-${name}` as the `/` symbol is invalid inside the Extensions editor.
- Enhanced validation messages both in the frontend and the backend.
- Add validations for `required` properties and for `data length` of string properties.
- Removes input rules (validation patterns) from the `Filter Dialogs`.
**validation/Student.ts**
```ts
import { StudentEntity } from "../gen/dao/entities/StudentRepository";
export const validate = (entity: StudentEntity) => {
if (entity.Name && entity.Name.length > 13) {
throw new …
```

[EDM] Server side validations

---

components/api/api-messaging/src/main/java/org/eclipse/dirigible/components/api/messaging/MessagingFacade.java
components/core/core-base/src/main/java/org/eclipse/dirigible/components/base/tenant/CallableResultAndException.java
components/core/core-base/src/main/java/org/eclipse/dirigible/components/base/tenant/TenantContext.java
components/core/core-base/src/main/java/org/eclipse/dirigible/components/base/tenant/TenantNotFoundException.java
components/core/core-tenants/src/main/java/org/eclipse/dirigible/components/tenants/tenant/TenantContextImpl.java
components/core/core-tenants/src/main/java/org/eclipse/dirigible/components/tenants/tenant/TenantContextInitFilter.java
components/engine/engine-listeners/src/main/java/org/eclipse/dirigible/components/listeners/service/AsynchronousMessageListener.java
components/engine/engine-listeners/src/main/java/org/eclipse/dirigible/components/listeners/service/AsynchronousMessageListenerFactory.java
components/engine/engine-listeners/src/main/java/org/eclipse/dirigible/components/listeners/service/DestinationNameManager.java
components/engine/engine-listeners/src/main/java/org/eclipse/dirigible/components/listeners/service/Listener.java
components/engine/engine-listeners/src/main/java/org/eclipse/dirigible/components/listeners/service/ListenerCreator.java
components/engine/engine-listeners/src/main/java/org/eclipse/dirigible/components/listeners/service/ListenerDescriptor.java
components/engine/engine-listeners/src/main/java/org/eclipse/dirigible/components/listeners/service/ListenerManager.java
components/engine/engine-listeners/src/main/java/org/eclipse/dirigible/components/listeners/service/ListenerManagerFactory.java
components/engine/engine-listeners/src/main/java/org/eclipse/dirigible/components/listeners/service/ListenerType.java
components/engine/engine-listeners/src/main/java/org/eclipse/dirigible/components/listeners/service/ListenersManager.java
components/engine/engine-listeners/src/main/java/org/eclipse/dirigible/components/listeners/service/MessageConsumer.java
components/engine/engine-listeners/src/main/java/org/eclipse/dirigible/components/listeners/service/MessageProducer.java
components/engine/engine-listeners/src/main/java/org/eclipse/dirigible/components/listeners/service/TenantPropertyManager.java
components/engine/engine-listeners/src/main/java/org/eclipse/dirigible/components/listeners/synchronizer/ListenerSynchronizer.java
components/engine/engine-listeners/src/test/java/org/eclipse/dirigible/components/listeners/endpoint/ListenerEndpointTest.java
components/engine/engine-listeners/src/test/java/org/eclipse/dirigible/components/listeners/repository/ListenerRepositoryTest.java
components/engine/engine-listeners/src/test/java/org/eclipse/dirigible/components/listeners/service/AsynchronousMessageListenerTest.java
components/engine/engine-listeners/src/test/java/org/eclipse/dirigible/components/listeners/service/ListenerManagerFactoryTest.java
components/engine/engine-listeners/src/test/java/org/eclipse/dirigible/components/listeners/service/ListenerManagerTest.java
components/engine/engine-listeners/src/test/java/org/eclipse/dirigible/components/listeners/service/ListenersManagerTest.java
components/engine/engine-listeners/src/test/java/org/eclipse/dirigible/components/listeners/service/MessageConsumerTest.java
components/engine/engine-listeners/src/test/java/org/eclipse/dirigible/components/listeners/service/MessageProducerTest.java
components/engine/engine-listeners/src/test/java/org/eclipse/dirigible/components/listeners/service/TestTenantContext.java
components/engine/engine-listeners/src/test/java/org/eclipse/dirigible/components/listeners/synchronizer/ListenerSynchronizerTest.java

Implementation of https://github.com/eclipse/dirigible/discussions/3423 [phase 3]
Add multitenancy support for listeners (`*.listener`) and messaging API.
- send messaging to dedicated topic/queue depending on the current tenant
- for the default tenant topic/queue name is used as it is
- for non defualt tenant - a prefix with the current tenant id is added to the topic/queue name
- an example for topic with name `myTopic`
- for the default tenant the name will be `myTopic`
- for a tenant with id `148e34d8-47ff-4e53-9f74-f0100202fdbf` the name will be `148e34d8-47ff-4e53-9f74-f0100202fdbf###myTopic`
- execute listener handlers in the corresponding tenant context
- register a dedicated  message handlers for all provisioned tenants
Example logs for executing …

Multitenancy phase 3 - listeners

---

components/core/core-initializers/src/main/java/org/eclipse/dirigible/components/initializers/synchronizer/SynchronizationJob.java
components/core/core-tenants/src/main/java/org/eclipse/dirigible/components/tenants/provisioning/TenantProvisioningJob.java
components/engine/engine-jobs/src/main/java/org/eclipse/dirigible/components/jobs/DirigibleJob.java
components/engine/engine-jobs/src/main/java/org/eclipse/dirigible/components/jobs/config/QuartzConfig.java
components/engine/engine-jobs/src/main/java/org/eclipse/dirigible/components/jobs/init/JobsInitializer.java

- reschedule system jobs on startup to apply new changes if any
- skip system misfired job executions
- add quartz startup delay to prevent jobs execution before spring boot application startup 
- optimize SynchronizationJob
- remove explicit calls for garbage collection - it causes Dirigible slow down when the job is executed frequently (for example every 100 millis)
- remove ExecutorService since it not needed
- optimize logging

skip misfired jobs executions

---

components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/platform/command.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/platform/index.ts
components/api/api-platform/src/main/java/org/eclipse/dirigible/components/api/platform/CommandFacade.java
components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/template/transformer-on-save.js
components/ide/ide-ui-registry/src/main/resources/META-INF/dirigible/ide-registry/extensions/workspace-after-publish.extension
components/ide/ide-ui-registry/src/main/resources/META-INF/dirigible/ide-registry/extensions/workspace-on-save.extension
components/ide/ide-ui-registry/src/main/resources/META-INF/dirigible/ide-registry/services/compile-typescript.js
components/ide/ide-workspace/src/main/resources/META-INF/dirigible/ide-workspace/ide-workspace-on-save.extensionpoint
modules/commons/commons-process/src/main/java/org/eclipse/dirigible/commons/process/execution/ProcessExecutionFuture.java

- Fixes: https://github.com/eclipse/dirigible/issues/3402
- `CommandFacade` now returns result in case of a command error _(previously an exception was thrown)_
- Adds types to the `command.ts`
- The result of the CommandFacade is in the following format:
```js
{
exitCode: 0, // In case of error, the exitCode is different than 0
standardOutput: "some message",
errorOutput: "some message"
}
// Note: Both standardOutput and errorOutput should be checked!
```
https://github.com/eclipse/dirigible/assets/4092083/c569175c-0fd3-42fd-9fe7-79631c3db9e8

[IDE] Transpile TypeScript files on save

---

components/api/api-cache/src/main/java/org/eclipse/dirigible/components/api/cache/CacheFacade.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/util/FileUtil.java
tests/tests-integrations/src/test/resources/META-INF/dirigible/modules-tests/src/cache/cache-test.ts

- fix storing and getting objects in the cache
With the previous version of the API, it was not able to store objects in the cache.
Example exception:
```
2024-05-07 09:39:45.961 [ERROR] [http-nio-8080-exec-10] [default-tenant] o.e.d.c.e.j.s.JavascriptHandler - Error on processing JavaScript service from project: [codbex-electra], and path: [dao/TestCache.js], with parameters: []
org.graalvm.polyglot.PolyglotException: The Context is already closed.
at com.oracle.truffle.polyglot.PolyglotEngineException.closedException(PolyglotEngineException.java:137) ~[truffle-api-24.0.1.jar!/:na]
at com.oracle.truffle.polyglot.PolyglotContextImpl.checkClosedOrDisposing(PolyglotContextImpl.java:1453) ~[truffle-api-24.0.1.jar!/:na]
at com.oracle.truffle.polyglot.PolyglotContextImpl.enterThreadChanged(Poly …
```

Improve cache API

---

components/core/core-base/src/main/java/org/eclipse/dirigible/components/base/endpoint/BaseEndpoint.java
components/core/core-base/src/main/java/org/eclipse/dirigible/components/base/http/access/HttpSecurityURIConfigurator.java
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/endpoint/BpmFlowableEndpoint.java
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/js/bpm-historic-process-instances.js
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/js/bpm-image-viewer.js
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/js/bpm-process-context.js
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/js/bpm-process-definitions.js
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/js/bpm-process-instances.js
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/js/bpm-process-jobs.js
components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/js/bpm-tasks.js
components/ide/ide-ui-bpm/src/main/resources/META-INF/dirigible/ide-bpm/scripts/app-cfg.js
components/resources/resources-inbox/src/main/resources/META-INF/dirigible/inbox/ui/launchpad/Home/controller.js

FR#4012: Change the namespace of the BpmFlowableEndpoint spring endpoint

---

components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/js/serializer.js
components/template/template-application-dao/src/main/resources/META-INF/dirigible/template-application-dao/dao/entity.ts.template

Skip the creation the following properties in the `*.model` file if they are not needed _(e.g. default or no values)_:
- `dataPrimaryKey`
- `dataAutoIncrement`
- `dataUnique`
- `isRequiredProperty`
- `isCalculatedProperty`
- `calculatedPropertyExpressionCreate`
- `calculatedPropertyExpressionUpdate`
Changes to `*.schema` files:
Changes to `*.model` files:
Fixes: https://github.com/eclipse/dirigible/issues/4050

[EDM] Clean-up output model file

---

components/resources/resources-core/src/main/resources/META-INF/dirigible/resources-core/ui/theming.js

Makes a small change, where it injects the `theming` provider in the `Theme` factory, so that the default theme config can be set even if Dirigible itself has never been loaded before.
#4134

[UI] #4134 - Set default theme config

---

components/engine/engine-security/src/main/java/org/eclipse/dirigible/components/security/config/SecurityFilterConfig.java

To expose TS REST API publicly add access file with role `PUBLIC`.
Example:
API `/snowflake-project/api/snowflake-api.ts`:
Access `/ts/snowflake-project/api/snowflake-api.ts/test`:
Used path `http://localhost:8080/public/ts/snowflake-project/api/snowflake-api.ts/test`.
It does **NOT** require authentication.

Do not expose TS APIs publicly + allow having public TS APIs

---

build/application/pom.xml
components/data/data-management/pom.xml
components/group/group-database/pom.xml
modules/database/database-sql-h2/pom.xml
modules/database/database-sql-hana/pom.xml
modules/database/database-sql-mysql/pom.xml
modules/database/database-sql-snowflake/pom.xml
modules/odata/odata-core-test/pom.xml
modules/odata/odata-samples-northwind/pom.xml

Drivers cleanup.
- include each driver in corresponding `database-sql-*` project
- add databases support by adding only the following
```xml
<dependency>
<groupId>org.eclipse.dirigible</groupId>
<artifactId>dirigible-components-group-database</artifactId>
<type>pom</type>
</dependency>
```
- remove unnecessary declarations

DB drivers declarations refactoring

---

build/application/pom.xml
build/application/src/main/java/org/eclipse/dirigible/DirigibleApplication.java
build/application/src/main/resources/application-spring-boot-admin-client.properties
build/application/src/main/resources/application-spring-boot-admin-server.properties
build/application/src/main/resources/application.properties
components/core/core-base/src/main/java/org/eclipse/dirigible/components/base/http/access/HttpSecurityURIConfigurator.java
components/core/core-base/src/main/java/org/eclipse/dirigible/components/base/http/roles/Roles.java
pom.xml
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/IDE.java
tests/tests-integrations/src/test/java/org/eclipse/dirigible/integration/tests/api/SecurityIT.java
tests/tests-integrations/src/test/java/org/eclipse/dirigible/integration/tests/api/java/CsvimIT.java
tests/tests-integrations/src/test/java/org/eclipse/dirigible/integration/tests/ui/tests/SpringBootAdminIT.java

- Spring Boot Admin Server
To enable the embedded SBA server, activate spring profile `spring-boot-admin-server` using env variable `SPRING_PROFILES_ACTIVE` or via system property `spring.profiles.active` 
The server could be accessed at path `/spring-admin`. For the local scenario the URL will be http://localhost:8080/spring-admin. The path requires role `OPERATOR`.
- Spring Boot Admin Client
To enable the SBA client, activate spring profile `spring-boot-admin-client`
By default it will connect to the embedded SBA server using the default basic credentials. You can configure the client to an external SBA server using the following configurations:
| Config key | Description |
| --- | --- |
| DIRIGIBLE_SPRING_ADMIN_SERVER_URL | SBA Server URL | 
| DIRIGIBLE_SPRING_ADMIN_SERVER_USERNAME | …

Add Spring Boot Admin (SBA) to Dirigible

---

components/ide/ide-ui-database/src/main/resources/META-INF/dirigible/ide-database/explorer/explorer.js
components/ide/ide-ui-result/src/main/resources/META-INF/dirigible/ide-result/js/crud.js
components/ide/ide-ui-result/src/main/resources/META-INF/dirigible/ide-result/js/result.js
components/ide/ide-ui-result/src/main/resources/META-INF/dirigible/ide-result/result.html

work on
- https://github.com/eclipse/dirigible/issues/4442

Add CRUD operations in Results view

---

components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/template/template-report-file.js
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/perspective-report-file.extension
components/template/template-application-ui-angular/src/main/resources/META-INF/dirigible/template-application-ui-angular/ui/perspective/perspective-report-file.js.template

Adds and changes some fields in the perspective and extension template files of the reports. Now when generating a report if you give the navigation extension point of the dashboard the reports will automatically be shown there.

Report Navigation Implementation

---

components/core/core-initializers/src/main/java/org/eclipse/dirigible/components/initializers/synchronizer/SynchronizationProcessor.java
tests/tests-integrations/src/test/java/org/eclipse/dirigible/integration/tests/api/java/CsvimIT.java

Reset synchronization watcher when starting synch processing instead of doing it after the sync execution is completed.
The previous approach leads to skipped file modifications synchronizations, which occur during long synchronization executions. 
Example: if a long running synchronization is executing and a file change is executed in parallel, when the running synchronization complete, it will reset the synch watcher. This will lead to skipped synch execution when the next processing is triggered .
This issue was found when investigating the instability of CsvimIT test execution.

Fix CsvimIT execution stability  - improve files watching reset

---

README.md
components/data/data-source-snowpark/src/main/java/org/eclipse/dirigible/components/data/source/snowpark/SnowflakeDatabaseConfigurator.java
components/data/data-sources/src/main/java/org/eclipse/dirigible/components/data/sources/domain/DataSource.java
components/data/data-sources/src/main/java/org/eclipse/dirigible/components/data/sources/service/CustomDataSourcesService.java
components/ide/ide-ui-databases/src/main/resources/META-INF/dirigible/ide-databases/dialogs/database-dialog.html
components/ide/ide-ui-databases/src/main/resources/META-INF/dirigible/ide-databases/dialogs/database-dialog.js
components/platform-ide/view-databases/src/main/resources/META-INF/dirigible/view-databases/dialogs/database-dialog.html
components/platform-ide/view-databases/src/main/resources/META-INF/dirigible/view-databases/dialogs/database-dialog.js

- Support more advanced datasource properties
Like the one in snowflake - https://docs.snowflake.com/en/developer-guide/jdbc/jdbc-parameters
Example params: `stringsQuotedForColumnDef=false,net.snowflake.jdbc.objectMapper.maxJsonStringLength=180000000,JDBC_GET_DATE_USE_NULL_TIMEZONE=true,enablePatternSearch=true,net.snowflake.jdbc.http_client_socket_timeout_in_ms=300000`
- Update Snowflake database registration template
- Make datasource  user and password optional.
There are scenarios where user and password are optional. For example in Snowflake where token file could be used instead.
- user/pass no longer required param for env data sources

Allow registering Snowflake datasources from UI + enhancements 

---

components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/bpm/process.ts
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/delegate/DirigibleCallDelegate.java
components/engine/engine-bpm-flowable/src/main/java/org/eclipse/dirigible/components/engine/bpm/flowable/dto/ExecutionData.java

Now the execution variables can be accessed as follows:
```ts
import { Process } from "sdk/bpm"
const variables = Process.getExecutionContext().getVariables();
const variable1 = Process.getExecutionContext().getVariable("variableName");
```
Fixes: #4602

[API] BPM - Adds Execution Variables

---

components/ide/ide-ui-bpm-workspace/src/main/resources/META-INF/dirigible/ide-bpm-workspace/js/bpm-process-jobs.js

Set the text of the alert dialog to be preformatted _(using the `<pre>` instead of the `<div>` tag)_.
Without Formatting:
Preformatted:

[IDE] Processes - Content of Jobs Incidents to be Preformatted

---

build/application/pom.xml
build/application/src/main/resources/application.properties

Remove Spring devtools since sometimes it doesn't work due to classloader issues (most probably caused by the Graal).

Remove Spring devtools

---

tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/framework/impl/BrowserImpl.java
tests/tests-framework/src/main/java/org/eclipse/dirigible/tests/util/FileUtil.java

With this PR, Integration tests screenshots archive is reduced **from** `102.1mb` **to** `451kb`

integration tests - remove unnecessary screenshots and files

---

components/api/api-database/src/main/java/org/eclipse/dirigible/components/api/db/DatabaseFacade.java
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/db/insert.ts

Currently, the code assumes that there would be only one primary key column and its type will be long.
In cases where there are multiple PK columns of this type, the code fails.
Example failure:
```log
2025-05-02 14:04:26.168 [ERROR] [flowable-task-Executor-1] [background] o.e.d.c.base.logging.LoggingExecutor - Failed to execute a code [org.eclipse.dirigible.components.api.db.DatabaseFacade$$Lambda/0x0000007002ad9778@3391a0f1] for data source [DirigibleDataSourceImpl{name='DefaultDB', connectionEnhancers=[], originalDataSource=HikariDataSource (DefaultDB), databaseSystem=H2, transactionManager=org.springframework.jdbc.support.JdbcTransactionManager@b5c07cf}]
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "DATE to BIGINT" [22018-232]
at …
```

Support multiple primary keys in insert result

---

components/template/template-form-builder-angularjs/src/main/resources/META-INF/dirigible/template-form-builder-angularjs/ui/controller.js.template
components/template/template-form-builder-angularjs/src/main/resources/META-INF/dirigible/template-form-builder-angularjs/ui/index.html.template
components/ui/editor-form-builder/src/main/resources/META-INF/dirigible/editor-form-builder/editor.html
components/ui/editor-form-builder/src/main/resources/META-INF/dirigible/editor-form-builder/js/editor.js
components/ui/platform-core/src/main/resources/META-INF/dirigible/platform-core/ui/blimpkit/blimpkit.js
components/ui/platform-core/src/main/resources/META-INF/dirigible/platform-core/ui/blimpkit/table.js

Adds a table widget to the form editor.
There is a difference between the feature request and the implementation.
It proved to be rather complicated to fill an HTML table using separate column data lists, so the table model has to be represented by a JSON/JS object with specific structure and properties. Example:
```javascript
$scope.tableData = [
{
"name":"John Doe",
"age":34
},
{
"name":"Jane Doe",
"age":35
}
];
```
The column headers and row keys are set inside the editor.
#4926

[Form Builder] Add table widget

---

components/api/api-database/src/main/java/org/eclipse/dirigible/components/api/db/DatabaseFacade.java

Handle the cases where  `RETURN_GENERATED_KEYS ` is not supported by some DB like Snowflake
Example error:
```log
2025-05-05 14:35:44,508 ERROR [flowable-task-Executor-3] [background] o.e.d.c.a.d.DatabaseFacade [DatabaseFacade.java:398] Failed to execute insert statement [INSERT INTO ***].
net.snowflake.client.jdbc.SnowflakeLoggedFeatureNotSupportedException: null
at net.snowflake.client.jdbc.SnowflakeConnectionV1.prepareStatement(SnowflakeConnectionV1.java:526) ~[snowflake-jdbc-3.23.2.jar!/:3.23.2]
at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:335) ~[HikariCP-5.1.0.jar!/:na]
at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[HikariCP-5.1.0.jar!/:na]
at …
```

Handle RETURN_GENERATED_KEYS not supported during insert by some databases

---

components/api/api-database/src/main/java/org/eclipse/dirigible/components/api/db/DatabaseFacade.java
components/api/api-database/src/main/java/org/eclipse/dirigible/components/api/db/ParametersSetter.java
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/db/insert.ts

- Add `public static executeMany(sql: string, parameters?: ((string | number | boolean | Date | InsertParameter)[])[], datasourceName?: string):  Array<Array<Record<string, any>>> ` to `insert.ts`
- Fix setting params which are floating point - until now for example `3.0` was treated as int which causes exceptions during batch execution

Enhance DB API

---

components/ui/platform-core/src/main/resources/META-INF/dirigible/platform-core/ui/platform/shell.js

Introduces autohide for notifications. When a notifications is shown, it will stay for 4 seconds after which it will be hidden. If the user hovers over the notification, the timer is cancelled and the notification will hide after the mouse pointer leaves the notification.
#5041

[UI] Notifications should autohide after a while

---

components/engine/engine-camel/src/main/java/org/eclipse/dirigible/components/engine/camel/invoke/DirigibleJavaScriptInvokerImpl.java

Fix async camel java script steps execution handling.
Currently, when an error occur in the async execution, the execution looks like "stuck"(running) without any errors/warnings in the logs.
Fix this by:
- Handle promise errors properly in the java code
- Add JS stacktrace to the logs so that issues could be investigated  
- Add async execution timeout - at most 15 minutes
An example failure log:
```log
2025-08-07 15:54:25.975 [ERROR] [flowable-async-job-executor-thread-24] [default-tenant] o.a.c.p.e.DefaultErrorHandler - Failed delivery for (MessageId: 33359D19B1D9808-0000000000000008 on ExchangeId: 33359D19B1D9808-0000000000000008). Exhausted after delivery attempt: 1 caught: org.eclipse.dirigible.components.engine.camel.components.DirigibleJavaScriptException: Exception during …
```

Fix async camel java script steps execution handling

---

components/api/api-log/src/main/java/org/eclipse/dirigible/components/api/log/LogFacade.java
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/log/logging.ts

Enhance logging API with isXxxEnabled functions:
- `isDebugEnabled`
- `isErrorEnabled`
- `isWarnEnabled`
- `isInfoEnabled`
- `isTraceEnabled`
Issue: https://github.com/eclipse-dirigible/dirigible/issues/5244

Enhance logging API with isXxxEnabled functions

---

components/api/api-test/src/test/java/org/eclipse/dirigible/components/api/test/APIAssertTest.java
components/engine/engine-javascript/src/main/java/org/eclipse/dirigible/components/engine/javascript/service/JavascriptHandler.java
modules/engines/engine-graalium/execution/src/main/java/org/eclipse/dirigible/graalium/core/javascript/GraalJSCodeRunner.java
modules/engines/engine-graalium/execution/src/main/java/org/eclipse/dirigible/graalium/core/javascript/GuestLanguageException.java

Enhance script failure logs:
- extract the root cause stack trace if available
- remove double logging
**Currently**, when a JS code call Java code which throw an exception the logs look like this:
<details>
<summary>Expand logs</summary>
```log
2025-09-17 13:19:54.592 [ERROR] [http-nio-8080-exec-8] [default-tenant] o.e.d.c.e.j.s.JavascriptHandler - Error on processing JavaScript service from project: [test], and path: [test-failure.js], with parameters: []
org.graalvm.polyglot.PolyglotException: JavaObject[org.eclipse.dirigible.components.api.db.MyCustomException]
at org.graalvm.polyglot.Context.eval(Context.java:416) ~[polyglot-24.2.2.jar!/:na]
at org.eclipse.dirigible.graalium.core.javascript.GraalJSCodeRunner.run(GraalJSCodeRunner.java:385) …
```

Enhance script failure logs - add more details on java error,  remove double logging

---

components/api/api-log/pom.xml
components/api/api-log/src/main/java/org/eclipse/dirigible/components/api/log/LogFacade.java
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/db/dao.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/http/rs/resource-http-controller.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/log/logging.ts
components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/mongodb/dao.ts
components/engine/engine-javascript/src/main/java/org/eclipse/dirigible/components/engine/javascript/service/JavascriptHandler.java
modules/engines/engine-graalium/execution/src/main/java/org/eclipse/dirigible/graalium/core/javascript/GraalJSCodeRunner.java
modules/engines/engine-graalium/execution/src/main/java/org/eclipse/dirigible/graalium/core/javascript/GuestLanguageException.java

Enhance logging in the different scenarios by fixing the logged messages, exceptions and adding stack traces to the logs.
Compare the master and PR logs to see the difference.
- Test files
```javascript
import { throwErr } from "test/my-lib"
import { logging } from "sdk/log";
const logger = logging.getLogger("org.eclipse.dirigible.testlogger");
try {
throwErr();
} catch (e) {
logger.error("An error occurred ", e)
}
export function throwErr() {
throw new Error("My intentional error.");
}
```
- Traces in **master** branch:
<details>
<summary>Expand logs</summary>
```log
2025-09-18 13:47:51.314 [ERROR] [http-nio-8080-exec-6] [default-tenant] a.org.eclipse.dirigible.testlogger - An error occurred 
java.lang.Exception: My intentional error.
```
</details>
- Traces in the **current PR** …

TypeScript logging API - fix logging ex/error stack traces

---

build/application/pom.xml
components/group/group-database/pom.xml

Remove schema export/import processes from **dirigible-components-group-database** dependency so that it id not automatically included in the projects.
It should be explicitly added in the projects where it is needed since it depends on CMIS, BPM, etc.

Refactor export/import schema dependency
